In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import csv
from scipy.stats import norm
import scipy.stats as stats
import statsmodels.api as sm
from patsy import dmatrices #a Python library for describing statistical models and building Design Matrices using R-like formulas.
import matplotlib.pyplot as plt
%matplotlib inline
import plotly.express as px 
from statsmodels.tsa.api import SimpleExpSmoothing
from statistics import stdev
from statistics import mean

In [2]:
!pip install yfinance --upgrade --no-cache-dir
import yfinance as yf
from pandas_datareader import data as pdr
yf.pdr_override()

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 62 kB 21.4 MB/s 
  Attempting uninstall: requests
    Found existing installation: requests 2.23.0
    Uninstalling requests-2.23.0:
      Successfully uninstalled requests-2.23.0


In [3]:
#φτιάχνω τη λίστα με τα assets μου -> 50 μετοχές 
#διόρθωση : θα βγάλω τυχαία άλλες 4 μετοχές μαζί με την OGN επειδή δεν έχει το ίδιο μέγεθος με τις άλλες 
#βγάζω OGN ,WRK,HST,CE,ACN
assets= ["ABBV","AEP","AIZ","ALLE","AMAT","AMP","AMZN","AVB","AVY",   
  "AXP","BDX","BF-B","BMY","BR","CARR","CDW","CHTR","CNC",   
  "CNP","COP","CTAS","CZR","DG","DPZ","DRE","DXC","META","FTV",   
  "GOOG","GPC","HIG","JPM","KR","PG","PPL","PRU",   
  "PYPL","RE","ROL","ROST","UNH","URI","V","VRSK","XOM"]

In [4]:
#άρα πρέπει να κατεβάσουμε όλα τα adj close για όλες τις τιμές όλων των μετοχών και να κάνουμε απόλυτο ranking και σε 5 κλασεις (targets)
r=pd.DataFrame(index=pdr.get_data_yahoo(assets[0],'2021-01-01','2022-04-01')['Adj Close'].index)

[*********************100%***********************]  1 of 1 completed


In [5]:
#παίρνω τιμές για ένα χρόνο και 3 μήνες
for i in assets:
  # print('i metoxi me onoma:',i,'exei megethos',pdr.get_data_yahoo(i,'2021-01-01','2022-04-01')['Adj Close'].count())
  temp= pdr.get_data_yahoo(i,'2021-01-01','2022-04-01')['Adj Close']
  temp=temp.dropna()
  r[i]=temp.values

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%********

In [6]:
#φτιάχνω ένα αντίγραφο με τις τιμές για να το έχω 
rd=pd.DataFrame(r)
rd

ABBV        AEP         AIZ        ALLE        AMAT  \
Date                                                                    
2021-01-04   96.813492  76.819260  128.241989  111.874290   85.672462   
2021-01-05   97.814583  76.715622  128.280823  112.089272   88.364830   
2021-01-06   96.969612  77.327995  133.911011  114.639877   89.577888   
2021-01-07   98.007462  75.264778  135.260315  117.659554   93.256454   
2021-01-08   98.521782  74.595879  134.551682  117.249107   94.242668   
...                ...        ...         ...         ...         ...   
2022-03-25  156.891495  95.333153  183.029373  111.363403  136.376923   
2022-03-28  157.513885  96.091171  182.225754  112.533562  136.973938   
2022-03-29  157.718109  97.154373  179.884308  114.090469  140.735092   
2022-03-30  159.244919  97.873009  180.737549  112.404640  135.123199   
2022-03-31  157.650024  98.217560  180.400223  108.864418  131.143127   

                   AMP        AMZN         AVB         AVY         AXP  ...  \
Date                                                                    ...   
2021-01-04  182.556030  159.331497  147.581161  148.152328  115.185806  ...   
2021-01-05  181.488495  160.925507  147.154129  148.474213  115.800583  ...   
2021-01-06  191.901703  156.919006  151.101746  154.150620  120.084435  ...   
2021-01-07  194.221130  158.108002  149.042526  158.958969  119.134567  ...   
2021-01-08  195.599182  159.134995  150.352081  152.882690  119.252083  ...   
...                ...         ...         ...         ...         ...  ...   
2022-03-25  311.729828  164.773499  241.656281  171.694946  188.315094  ...   
2022-03-28  308.232391  168.990494  244.344177  172.051941  187.741089  ...   
2022-03-29  309.342041  169.315002  252.427429  177.406876  188.968292  ...   
2022-03-30  307.737000  166.300995  247.785416  175.354156  187.800461  ...   
2022-03-31  297.591339  162.997498  244.264587  172.518021  185.068985  ...   

                   PRU        PYPL          RE        ROL        ROST  \
Date                                                                    
2021-01-04   70.458305  231.919998  218.876419  37.469650  114.689148   
2021-01-05   71.140762  234.910004  217.072510  38.086960  114.787102   
2021-01-06   75.355347  226.830002  229.939713  38.714066  119.802994   
2021-01-07   75.023354  235.039993  231.590073  39.360771  119.538467   
2021-01-08   74.423889  242.460007  229.296844  39.978077  119.920547   
...                ...         ...         ...        ...         ...   
2022-03-25  118.004997  113.760002  295.426666  33.621418   89.567093   
2022-03-28  117.223892  116.169998  294.201508  34.228012   90.897392   
2022-03-29  118.004997  121.180000  298.953888  34.953945   94.858521   
2022-03-30  117.458229  118.489998  301.068237  35.242325   91.939789   
2022-03-31  115.378540  115.650002  297.768280  34.854500   89.805344   

                   UNH         URI           V        VRSK        XOM  
Date                                                                   
2021-01-04  341.345001  229.649994  215.285767  200.593628  37.906910  
2021-01-05  336.754608  235.570007  212.072693  199.693878  39.733753  
2021-01-06  350.887024  256.549988  210.204163  197.805405  40.747643  
2021-01-07  356.512573  264.679993  211.380630  198.705139  41.067345  
2021-01-08  354.910889  260.149994  213.001999  198.635925  41.524048  
...                ...         ...         ...         ...        ...  
2022-03-25  509.607941  363.670013  217.628143  207.255630  83.524574  
2022-03-28  509.776794  363.399994  219.959564  210.842758  81.181572  
2022-03-29  507.323273  365.200012  227.282562  214.031296  80.750229  
2022-03-30  517.345947  359.190002  223.127884  216.193527  82.132500  
2022-03-31  506.568329  355.209991  220.955887  213.861923  80.965904  

[314 rows x 45 columns]

In [7]:
rd1= rd.pct_change().shift(-1)
rd1=rd1.dropna()
rd1

ABBV       AEP       AIZ      ALLE      AMAT       AMP  \
Date                                                                     
2021-01-04  0.010340 -0.001349  0.000303  0.001922  0.031426 -0.005848   
2021-01-05 -0.008638  0.007982  0.043890  0.022755  0.013728  0.057377   
2021-01-06  0.010703 -0.026681  0.010076  0.026341  0.041066  0.012087   
2021-01-07  0.005248 -0.008887 -0.005239 -0.003488  0.010575  0.007095   
2021-01-08  0.016314 -0.005052 -0.005772  0.002917  0.025115  0.000149   
...              ...       ...       ...       ...       ...       ...   
2022-03-24  0.006551  0.004148  0.008804 -0.002576 -0.011040  0.009335   
2022-03-25  0.003967  0.007951 -0.004391  0.010508  0.004378 -0.011219   
2022-03-28  0.001297  0.011065 -0.012849  0.013835  0.027459  0.003600   
2022-03-29  0.009681  0.007397  0.004743 -0.014776 -0.039876 -0.005189   
2022-03-30 -0.010015  0.003520 -0.001866 -0.031495 -0.029455 -0.032969   

                AMZN       AVB       AVY       AXP  ...       PRU      PYPL  \
Date                                                ...                       
2021-01-04  0.010004 -0.002894  0.002173  0.005337  ...  0.009686  0.012892   
2021-01-05 -0.024897  0.026826  0.038232  0.036993  ...  0.059243 -0.034396   
2021-01-06  0.007577 -0.013628  0.031193 -0.007910  ... -0.004406  0.036194   
2021-01-07  0.006496  0.008786 -0.038225  0.000986  ... -0.007990  0.031569   
2021-01-08 -0.021519 -0.006690  0.029282 -0.005912  ...  0.000992 -0.020457   
...              ...       ...       ...       ...  ...       ...       ...   
2022-03-24  0.006868  0.016612  0.037885  0.007359  ...  0.014266 -0.019733   
2022-03-25  0.025593  0.011123  0.002079 -0.003048  ... -0.006619  0.021185   
2022-03-28  0.001920  0.033081  0.031124  0.006537  ...  0.006663  0.043126   
2022-03-29 -0.017801 -0.018389 -0.011571 -0.006180  ... -0.004633 -0.022198   
2022-03-30 -0.019865 -0.014209 -0.016174 -0.014545  ... -0.017706 -0.023968   

                  RE       ROL      ROST       UNH       URI         V  \
Date                                                                     
2021-01-04 -0.008242  0.016475  0.000854 -0.013448  0.025778 -0.014925   
2021-01-05  0.059276  0.016465  0.043697  0.041967  0.089060 -0.008811   
2021-01-06  0.007177  0.016705 -0.002208  0.016032  0.031690  0.005597   
2021-01-07 -0.009902  0.015683  0.003196 -0.004493 -0.017115  0.007670   
2021-01-08 -0.007198  0.002696 -0.012581 -0.007265 -0.010379 -0.011882   
...              ...       ...       ...       ...       ...       ...   
2022-03-24  0.013593  0.008050 -0.002212 -0.000837  0.013065  0.005154   
2022-03-25 -0.004147  0.018042  0.014853  0.000331 -0.000742  0.010713   
2022-03-28  0.016153  0.021209  0.043578 -0.004813  0.004953  0.033292   
2022-03-29  0.007072  0.008250 -0.030769  0.019756 -0.016457 -0.018280   
2022-03-30 -0.010961 -0.011005 -0.023216 -0.020833 -0.011081 -0.009734   

                VRSK       XOM  
Date                            
2021-01-04 -0.004485  0.048193  
2021-01-05 -0.009457  0.025517  
2021-01-06  0.004549  0.007846  
2021-01-07 -0.000348  0.011121  
2021-01-08 -0.015082  0.030356  
...              ...       ...  
2022-03-24 -0.001153  0.021828  
2022-03-25  0.017308 -0.028052  
2022-03-28  0.015123 -0.005313  
2022-03-29  0.010102  0.017118  
2022-03-30 -0.010785 -0.014204  

[313 rows x 45 columns]

In [12]:
def pct_for2(st,i,title):
  print(i)
  insample=st.iloc[:-i]
  
  outsample=st.iloc[-i:]
  
  insample.index=pd.to_datetime(insample.index)
  outsample.index=pd.to_datetime(outsample.index)
  print('auto einai to insample',insample)
  print('auto einai to outsample',outsample)
  pred = outsample.copy()
  # print(insample.values)
  model = SimpleExpSmoothing(np.asarray(insample.values))
  model.index = pd.to_datetime(insample.index)
  # print(model)
  fit1 = model.fit()
  # print(fit1.fittedvalues)
  pred1=fit1.forecast(1)
  # print(pred1)
  # print("alpha= ",fit1.params['smoothing_level'])
  # print(insample.values)
  # print(st.index[-i])
  dif=np.subtract(insample.values,fit1.fittedvalues)
  # print(dif)
  me=dif.mean()
  sd=dif.std()
  print("prediction->",pred1[0])
  print("mean->",me)
  print("sd->",sd)
  x= np.arange((pred1[0]+me)-3*sd,(pred1[0]+me)+ 3*sd,0.001)
  #print(x)
  pdf= stats.norm.pdf(x, loc=me+pred1, scale=sd)
  plt.plot(x,pdf,label=title)
  return pred1+me,sd

In [13]:
def cdf(r1,r2,r3,r4,mean,sd):
  temp=[]
  #print(mean,sd)
  p1=norm(loc = mean , scale =sd ).cdf(r1)
  p2=norm(loc = mean , scale =sd ).cdf(r2)-p1
  p3=norm(loc = mean , scale =sd ).cdf(r3)-p1-p2
  p4=norm(loc = mean , scale =sd ).cdf(r4)-p1-p2-p3
  p5=1-p1-p2-p3-p4
  temp.append(p1)
  temp.append(p2)
  temp.append(p3)
  temp.append(p4)
  temp.append(p5)
  return temp

In [14]:
def RPS_calculation(hist_data, submission, asset_no=44):
    # print('check')
    if hist_data.shape[0]<=asset_no:
        return np.nan    
    # print('check')
    asset_id = pd.unique(hist_data.symbol)
    
    for i in range(len(pd.unique(hist_data.date))):
        if len(hist_data[hist_data.date == pd.unique(hist_data.date)[i]])<len(asset_id):
            for asset in [x for x in asset_id if x not in hist_data[hist_data.date == pd.unique(hist_data.date)[i]].symbol.values]:
                right_price = hist_data[hist_data.symbol==asset].sort_values(by='date')
                right_price = right_price[right_price.date <= pd.unique(hist_data.date)[i]]
                right_price = right_price.price.iloc[-1]
                hist_data = hist_data.append({'date' : pd.unique(hist_data.date)[i],
                                               'symbol' : asset,
                                               'price' : right_price}, ignore_index=True)

    #Compute percentage returns
    asset_id = sorted(asset_id) 

    #Compute percentage returns
    returns = pd.DataFrame(columns = ["ID", "Return"])
    
    # min_date = min(hist_data.date)
    # max_date = max(hist_data.date)

    #alternative for point forecast
    min_date = min(hist_data.date)
    max_date = np.max(hist_data.date)
    
    for i in range(0,len(asset_id)):
        temp = hist_data.loc[hist_data.symbol==asset_id[i]]
        
        open_price = float(temp.loc[temp.date==min_date].price)
        close_price = float(temp.loc[temp.date==max_date].price)
        
        returns = returns.append({'ID': temp.symbol.iloc[0], 
                                'Return': (close_price - open_price)/open_price}, ignore_index=True)

    #Define the relevant position of each asset
    ranking = pd.DataFrame(columns=["ID", "Position", "Return"])
    ranking.ID = list(asset_id)
    ranking.Return = returns.Return
    ranking.Position = ranking.Return.rank(method = 'min')

    #Handle Ties
    Series_per_position = pd.DataFrame(columns=["Position","Series", "Rank", "Rank1", "Rank2","Rank3", "Rank4", "Rank5"])
    Series_per_position.Position = list(pd.unique(ranking.Position.sort_values(ascending=True)))
    temp = ranking.Position.value_counts()
    temp = pd.DataFrame(zip(temp.index, temp), columns = ["Rank", "Occurencies"])
    temp = temp.sort_values(by = ["Rank"],ascending=True)
    Series_per_position.Series = list(temp.Occurencies)
    Series_per_position

    total_ranks = Series_per_position.Position.values[-1]
    for i in range(0,Series_per_position.shape[0]):
    
        start_p = Series_per_position.Position[i]
        end_p = Series_per_position.Position[i] + Series_per_position.Series[i]
        temp = pd.DataFrame(columns = ["Position","Rank", "Rank1", "Rank2", "Rank3", "Rank4","Rank5"])
        temp.Position = list(range(int(start_p),int(end_p)))

        if(temp.loc[temp.Position.isin(list(range(1,int(0.2*total_ranks+1))))].empty==False):
            temp.loc[temp.Position.isin(list(range(1,int(0.2*total_ranks+1))))] = temp.loc[temp.Position.isin(list(range(1,int(0.2*total_ranks+1))))].assign(Rank=1)
            temp.loc[temp.Position.isin(list(range(1,int(0.2*total_ranks+1))))] = temp.loc[temp.Position.isin(list(range(1,int(0.2*total_ranks+1))))].assign(Rank1=1.0)

        elif(temp.loc[temp.Position.isin(list(range(int(0.2*total_ranks+1),int(0.4*total_ranks+1))))].empty==False):
            temp.loc[temp.Position.isin(list(range(int(0.2*total_ranks+1),int(0.4*total_ranks+1))))] = temp.loc[temp.Position.isin(list(range(int(0.2*total_ranks+1),int(0.4*total_ranks+1))))].assign(Rank=2)
            temp.loc[temp.Position.isin(list(range(int(0.2*total_ranks+1),int(0.4*total_ranks+1))))] = temp.loc[temp.Position.isin(list(range(int(0.2*total_ranks+1),int(0.4*total_ranks+1))))].assign(Rank2=1.0)

        elif(temp.loc[temp.Position.isin(list(range(int(0.4*total_ranks+1),int(0.6*total_ranks+1))))].empty==False):
            temp.loc[temp.Position.isin(list(range(int(0.4*total_ranks+1),int(0.6*total_ranks+1))))] = temp.loc[temp.Position.isin(list(range(int(0.4*total_ranks+1),int(0.6*total_ranks+1))))].assign(Rank=3)
            temp.loc[temp.Position.isin(list(range(int(0.4*total_ranks+1),int(0.6*total_ranks+1))))] = temp.loc[temp.Position.isin(list(range(int(0.4*total_ranks+1),int(0.6*total_ranks+1))))].assign(Rank3=1.0)

        elif(temp.loc[temp.Position.isin(list(range(int(0.6*total_ranks+1),int(0.8*total_ranks+1))))].empty==False):
            temp.loc[temp.Position.isin(list(range(int(0.6*total_ranks+1),int(0.8*total_ranks+1))))] = temp.loc[temp.Position.isin(list(range(int(0.6*total_ranks+1),int(0.8*total_ranks+1))))].assign(Rank=4)
            temp.loc[temp.Position.isin(list(range(int(0.6*total_ranks+1),int(0.8*total_ranks+1))))] = temp.loc[temp.Position.isin(list(range(int(0.6*total_ranks+1),int(0.8*total_ranks+1))))].assign(Rank4=1.0)

        elif(temp.loc[temp.Position.isin(list(range(int(0.8*total_ranks+1),int(total_ranks+1))))].empty==False):
            temp.loc[temp.Position.isin(list(range(int(0.8*total_ranks+1),int(total_ranks+1))))] = temp.loc[temp.Position.isin(list(range(int(0.8*total_ranks+1),int(total_ranks+1))))].assign(Rank=5)
            temp.loc[temp.Position.isin(list(range(int(0.8*total_ranks+1),int(total_ranks+1))))] = temp.loc[temp.Position.isin(list(range(int(0.8*total_ranks+1),int(total_ranks+1))))].assign(Rank5=1.0)
        temp = temp.fillna(0)
        Series_per_position.iloc[i,2:Series_per_position.shape[1]] = temp.mean(axis = 0).iloc[1:temp.shape[1]]

    Series_per_position = Series_per_position.drop('Series', axis = 1)
    ranking = pd.merge(ranking,Series_per_position, on = "Position")
    ranking = ranking[["ID", "Return", "Position", "Rank", "Rank1", "Rank2", "Rank3", "Rank4", "Rank5"]]
    ranking = ranking.sort_values(["Position"])
    # print(ranking)
    #Evaluate submission
    rps_sub = []
    #for aid in list((pd.unique(ranking.ID))):
    for aid in asset_id:

        target = np.cumsum(ranking.loc[ranking.ID==aid].iloc[:,4:9].values).tolist()
        frc = np.cumsum(submission.loc[submission.ID==aid].iloc[:,1:6].values).tolist()
        rps_sub.append(np.mean([(a - b)**2 for a, b in zip(target, frc)]))
    submission["RPS"] = rps_sub
    
    output = {'RPS' : np.mean(rps_sub),
              'details' : submission}
    
    return(output)

In [18]:
from collections import OrderedDict
def pct_vis2(data):
  final=dict()
  for i in range(253,len(data.index)-1,1):
    print('i=========',data.index[i])
    day=[]
    d=data.loc[data.index[i]] #για κάθε μέρα μετά τις πρώτες 253 μέρες (χρειάζονται για το insample)
    plt.figure(figsize=(18,10))
    plt.title(data.index[i])
    temp=dict()
    for j in range(len(d.index)):#για κάθε μετοχή 
      # print(d.index[j],'kai',i,'kai',data[d.index[j]])
      x,y=pct_for2(data[d.index[j]],i,d.index[j])
      print(x,y)
      temp[x[0]]=y #θα κρατάω σε ένα dict ta means και τα sd των κατανομών 
    res = list(temp.keys())#εδώ θα έχω όλα τα keys
    # temp2=dict(sorted(temp.items()))#εδώ θα έχω τα means sorted των κατανομών σε αύξουσα σειρά (λίστα)
    temp2=sorted(temp.keys())
    print('temp2',temp2)
    R1=temp2[8]#To δέκατο στοιχείο
    R2=temp2[18]#Το 20ο κ.λ.π.
    R3=temp2[27]
    R4=temp2[36]
    print(R1,R2,R3,R4)
  
    #φτιάχνω μια συνάρτηση τώρα που δίνω τις περιοχές και τις τιμές κάθε μετοχής  και μου επιστρέφει έναν πίνακα με τις πιθανότητες
    for k in range(len(d.index)):
      #print(k)
      js=cdf(R1,R2,R3,R4,res[k],temp[res[k]]) #επιστρέφει έναν πίνακα με τα ranks κάθε μετοχής για εκείνη τη μέρα
      #print(js,d.index[k])
      day.append(js)
    plt.legend()
    plt.ylim(0)
    final[data.index[i]]=day
    
  #print(len(final))
  return final
final=pct_vis2(rd1)

Output hidden; open in https://colab.research.google.com to view.

In [20]:
t2=pd.DataFrame.from_dict(final).T
t2.columns=assets
t2=t2.rename_axis('date')
t2=t2.reset_index()
t2

date                                               ABBV  \
0  2022-01-04  [0.4718948929454726, 0.03080035344925769, 0.02...   
1  2022-01-05  [0.4800434933847417, 0.028583163158277358, 0.0...   
2  2022-01-06  [0.4842879275426568, 0.03141706805030453, 0.03...   
3  2022-01-07  [0.48548724941317806, 0.031667378145671055, 0....   
4  2022-01-10  [0.48795355871486273, 0.03176434550317159, 0.0...   
5  2022-01-11  [0.49018445268379596, 0.02858447827962285, 0.0...   
6  2022-01-12  [0.4803643239067152, 0.03308852496828135, 0.01...   
7  2022-01-13  [0.4810374836790122, 0.029622152820288683, 0.0...   
8  2022-01-14  [0.48455355510541764, 0.04054294040401407, 0.0...   
9  2022-01-18  [0.4829171284520646, 0.037093578197812005, 0.0...   
10 2022-01-19  [0.48186723430725475, 0.026784832480721166, 0....   
11 2022-01-20  [0.44917070762854433, 0.03761869677831153, 0.0...   
12 2022-01-21  [0.4509205018595917, 0.03622206171832243, 0.03...   
13 2022-01-24  [0.45989945749816163, 0.0373055895595788, 0.04...   
14 2022-01-25  [0.4614424275700435, 0.03185679063290492, 0.04...   
15 2022-01-26  [0.4548721291958188, 0.03283463206831394, 0.04...   
16 2022-01-27  [0.4619955034760625, 0.027546347959616968, 0.0...   
17 2022-01-28  [0.4485726778462049, 0.04155673849894631, 0.05...   
18 2022-01-31  [0.4656219700247641, 0.01457223735861407, 0.04...   
19 2022-02-01  [0.4487690311124107, 0.019438572643140917, 0.0...   
20 2022-02-02  [0.44250474290892944, 0.030816634792092845, 0....   
21 2022-02-03  [0.44332668924960694, 0.027896731603529568, 0....   
22 2022-02-04  [0.4436880237800274, 0.02256601210254716, 0.03...   
23 2022-02-07  [0.42124441831812653, 0.02847663827724556, 0.0...   
24 2022-02-08  [0.43696108704377096, 0.017743541699771492, 0....   
25 2022-02-09  [0.4395680865163409, 0.02444506093246307, 0.04...   
26 2022-02-10  [0.4552168691720036, 0.021511317683767572, 0.0...   
27 2022-02-11  [0.4440699249800915, 0.03000450039201319, 0.04...   
28 2022-02-14  [0.4575730078122303, 0.0367798204279251, 0.031...   
29 2022-02-15  [0.4540932571957872, 0.02685590772555413, 0.02...   
30 2022-02-16  [0.4524520128741629, 0.03908252323861089, 0.02...   
31 2022-02-17  [0.46558663064776157, 0.043214802258334684, 0....   
32 2022-02-18  [0.4723663373294362, 0.03428030420967898, 0.02...   
33 2022-02-22  [0.4787719320853964, 0.029734150286476024, 0.0...   
34 2022-02-23  [0.4768609197965784, 0.03182758814575071, 0.03...   
35 2022-02-24  [0.4675930865338914, 0.03240691346610858, 0.03...   
36 2022-02-25  [0.4328342366110576, 0.05061944268567298, 0.03...   
37 2022-02-28  [0.3744369378289906, 0.04424848014490185, 0.04...   
38 2022-03-01  [0.2766157026621082, 0.03539599202859167, 0.04...   
39 2022-03-02  [0.4226802322133186, 0.04390764385857415, 0.03...   
40 2022-03-03  [0.5818868002944237, 0.06062336055458595, 0.03...   
41 2022-03-04  [0.6622724968056053, 0.057614169276897, 0.0396...   
42 2022-03-07  [0.5908382997017079, 0.1399734310064108, 0.060...   
43 2022-03-08  [0.6637008048388089, 0.0567210845804309, 0.048...   
44 2022-03-09  [0.8539073163579962, 0.13004977061580225, 0.00...   
45 2022-03-10  [0.39057558951755095, 0.31481340173906663, 0.0...   
46 2022-03-11  [0.32892360637621787, 0.19477208270543456, 0.0...   
47 2022-03-14  [0.25902517773926015, 0.19051372194102, 0.0773...   
48 2022-03-15  [0.21540883589106685, 0.13706736798669872, 0.0...   
49 2022-03-16  [0.09435049197829704, 0.17276531926417266, 0.1...   
50 2022-03-17  [0.09404790057958395, 0.16311346065893495, 0.1...   
51 2022-03-18  [0.08900658503839165, 0.19433142971146222, 0.1...   
52 2022-03-21  [0.05475207883347523, 0.17045981139695027, 0.1...   
53 2022-03-22  [0.07443242190249244, 0.15617799409797173, 0.1...   
54 2022-03-23  [0.07635476977239525, 0.275930043733217, 0.273...   
55 2022-03-24  [0.09197256723741237, 0.34319943631007244, 0.1...   
56 2022-03-25  [0.334399179443498, 0.30343465872407044, 0.165...   
57 2022-03-28  [0.31103246241337534, 0.3947363492872076, 0.20... 

In [21]:
def create_historical(prob):
  prob=prob.rename_axis("symbol", axis="columns")
  prob=prob.T
  prob['date']=prob.columns.date[0]
  prob.columns = ['price', 'date']
  prob=prob.reset_index()
  prob=prob[['symbol','date','price']]
  return prob

In [22]:
RPS=pd.DataFrame()

# RPS=RPS.drop('date',axis=1)
# print(RPS.index[2])
for k in t2.index: #for everyday of a stock->index
  prob=pd.DataFrame()
  prob1=pd.DataFrame()
  predic=pd.DataFrame()
  if(t2['date'][k]!=t2['date'].tail(1).values): #if it's not for the last day 
    #for historical data of two days 
    prob=rd.loc[(rd.index.date==t2['date'][k])]
    prob1=rd.loc[ (rd.index.date==t2['date'][k+1])]
    prob=create_historical(prob)
    prob1=create_historical(prob1)
    hist_data=prob.append(prob1)
    # print(hist_data)
    predic=t2.loc[t2['date']==t2['date'][k]] #find predictions of this day
    predic=predic.drop('date',axis=1)
    # print(predic)
    data=pd.DataFrame(index=predic.columns)
    data=data.reset_index()
    # print(data)
    data[['Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']]=(0,0,0,0,0)
    for i in range(len(np.array_split(predic.values[0],46))-1):
      # print(i)
      # print(np.array_split(predic.values[0],46)[i][0])
      data.loc[i,['Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']]=np.array_split(predic.values[0],46)[i][0]
    data.columns = ['ID','Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']
    # print(data)
    #now we have data->predictions and hist_data->historical data so now we can call the RPS
    rps=RPS_calculation(hist_data = hist_data , submission = data)['details']
    # print(rps) ->rps for every stock for one day 
    # print(rps['RPS'])
    tmp=pd.DataFrame(rps['RPS'].values).T
    # print(tmp.T)
    RPS=RPS.append(tmp,ignore_index=True)
    # print(RPS[RPS.index==k])

    
  else:
    #for the last day
    prob=rd.loc[(rd.index.date==t2['date'][k])]
    prob1=rd.loc[ (rd.index.date==rd.index.date[-1])]
    prob=create_historical(prob)
    prob1=create_historical(prob1)
    hist_data=prob.append(prob1)
    # print(hist_data)
    predic=t2.loc[t2['date']==t2['date'][k]] #find predictions of this day
    predic=predic.drop('date',axis=1)
    # print(predic)
    data=pd.DataFrame(index=predic.columns)
    data=data.reset_index()
    # print(data)
    data[['Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']]=(0,0,0,0,0)
    for i in range(len(np.array_split(predic.values[0],46))-1):
      # print(i)
      # print(np.array_split(predic.values[0],46)[i][0])
      data.loc[i,['Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']]=np.array_split(predic.values[0],46)[i][0]
    data.columns = ['ID','Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']
    # print(data)
    #now we have data->predictions and hist_data->historical data so now we can call the RPS
    rps=RPS_calculation(hist_data = hist_data , submission = data)['details']
    # print(rps) ->rps for every stock for one day 
    # print(rps['RPS'])
    tmp=pd.DataFrame(rps['RPS'].values).T
    # print(tmp.T)
    RPS=RPS.append(tmp,ignore_index=True)              
print(RPS)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior.  In a future version these will be considered non-comparable.Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.
  # This is added back by InteractiveShellApp.init_path()
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior.  In a future version these will be considered non-comparable.Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.
  if sys.path[0] == '':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:42: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior.  In a future version these will be considered non-comparable.Use 'ts == pd.Timestamp(date)' or 'ts.date() == dat

          0         1         2         3         4         5         6   \
0   0.214670  0.216166  0.182459  0.187599  0.257980  0.167144  0.179912   
1   0.172538  0.169727  0.185800  0.203540  0.156326  0.167669  0.164743   
2   0.176507  0.219374  0.202671  0.184587  0.246837  0.172627  0.179254   
3   0.233104  0.164969  0.198611  0.182163  0.217770  0.178461  0.159574   
4   0.169774  0.188752  0.178878  0.180418  0.172284  0.166625  0.242500   
5   0.178952  0.179766  0.188042  0.185665  0.156599  0.169639  0.170006   
6   0.181711  0.208840  0.186515  0.182369  0.215522  0.169418  0.175821   
7   0.222469  0.184464  0.179226  0.181680  0.158828  0.164968  0.198820   
8   0.234074  0.182540  0.176599  0.183422  0.240016  0.241898  0.163424   
9   0.166702  0.185052  0.176463  0.176155  0.240253  0.241434  0.159979   
10  0.169288  0.187719  0.179820  0.200942  0.249496  0.179240  0.168887   
11  0.177206  0.224020  0.176096  0.204887  0.216745  0.232692  0.163358   
12  0.172400

In [23]:
d=t2['date']
name=t2.columns[:-1]
# print(np.split(name.values,len(name)))
# print(d.values)
RPS['date']=d.values
RPS=RPS.set_index('date')
RPS.columns=assets
RPS

ABBV       AEP       AIZ      ALLE      AMAT       AMP  \
date                                                                     
2022-01-04  0.214670  0.216166  0.182459  0.187599  0.257980  0.167144   
2022-01-05  0.172538  0.169727  0.185800  0.203540  0.156326  0.167669   
2022-01-06  0.176507  0.219374  0.202671  0.184587  0.246837  0.172627   
2022-01-07  0.233104  0.164969  0.198611  0.182163  0.217770  0.178461   
2022-01-10  0.169774  0.188752  0.178878  0.180418  0.172284  0.166625   
2022-01-11  0.178952  0.179766  0.188042  0.185665  0.156599  0.169639   
2022-01-12  0.181711  0.208840  0.186515  0.182369  0.215522  0.169418   
2022-01-13  0.222469  0.184464  0.179226  0.181680  0.158828  0.164968   
2022-01-14  0.234074  0.182540  0.176599  0.183422  0.240016  0.241898   
2022-01-18  0.166702  0.185052  0.176463  0.176155  0.240253  0.241434   
2022-01-19  0.169288  0.187719  0.179820  0.200942  0.249496  0.179240   
2022-01-20  0.177206  0.224020  0.176096  0.204887  0.216745  0.232692   
2022-01-21  0.172400  0.172439  0.181139  0.218422  0.162598  0.177875   
2022-01-24  0.223791  0.190030  0.183976  0.170467  0.240798  0.175685   
2022-01-25  0.221258  0.192929  0.214076  0.172519  0.157782  0.160239   
2022-01-26  0.219389  0.184990  0.196493  0.170155  0.241768  0.162255   
2022-01-27  0.165344  0.158938  0.171303  0.178757  0.188935  0.244763   
2022-01-28  0.184348  0.153680  0.170376  0.166454  0.169756  0.156525   
2022-01-31  0.173922  0.159950  0.175023  0.176530  0.188632  0.157863   
2022-02-01  0.161992  0.186031  0.168316  0.168323  0.165709  0.155299   
2022-02-02  0.209347  0.267241  0.184645  0.178365  0.223481  0.213708   
2022-02-03  0.166909  0.151155  0.188640  0.224269  0.191140  0.149828   
2022-02-04  0.202809  0.195165  0.173209  0.186240  0.154792  0.141744   
2022-02-07  0.184229  0.146959  0.189264  0.168908  0.154656  0.177961   
2022-02-08  0.205717  0.148755  0.237206  0.245983  0.141611  0.176531   
2022-02-09  0.207420  0.142163  0.163555  0.158406  0.290932  0.134216   
2022-02-10  0.170844  0.270323  0.239791  0.168877  0.277783  0.275276   
2022-02-11  0.214442  0.134876  0.190435  0.167908  0.186817  0.219990   
2022-02-14  0.166437  0.156536  0.256846  0.161014  0.124081  0.137147   
2022-02-15  0.209119  0.157515  0.259702  0.159936  0.131979  0.149410   
2022-02-16  0.167782  0.301214  0.194552  0.193132  0.232721  0.262461   
2022-02-17  0.157697  0.191110  0.169134  0.169423  0.296014  0.146645   
2022-02-18  0.231346  0.291112  0.193214  0.163169  0.295819  0.177084   
2022-02-22  0.232576  0.158006  0.188126  0.203665  0.192232  0.177478   
2022-02-23  0.171783  0.188320  0.171010  0.170006  0.145719  0.211615   
2022-02-24  0.161355  0.187806  0.166440  0.170481  0.218316  0.157464   
2022-02-25  0.163933  0.276821  0.220701  0.153706  0.221092  0.167987   
2022-02-28  0.144102  0.165895  0.159731  0.252136  0.210124  0.252099   
2022-03-01  0.258210  0.141955  0.158297  0.191661  0.155075  0.157898   
2022-03-02  0.167443  0.234441  0.208430  0.191493  0.262459  0.175014   
2022-03-03  0.186179  0.207619  0.164255  0.162792  0.290713  0.265181   
2022-03-04  0.314594  0.189353  0.169997  0.157730  0.236007  0.270990   
2022-03-07  0.099295  0.170724  0.151402  0.027816  0.336190  0.162872   
2022-03-08  0.121731  0.202462  0.158015  0.293345  0.148038  0.118808   
2022-03-09  0.536150  0.112489  0.125943  0.263607  0.115231  0.138699   
2022-03-10  0.402134  0.131887  0.528401  0.069473  0.192028  0.115324   
2022-03-11  0.252401  0.295395  0.150024  0.221017  0.399580  0.178211   
2022-03-14  0.136922  0.129562  0.151996  0.173660  0.077221  0.118689   
2022-03-15  0.197685  0.142914  0.172185  0.141468  0.070078  0.090256   
2022-03-16  0.084175  0.145712  0.123342  0.180229  0.193046  0.103215   
2022-03-17  0.121736  0.152634  0.206969  0.111944  0.051465  0.170803   
2022-03-18  0.084206  0.181712  0.134305  0.122035  0.295799  0.256162   
2022-03-21  0.216436

In [24]:
RPS.mean(axis=1).mean()

0.19278034684158302

In [ ]:
#save results
RPS.to_excel('Method_3-SES_in_perc_returns.xlsx')

#####Compare with point forecast 
***

In [ ]:
t2.set_index('date',inplace=True)

In [ ]:
flag=False
for i in t2: #for every stock
  print(i)
  for j in range(len(t2[i].values)): #each day of this stock
    temp = t2[i].values[j]
    max= np.max(temp) #find max possiblity
    #replace this max possibility with 1
    temp2=np.where(temp!=max,0,temp)
    temp2=np.where(temp2==max,1,temp2)
    print(temp,'kai',temp2)
    if((temp2==1).sum()>1):
      print('isotimia')
      flag=True
      break
    t2[i].values[j]=temp2

In [ ]:
t2=t2.reset_index()

In [ ]:
flag

False

In [ ]:
RPS=pd.DataFrame()

# RPS=RPS.drop('date',axis=1)
# print(RPS.index[2])
for k in t2.index: #for everyday of a stock->index
  prob=pd.DataFrame()
  prob1=pd.DataFrame()
  predic=pd.DataFrame()
  if(t2['date'][k]!=t2['date'].tail(1).values): #if it's not for the last day 
    #for historical data of two days 
    prob=rd.loc[(rd.index.date==t2['date'][k])]
    prob1=rd.loc[ (rd.index.date==t2['date'][k+1])]
    prob=create_historical(prob)
    prob1=create_historical(prob1)
    hist_data=prob.append(prob1)
    # print(hist_data)
    predic=t2.loc[t2['date']==t2['date'][k]] #find predictions of this day
    predic=predic.drop('date',axis=1)
    # print(predic)
    data=pd.DataFrame(index=predic.columns)
    data=data.reset_index()
    # print(data)
    data[['Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']]=(0,0,0,0,0)
    for i in range(len(np.array_split(predic.values[0],46))-1):
      # print(i)
      print(np.array_split(predic.values[0],46)[i][0])
      data.loc[i,['Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']]=np.array_split(predic.values[0],46)[i][0]
    data.columns = ['ID','Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']
    # print(data)
    print(np.max(hist_data.date))
    #now we have data->predictions and hist_data->historical data so now we can call the RPS
    rps=RPS_calculation(hist_data = hist_data , submission = data)['details']
    # print(rps) ->rps for every stock for one day 
    # print(rps['RPS'])
    tmp=pd.DataFrame(rps['RPS'].values).T
    # print(tmp.T)
    RPS=RPS.append(tmp,ignore_index=True)
    # print(RPS[RPS.index==k])

    
  else:
    #for the last day
    prob=rd.loc[(rd.index.date==t2['date'][k])]
    prob1=rd.loc[ (rd.index.date==rd.index.date[-1])]
    prob=create_historical(prob)
    prob1=create_historical(prob1)
    hist_data=prob.append(prob1)
    # print(hist_data)
    predic=t2.loc[t2['date']==t2['date'][k]] #find predictions of this day
    predic=predic.drop('date',axis=1)
    # print(predic)
    data=pd.DataFrame(index=predic.columns)
    data=data.reset_index()
    # print(data)
    data[['Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']]=(0,0,0,0,0)
    for i in range(len(np.array_split(predic.values[0],46))-1):
      # print(i)
      # print(np.array_split(predic.values[0],46)[i][0])
      data.loc[i,['Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']]=np.array_split(predic.values[0],46)[i][0]
    data.columns = ['ID','Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']
    # print(data)
    
    print(hist_data)
    #now we have data->predictions and hist_data->historical data so now we can call the RPS
    rps=RPS_calculation(hist_data = hist_data , submission = data)['details']
    
    # print(rps) ->rps for every stock for one day 
    # print(rps['RPS'])
    tmp=pd.DataFrame(rps['RPS'].values).T
    # print(tmp.T)
    RPS=RPS.append(tmp,ignore_index=True)              
print(RPS)

[0. 0. 0. 0. 1.]
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[0. 0. 0. 0. 1.]
[0. 0. 0. 0. 1.]
[1. 0. 0. 0. 0.]
[0. 0. 0. 0. 1.]
[1. 0. 0. 0. 0.]
[0. 0. 0. 0. 1.]
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[0. 0. 0. 0. 1.]
[0. 0. 0. 0. 1.]
[1. 0. 0. 0. 0.]
[0. 0. 0. 0. 1.]
[0. 0. 0. 0. 1.]
[0. 0. 0. 0. 1.]
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[0. 0. 0. 0. 1.]
[0. 0. 0. 0. 1.]
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[0. 0. 0. 0. 1.]
[0. 0. 0. 0. 1.]
[0. 0. 0. 0. 1.]
[1. 0. 0. 0. 0.]
[0. 0. 0. 0. 1.]
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[0. 0. 0. 0. 1.]
[1. 0. 0. 0. 0.]
[0. 0. 0. 0. 1.]
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[0. 0. 0. 0. 1.]
[0. 0. 0. 0. 1.]
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[0. 0. 0. 0. 1.]
2022-02-04
[0. 0. 0. 0. 1.]
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[0. 0. 0. 0. 1.]
[0. 0. 0. 0. 1.]
[1. 0. 0. 0. 0.]
[0. 0. 0. 0. 1.]
[1. 0. 0. 0. 0.]
[0. 0. 0. 0. 1.]
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[1.

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:43: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior.  In a future version these will be considered non-comparable.Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.


   symbol        date       price
0    ABBV  2022-03-30  160.865295
1     AEP  2022-03-30   97.873009
2     AIZ  2022-03-30  180.737549
3    ALLE  2022-03-30  112.891090
4    AMAT  2022-03-30  135.123199
..    ...         ...         ...
40    UNH  2022-03-31  508.157806
41    URI  2022-03-31  355.209991
42      V  2022-03-31  220.955887
43   VRSK  2022-03-31  214.218460
44    XOM  2022-03-31   80.965904

[90 rows x 3 columns]
     0    1    2    3    4    5    6    7    8    9   ...   35   36   37   38  \
0   0.0  0.8  0.6  0.2  0.8  0.2  0.4  0.4  0.2  0.2  ...  0.6  0.2  0.4  0.0   
1   0.6  0.2  0.2  0.0  0.0  0.2  0.2  0.4  0.4  0.2  ...  0.2  0.8  0.8  0.8   
2   0.4  0.8  0.8  0.2  0.8  0.2  0.4  0.6  0.4  0.2  ...  0.0  0.0  0.8  0.6   
3   0.0  0.4  0.0  0.2  0.6  0.4  0.2  0.4  0.8  0.4  ...  0.4  0.0  0.6  0.6   
4   0.6  0.0  0.4  0.6  0.2  0.0  0.8  0.6  0.0  0.4  ...  0.4  0.8  0.6  0.0   
5   0.4  0.6  0.2  0.2  0.0  0.2  0.2  0.2  0.2  0.6  ...  0.4  0.0  0.0  0.8   
6 

In [ ]:
d=t2['date']
name=t2.columns[:-1]
# print(np.split(name.values,len(name)))
# print(d.values)
RPS['date']=d.values
RPS=RPS.set_index('date')
RPS.columns=assets
RPS

ABBV  AEP  AIZ  ALLE  AMAT  AMP  AMZN  AVB  AVY  AXP  ...  PRU  \
date                                                              ...        
2022-01-04   0.0  0.8  0.6   0.2   0.8  0.2   0.4  0.4  0.2  0.2  ...  0.6   
2022-01-05   0.6  0.2  0.2   0.0   0.0  0.2   0.2  0.4  0.4  0.2  ...  0.2   
2022-01-06   0.4  0.8  0.8   0.2   0.8  0.2   0.4  0.6  0.4  0.2  ...  0.0   
2022-01-07   0.0  0.4  0.0   0.2   0.6  0.4   0.2  0.4  0.8  0.4  ...  0.4   
2022-01-10   0.6  0.0  0.4   0.6   0.2  0.0   0.8  0.6  0.0  0.4  ...  0.4   
2022-01-11   0.4  0.6  0.2   0.2   0.0  0.2   0.2  0.2  0.2  0.6  ...  0.4   
2022-01-12   0.8  0.8  0.2   0.2   0.6  0.2   0.0  0.2  0.4  0.4  ...  0.0   
2022-01-13   0.0  0.6  0.4   0.2   0.0  0.2   0.6  0.4  0.6  0.8  ...  0.0   
2022-01-14   0.0  0.6  0.4   0.6   0.8  0.8   0.2  0.2  0.2  0.4  ...  0.4   
2022-01-18   0.6  0.6  0.4   0.4   0.8  0.8   0.0  0.6  0.4  0.8  ...  0.8   
2022-01-19   0.6  0.6  0.2   0.0   0.8  0.4   0.0  0.4  0.6  0.2  ...  0.4   
2022-01-20   0.2  0.8  0.4   0.8   0.6  0.8   0.0  0.2  0.4  0.4  ...  0.6   
2022-01-21   0.6  0.0  0.6   0.8   0.0  0.4   0.6  0.8  0.6  0.6  ...  0.6   
2022-01-24   0.0  0.6  0.6   0.2   0.8  0.4   0.0  0.0  0.6  0.0  ...  0.0   
2022-01-25   0.0  0.6  0.8   0.4   0.0  0.2   0.4  0.4  0.4  0.0  ...  0.0   
2022-01-26   0.0  0.6  0.8   0.4   0.8  0.0   0.6  0.6  0.6  0.8  ...  0.6   
2022-01-27   0.4  0.2  0.4   0.0   0.4  0.8   0.8  0.2  0.4  0.0  ...  0.8   
2022-01-28   0.8  0.2  0.2   0.4   0.0  0.2   0.8  0.6  0.0  0.2  ...  0.4   
2022-01-31   0.6  0.0  0.2   0.0   0.4  0.2   0.6  0.6  0.4  0.0  ...  0.0   
2022-02-01   0.4  0.6  0.4   0.2   0.2  0.2   0.2  0.0  0.8  0.6  ...  0.4   
2022-02-02   0.0  0.8  0.6   0.0   0.6  0.6   0.0  0.2  0.8  0.2  ...  0.4   
2022-02-03   0.2  0.2  0.6   0.8   0.4  0.2   0.8  0.6  0.0  0.2  ...  0.0   
2022-02-04   0.0  0.6  0.4   0.6   0.2  0.0   0.4  0.8  0.0  0.0  ...  0.2   
2022-02-07   0.6  0.2  0.6   0.4   0.2  0.4   0.8  0.8  0.6  0.0  ...  0.2   
2022-02-08   0.8  0.2  0.8   0.8   0.0  0.4   0.0  0.0  0.6  0.4  ...  0.8   
2022-02-09   0.0  0.2  0.6   0.0   0.8  0.0   0.4  0.8  0.6  0.0  ...  0.0   
2022-02-10   0.2  0.8  0.0   0.4   0.8  0.8   0.0  0.2  0.2  0.6  ...  0.4   
2022-02-11   0.0  0.0  0.2   0.4   0.4  0.6   0.8  0.6  0.2  0.0  ...  0.8   
2022-02-14   0.4  0.0  0.0   0.0   0.0  0.0   0.2  0.6  0.6  0.0  ...  0.2   
2022-02-15   0.0  0.2  0.0   0.0   0.0  0.0   0.8  0.6  0.4  0.4  ...  0.4   
2022-02-16   0.2  0.8  0.2   0.6   0.6  0.8   0.2  0.4  0.6  0.4  ...  0.8   
2022-02-17   0.6  0.6  0.4   0.4   0.8  0.0   0.0  0.4  0.2  0.4  ...  0.2   
2022-02-18   0.0  0.8  0.2   0.4   0.8  0.4   0.0  0.0  0.2  0.6  ...  0.4   
2022-02-22   0.0  0.4  0.2   0.0   0.4  0.4   0.0  0.2  0.2  0.4  ...  0.4   
2022-02-23   0.8  0.6  0.4   0.6   0.0  0.6   0.8  0.4  0.2  0.6  ...  0.8   
2022-02-24   0.4  0.6  0.2   0.6   0.6  0.0   0.0  0.2  0.6  0.4  ...  0.2   
2022-02-25   0.6  0.8  0.0   0.4   0.6  0.4   0.6  0.8  0.0  0.2  ...  0.4   
2022-02-28   0.2  0.6  0.6   0.8   0.6  0.8   0.4  0.4  0.0  0.8  ...  0.8   
2022-03-01   0.6  0.2  0.4   0.6   0.2  0.0   0.2  0.2  0.6  0.6  ...  0.0   
2022-03-02   0.2  0.8  0.0   0.6   0.8  0.4   0.0  0.0  0.2  0.4  ...  0.4   
2022-03-03   0.4  0.0  0.4   0.4   0.8  0.8   0.4  0.2  0.2  0.8  ...  0.6   
2022-03-04   0.2  0.0  0.0   0.4   0.6  0.8   0.0  0.2  0.0  0.8  ...  0.6   
2022-03-07   0.6  0.6  0.4   0.0   0.0  0.4   0.4  0.6  0.6  0.2  ...  0.0   
2022-03-08   0.6  0.8  0.4   0.6   0.2  0.0   0.4  0.4  0.8  0.0  ...  0.2   
2022-03-09   0.2  0.2  0.2   0.0   0.8  0.4   0.8  0.4  0.2  0.2  ...  0.4   
2022-03-10   0.0  0.2  0.0   0.2   0.4  0.2   0.4  0.4  0.6  0.4  ...  0.0   
2022-03-11   0.0  0.6  0.4   0.4   0.8  0.4   0.0  0.6  0.8  0.0  ...  0.0   
2022-03-14   0.2  0.6  0.4   0.6   0.0  0.2   0.8  0.8  0.0  0.4  ...  0.8   
2022-03-15   0.6  0.8  0.6   0.4   0.0  0.0   0.6  0.6  0.4  0.4  ...  0.2   
2022-03-16   0.2  0.0  0.4   0.4  

In [ ]:
RPS.mean(axis=1).mean()

0.39037037037037037

In [ ]:
#save results
RPS.to_excel('Method_3-SES_in_perc_returns-POINT_FORECAST.xlsx')