####Libraries
***

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import csv
from scipy.stats import norm
import statsmodels.api as sm
from patsy import dmatrices #a Python library for describing statistical models and building Design Matrices using R-like formulas.
import matplotlib.pyplot as plt
%matplotlib inline
from collections import Counter
from collections import defaultdict

In [2]:
!pip install yfinance --upgrade --no-cache-dir
import yfinance as yf
from pandas_datareader import data as pdr
yf.pdr_override()

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 62 kB 38.7 MB/s 
  Attempting uninstall: requests
    Found existing installation: requests 2.23.0
    Uninstalling requests-2.23.0:
      Successfully uninstalled requests-2.23.0


####Load Dataset
***

In [3]:
#φτιάχνω τη λίστα με τα assets μου -> 50 μετοχές 
#διόρθωση : θα βγάλω τυχαία άλλες 4 μετοχές μαζί με την OGN επειδή δεν έχει το ίδιο μέγεθος με τις άλλες 
#βγάζω OGN ,WRK,HST,CE,ACN
assets= ["ABBV","AEP","AIZ","ALLE","AMAT","AMP","AMZN","AVB","AVY",   
  "AXP","BDX","BF-B","BMY","BR","CARR","CDW","CHTR","CNC",   
  "CNP","COP","CTAS","CZR","DG","DPZ","DRE","DXC","META","FTV",   
  "GOOG","GPC","HIG","JPM","KR","PG","PPL","PRU",   
  "PYPL","RE","ROL","ROST","UNH","URI","V","VRSK","XOM"]

In [4]:
#άρα πρέπει να κατεβάσουμε όλα τα adj close για όλες τις τιμές όλων των μετοχών και να κάνουμε απόλυτο ranking και σε 5 κλασεις (targets)
r=pd.DataFrame(index=pdr.get_data_yahoo(assets[0],'2021-01-01','2022-04-01')['Adj Close'].index)

[*********************100%***********************]  1 of 1 completed


In [5]:
#παίρνω τιμές για ένα χρόνο και 3 μήνες
for i in assets:
  # print('i metoxi me onoma:',i,'exei megethos',pdr.get_data_yahoo(i,'2021-01-01','2022-04-01')['Adj Close'].count())
  temp= pdr.get_data_yahoo(i,'2021-01-01','2022-04-01')['Adj Close']
  temp=temp.dropna()
  r[i]=temp.values

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%********

In [6]:
#φτιάχνω ένα αντίγραφο με τις τιμές για να το έχω 
rd=pd.DataFrame(r)
rd

ABBV        AEP         AIZ        ALLE  \
Date                                                                       
2021-01-04 00:00:00-05:00   96.813477  76.819252  128.242004  111.874290   
2021-01-05 00:00:00-05:00   97.814575  76.715622  128.280823  112.089287   
2021-01-06 00:00:00-05:00   96.969620  77.327995  133.911011  114.639877   
2021-01-07 00:00:00-05:00   98.007446  75.264786  135.260315  117.659546   
2021-01-08 00:00:00-05:00   98.521790  74.595879  134.551682  117.249107   
...                               ...        ...         ...         ...   
2022-03-25 00:00:00-04:00  156.891495  95.333153  183.029373  111.363403   
2022-03-28 00:00:00-04:00  157.513885  96.091171  182.225754  112.533562   
2022-03-29 00:00:00-04:00  157.718109  97.154373  179.884308  114.090469   
2022-03-30 00:00:00-04:00  159.244919  97.873009  180.737549  112.404640   
2022-03-31 00:00:00-04:00  157.650040  98.217560  180.400223  108.864418   

                                 AMAT         AMP        AMZN         AVB  \
Date                                                                        
2021-01-04 00:00:00-05:00   85.672470  182.556000  159.331497  147.581146   
2021-01-05 00:00:00-05:00   88.364822  181.488480  160.925507  147.154129   
2021-01-06 00:00:00-05:00   89.577881  191.901703  156.919006  151.101746   
2021-01-07 00:00:00-05:00   93.256462  194.221146  158.108002  149.042511   
2021-01-08 00:00:00-05:00   94.242668  195.599213  159.134995  150.352066   
...                               ...         ...         ...         ...   
2022-03-25 00:00:00-04:00  136.376923  311.729828  164.773499  241.656281   
2022-03-28 00:00:00-04:00  136.973938  308.232391  168.990494  244.344177   
2022-03-29 00:00:00-04:00  140.735077  309.342041  169.315002  252.427414   
2022-03-30 00:00:00-04:00  135.123199  307.737000  166.300995  247.785416   
2022-03-31 00:00:00-04:00  131.143143  297.591339  162.997498  244.264587   

                                  AVY         AXP  ...         PRU  \
Date                                               ...               
2021-01-04 00:00:00-05:00  148.152328  115.185814  ...   70.458298   
2021-01-05 00:00:00-05:00  148.474228  115.800583  ...   71.140762   
2021-01-06 00:00:00-05:00  154.150650  120.084427  ...   75.355339   
2021-01-07 00:00:00-05:00  158.959000  119.134567  ...   75.023338   
2021-01-08 00:00:00-05:00  152.882690  119.252068  ...   74.423897   
...                               ...         ...  ...         ...   
2022-03-25 00:00:00-04:00  171.694946  188.315094  ...  118.004997   
2022-03-28 00:00:00-04:00  172.051941  187.741089  ...  117.223892   
2022-03-29 00:00:00-04:00  177.406876  188.968292  ...  118.004997   
2022-03-30 00:00:00-04:00  175.354156  187.800461  ...  117.458229   
2022-03-31 00:00:00-04:00  172.518021  185.068970  ...  115.378540   

                                 PYPL          RE        ROL        ROST  \
Date                                                                       
2021-01-04 00:00:00-05:00  231.919998  218.876434  37.469650  114.689148   
2021-01-05 00:00:00-05:00  234.910004  217.072525  38.086964  114.787094   
2021-01-06 00:00:00-05:00  226.830002  229.939713  38.714066  119.802986   
2021-01-07 00:00:00-05:00  235.039993  231.590088  39.360771  119.538467   
2021-01-08 00:00:00-05:00  242.460007  229.296829  39.978073  119.920540   
...                               ...         ...        ...         ...   
2022-03-25 00:00:00-04:00  113.760002  295.426666  33.621418   89.567093   
2022-03-28 00:00:00-04:00  116.169998  294.201538  34.228012   90.897385   
2022-03-29 00:00:00-04:00  121.180000  298.953888  34.953945   94.858521   
2022-03-30 00:00:00-04:00  118.489998  301.068237  35.242325   91.939796   
2022-03-31 00:00:00-04:00  115.650002  297.768280  34.854500   89.805351   

                                  UNH         URI           V        VRSK  \
Date                                                             

In [7]:
rd1= rd.pct_change().shift(-1)
rd1

ABBV       AEP       AIZ      ALLE      AMAT  \
Date                                                                          
2021-01-04 00:00:00-05:00  0.010340 -0.001349  0.000303  0.001922  0.031426   
2021-01-05 00:00:00-05:00 -0.008638  0.007982  0.043890  0.022755  0.013728   
2021-01-06 00:00:00-05:00  0.010703 -0.026681  0.010076  0.026340  0.041066   
2021-01-07 00:00:00-05:00  0.005248 -0.008887 -0.005239 -0.003488  0.010575   
2021-01-08 00:00:00-05:00  0.016314 -0.005052 -0.005772  0.002917  0.025115   
...                             ...       ...       ...       ...       ...   
2022-03-25 00:00:00-04:00  0.003967  0.007951 -0.004391  0.010508  0.004378   
2022-03-28 00:00:00-04:00  0.001297  0.011065 -0.012849  0.013835  0.027459   
2022-03-29 00:00:00-04:00  0.009681  0.007397  0.004743 -0.014776 -0.039875   
2022-03-30 00:00:00-04:00 -0.010015  0.003520 -0.001866 -0.031495 -0.029455   
2022-03-31 00:00:00-04:00       NaN       NaN       NaN       NaN       NaN   

                                AMP      AMZN       AVB       AVY       AXP  \
Date                                                                          
2021-01-04 00:00:00-05:00 -0.005848  0.010004 -0.002893  0.002173  0.005337   
2021-01-05 00:00:00-05:00  0.057377 -0.024897  0.026826  0.038232  0.036993   
2021-01-06 00:00:00-05:00  0.012087  0.007577 -0.013628  0.031193 -0.007910   
2021-01-07 00:00:00-05:00  0.007095  0.006496  0.008786 -0.038226  0.000986   
2021-01-08 00:00:00-05:00  0.000149 -0.021519 -0.006690  0.029282 -0.005912   
...                             ...       ...       ...       ...       ...   
2022-03-25 00:00:00-04:00 -0.011219  0.025593  0.011123  0.002079 -0.003048   
2022-03-28 00:00:00-04:00  0.003600  0.001920  0.033081  0.031124  0.006537   
2022-03-29 00:00:00-04:00 -0.005189 -0.017801 -0.018389 -0.011571 -0.006180   
2022-03-30 00:00:00-04:00 -0.032969 -0.019865 -0.014209 -0.016174 -0.014545   
2022-03-31 00:00:00-04:00       NaN       NaN       NaN       NaN       NaN   

                           ...       PRU      PYPL        RE       ROL  \
Date                       ...                                           
2021-01-04 00:00:00-05:00  ...  0.009686  0.012892 -0.008242  0.016475   
2021-01-05 00:00:00-05:00  ...  0.059243 -0.034396  0.059276  0.016465   
2021-01-06 00:00:00-05:00  ... -0.004406  0.036194  0.007177  0.016705   
2021-01-07 00:00:00-05:00  ... -0.007990  0.031569 -0.009902  0.015683   
2021-01-08 00:00:00-05:00  ...  0.000991 -0.020457 -0.007197  0.002696   
...                        ...       ...       ...       ...       ...   
2022-03-25 00:00:00-04:00  ... -0.006619  0.021185 -0.004147  0.018042   
2022-03-28 00:00:00-04:00  ...  0.006663  0.043126  0.016153  0.021209   
2022-03-29 00:00:00-04:00  ... -0.004633 -0.022198  0.007072  0.008250   
2022-03-30 00:00:00-04:00  ... -0.017706 -0.023968 -0.010961 -0.011005   
2022-03-31 00:00:00-04:00  ...       NaN       NaN       NaN       NaN   

                               ROST       UNH       URI         V      VRSK  \
Date                                                                          
2021-01-04 00:00:00-05:00  0.000854 -0.013448  0.025778 -0.014925 -0.004485   
2021-01-05 00:00:00-05:00  0.043697  0.041966  0.089060 -0.008811 -0.009457   
2021-01-06 00:00:00-05:00 -0.002208  0.016033  0.031690  0.005597  0.004549   
2021-01-07 00:00:00-05:00  0.003196 -0.004493 -0.017115  0.007670 -0.000348   
2021-01-08 00:00:00-05:00 -0.012581 -0.007265 -0.010379 -0.011882 -0.015082   
...                             ...       ...       ...       ...       ...   
2022-03-25 00:00:00-04:00  0.014852  0.000331 -0.000742  0.010713  0.017308   
2022-03-28 00:00:00-04:00  0.043578 -0.004813  0.004953  0.033293  0.015123   
2022-03-29 00:00:00-04:00 -0.030769  0.019756 -0.016457 -0.018280  0.010102   
2022-03-30 00:00:00-04:00 -0.023216 -0.020833 -0.011081 -0.009734 -0.010785   
2022-03-31 00:00:00-04:00       NaN       NaN       NaN       Na

In [8]:
#first: ranks assigned in order they appear in the array
rd2=rd1.rank(axis=1,method='first')
rd2=rd2.dropna()
rd2.astype(int)
jk=rd2.copy()
jk.astype(int)

ABBV  AEP  AIZ  ALLE  AMAT  AMP  AMZN  AVB  AVY  \
Date                                                                         
2021-01-04 00:00:00-05:00    34   14   15    21    41    9    33   12   22   
2021-01-05 00:00:00-05:00     8   14   37    25    20   40     3   28   31   
2021-01-06 00:00:00-05:00    25    2   23    36    44   28    20    3   40   
2021-01-07 00:00:00-05:00    28    8   13    17    37   31    30   34    1   
2021-01-08 00:00:00-05:00    39   23   22    29    42   26     5   20   43   
...                         ...  ...  ...   ...   ...  ...   ...  ...  ...   
2022-03-24 00:00:00-04:00    21   16   27     4     3   28    22   40   45   
2022-03-25 00:00:00-04:00    22   27    9    31    23    4    45   36   19   
2022-03-28 00:00:00-04:00     7   20    2    24    36   11     9   41   39   
2022-03-29 00:00:00-04:00    41   38   33    11     2   21     9    6   14   
2022-03-30 00:00:00-04:00    33   44   40     4     6    3    16   23   20   

                           AXP  ...  PRU  PYPL  RE  ROL  ROST  UNH  URI   V  \
Date                            ...                                           
2021-01-04 00:00:00-05:00   25  ...   32    36   6   38    17    5   40   3   
2021-01-05 00:00:00-05:00   29  ...   41     1  42   21    36   35   44   7   
2021-01-06 00:00:00-05:00    8  ...    9    43  19   30    11   29   41  18   
2021-01-07 00:00:00-05:00   22  ...   11    45   6   42    26   14    3  33   
2021-01-08 00:00:00-05:00   21  ...   27     7  16   28    10   15   13  11   
...                        ...  ...  ...   ...  ..  ...   ...  ...  ...  ..   
2022-03-24 00:00:00-04:00   24  ...   38     2  37   25     5    8   36  19   
2022-03-25 00:00:00-04:00   13  ...    8    42  11   41    38   18   16  32   
2022-03-28 00:00:00-04:00   14  ...   15    43  26   33    44    5   12  42   
2022-03-29 00:00:00-04:00   20  ...   22     5  37   39     3   45   10   7   
2022-03-30 00:00:00-04:00   22  ...   19     9  29   28    11   15   27  34   

                           VRSK  XOM  
Date                                  
2021-01-04 00:00:00-05:00    11   44  
2021-01-05 00:00:00-05:00     6   26  
2021-01-06 00:00:00-05:00    16   21  
2021-01-07 00:00:00-05:00    19   38  
2021-01-08 00:00:00-05:00     9   44  
...                         ...  ...  
2022-03-24 00:00:00-04:00     7   42  
2022-03-25 00:00:00-04:00    40    2  
2022-03-28 00:00:00-04:00    25    4  
2022-03-29 00:00:00-04:00    42   44  
2022-03-30 00:00:00-04:00    31   24  

[313 rows x 45 columns]

In [9]:
def rank_data(df1):
  for i in range(len(df1.index)):
    d=df1.loc[df1.index[i]]  #της κάθε μέρας d[1] δίνει μόνο τις τιμές 
    #print(d)
    d=d.sort_values()
    d[0:9]=1
    d[9:18]=2
    d[18:27]=3
    d[27:36]=4
    d[36:45]=5
    df1.loc[df1.index[i]]=d
    #print(df1.loc[df1.index[i]])
    #print(d)
  df1=df1.astype(int)
  return df1
r5=rd2.copy()
rd3=rank_data(r5)
rd3

ABBV  AEP  AIZ  ALLE  AMAT  AMP  AMZN  AVB  AVY  \
Date                                                                         
2021-01-04 00:00:00-05:00     4    2    2     3     5    1     4    2    3   
2021-01-05 00:00:00-05:00     1    2    5     3     3    5     1    4    4   
2021-01-06 00:00:00-05:00     3    1    3     4     5    4     3    1    5   
2021-01-07 00:00:00-05:00     4    1    2     2     5    4     4    4    1   
2021-01-08 00:00:00-05:00     5    3    3     4     5    3     1    3    5   
...                         ...  ...  ...   ...   ...  ...   ...  ...  ...   
2022-03-24 00:00:00-04:00     3    2    3     1     1    4     3    5    5   
2022-03-25 00:00:00-04:00     3    3    1     4     3    1     5    4    3   
2022-03-28 00:00:00-04:00     1    3    1     3     4    2     1    5    5   
2022-03-29 00:00:00-04:00     5    5    4     2     1    3     1    1    2   
2022-03-30 00:00:00-04:00     4    5    5     1     1    1     2    3    3   

                           AXP  ...  PRU  PYPL  RE  ROL  ROST  UNH  URI  V  \
Date                            ...                                          
2021-01-04 00:00:00-05:00    3  ...    4     4   1    5     2    1    5  1   
2021-01-05 00:00:00-05:00    4  ...    5     1   5    3     4    4    5  1   
2021-01-06 00:00:00-05:00    1  ...    1     5   3    4     2    4    5  2   
2021-01-07 00:00:00-05:00    3  ...    2     5   1    5     3    2    1  4   
2021-01-08 00:00:00-05:00    3  ...    3     1   2    4     2    2    2  2   
...                        ...  ...  ...   ...  ..  ...   ...  ...  ... ..   
2022-03-24 00:00:00-04:00    3  ...    5     1   5    3     1    1    4  3   
2022-03-25 00:00:00-04:00    2  ...    1     5   2    5     5    2    2  4   
2022-03-28 00:00:00-04:00    2  ...    2     5   3    4     5    1    2  5   
2022-03-29 00:00:00-04:00    3  ...    3     1   5    5     1    5    2  1   
2022-03-30 00:00:00-04:00    3  ...    3     1   4    4     2    2    3  4   

                           VRSK  XOM  
Date                                  
2021-01-04 00:00:00-05:00     2    5  
2021-01-05 00:00:00-05:00     1    3  
2021-01-06 00:00:00-05:00     2    3  
2021-01-07 00:00:00-05:00     3    5  
2021-01-08 00:00:00-05:00     1    5  
...                         ...  ...  
2022-03-24 00:00:00-04:00     1    5  
2022-03-25 00:00:00-04:00     5    1  
2022-03-28 00:00:00-04:00     3    1  
2022-03-29 00:00:00-04:00     5    5  
2022-03-30 00:00:00-04:00     4    3  

[313 rows x 45 columns]

####Συνάρτηση για τον υπολογισμό του RPS


In [10]:
def RPS_calculation(hist_data, submission, asset_no=44):
    # print('check')
    if hist_data.shape[0]<=asset_no:
        return np.nan    
    # print('check')
    asset_id = pd.unique(hist_data.symbol)
    
    for i in range(len(pd.unique(hist_data.date))):
        if len(hist_data[hist_data.date == pd.unique(hist_data.date)[i]])<len(asset_id):
            for asset in [x for x in asset_id if x not in hist_data[hist_data.date == pd.unique(hist_data.date)[i]].symbol.values]:
                right_price = hist_data[hist_data.symbol==asset].sort_values(by='date')
                right_price = right_price[right_price.date <= pd.unique(hist_data.date)[i]]
                right_price = right_price.price.iloc[-1]
                hist_data = hist_data.append({'date' : pd.unique(hist_data.date)[i],
                                               'symbol' : asset,
                                               'price' : right_price}, ignore_index=True)

    #Compute percentage returns
    asset_id = sorted(asset_id) 

    #Compute percentage returns
    returns = pd.DataFrame(columns = ["ID", "Return"])
    
    min_date = min(hist_data.date)
    # max_date = max(hist_data.date)
    max_date = np.max(hist_data.date)
    
    for i in range(0,len(asset_id)):
        temp = hist_data.loc[hist_data.symbol==asset_id[i]]
        
        open_price = float(temp.loc[temp.date==min_date].price)
        close_price = float(temp.loc[temp.date==max_date].price)
        
        returns = returns.append({'ID': temp.symbol.iloc[0], 
                                'Return': (close_price - open_price)/open_price}, ignore_index=True)

    #Define the relevant position of each asset
    ranking = pd.DataFrame(columns=["ID", "Position", "Return"])
    ranking.ID = list(asset_id)
    ranking.Return = returns.Return
    ranking.Position = ranking.Return.rank(method = 'min')

    #Handle Ties
    Series_per_position = pd.DataFrame(columns=["Position","Series", "Rank", "Rank1", "Rank2","Rank3", "Rank4", "Rank5"])
    Series_per_position.Position = list(pd.unique(ranking.Position.sort_values(ascending=True)))
    temp = ranking.Position.value_counts()
    temp = pd.DataFrame(zip(temp.index, temp), columns = ["Rank", "Occurencies"])
    temp = temp.sort_values(by = ["Rank"],ascending=True)
    Series_per_position.Series = list(temp.Occurencies)
    Series_per_position

    total_ranks = Series_per_position.Position.values[-1]
    for i in range(0,Series_per_position.shape[0]):
    
        start_p = Series_per_position.Position[i]
        end_p = Series_per_position.Position[i] + Series_per_position.Series[i]
        temp = pd.DataFrame(columns = ["Position","Rank", "Rank1", "Rank2", "Rank3", "Rank4","Rank5"])
        temp.Position = list(range(int(start_p),int(end_p)))

        if(temp.loc[temp.Position.isin(list(range(1,int(0.2*total_ranks+1))))].empty==False):
            temp.loc[temp.Position.isin(list(range(1,int(0.2*total_ranks+1))))] = temp.loc[temp.Position.isin(list(range(1,int(0.2*total_ranks+1))))].assign(Rank=1)
            temp.loc[temp.Position.isin(list(range(1,int(0.2*total_ranks+1))))] = temp.loc[temp.Position.isin(list(range(1,int(0.2*total_ranks+1))))].assign(Rank1=1.0)

        elif(temp.loc[temp.Position.isin(list(range(int(0.2*total_ranks+1),int(0.4*total_ranks+1))))].empty==False):
            temp.loc[temp.Position.isin(list(range(int(0.2*total_ranks+1),int(0.4*total_ranks+1))))] = temp.loc[temp.Position.isin(list(range(int(0.2*total_ranks+1),int(0.4*total_ranks+1))))].assign(Rank=2)
            temp.loc[temp.Position.isin(list(range(int(0.2*total_ranks+1),int(0.4*total_ranks+1))))] = temp.loc[temp.Position.isin(list(range(int(0.2*total_ranks+1),int(0.4*total_ranks+1))))].assign(Rank2=1.0)

        elif(temp.loc[temp.Position.isin(list(range(int(0.4*total_ranks+1),int(0.6*total_ranks+1))))].empty==False):
            temp.loc[temp.Position.isin(list(range(int(0.4*total_ranks+1),int(0.6*total_ranks+1))))] = temp.loc[temp.Position.isin(list(range(int(0.4*total_ranks+1),int(0.6*total_ranks+1))))].assign(Rank=3)
            temp.loc[temp.Position.isin(list(range(int(0.4*total_ranks+1),int(0.6*total_ranks+1))))] = temp.loc[temp.Position.isin(list(range(int(0.4*total_ranks+1),int(0.6*total_ranks+1))))].assign(Rank3=1.0)

        elif(temp.loc[temp.Position.isin(list(range(int(0.6*total_ranks+1),int(0.8*total_ranks+1))))].empty==False):
            temp.loc[temp.Position.isin(list(range(int(0.6*total_ranks+1),int(0.8*total_ranks+1))))] = temp.loc[temp.Position.isin(list(range(int(0.6*total_ranks+1),int(0.8*total_ranks+1))))].assign(Rank=4)
            temp.loc[temp.Position.isin(list(range(int(0.6*total_ranks+1),int(0.8*total_ranks+1))))] = temp.loc[temp.Position.isin(list(range(int(0.6*total_ranks+1),int(0.8*total_ranks+1))))].assign(Rank4=1.0)

        elif(temp.loc[temp.Position.isin(list(range(int(0.8*total_ranks+1),int(total_ranks+1))))].empty==False):
            temp.loc[temp.Position.isin(list(range(int(0.8*total_ranks+1),int(total_ranks+1))))] = temp.loc[temp.Position.isin(list(range(int(0.8*total_ranks+1),int(total_ranks+1))))].assign(Rank=5)
            temp.loc[temp.Position.isin(list(range(int(0.8*total_ranks+1),int(total_ranks+1))))] = temp.loc[temp.Position.isin(list(range(int(0.8*total_ranks+1),int(total_ranks+1))))].assign(Rank5=1.0)
        temp = temp.fillna(0)
        Series_per_position.iloc[i,2:Series_per_position.shape[1]] = temp.mean(axis = 0).iloc[1:temp.shape[1]]

    Series_per_position = Series_per_position.drop('Series', axis = 1)
    ranking = pd.merge(ranking,Series_per_position, on = "Position")
    ranking = ranking[["ID", "Return", "Position", "Rank", "Rank1", "Rank2", "Rank3", "Rank4", "Rank5"]]
    ranking = ranking.sort_values(["Position"])
    print(ranking)
    #Evaluate submission
    rps_sub = []
    #for aid in list((pd.unique(ranking.ID))):
    for aid in asset_id:

        target = np.cumsum(ranking.loc[ranking.ID==aid].iloc[:,4:9].values).tolist()
        frc = np.cumsum(submission.loc[submission.ID==aid].iloc[:,1:6].values).tolist()
        rps_sub.append(np.mean([(a - b)**2 for a, b in zip(target, frc)]))
    submission["RPS"] = rps_sub
    
    output = {'RPS' : np.mean(rps_sub),
              'details' : submission}
    
    return(output)

####'Εχω τα data έτοιμα και τώρα θα υπολογίσω με πιθανότητες την καινούρια μέθοδο σύμφωνα κάθε φορά με το insample μου.

In [36]:
#Αυτή η συνάρτηση παίρνει τα data και κάνει τη dummy μέτρηση για το διάστημα ενός χρόνου (όσο οριστεί στην ουσία το insample) για μια μετοχή
n=dict() 
def dummy(st,i):
  insample=st.iloc[:-i]
  print('Η ημέρα που πραγματοποιείται η πρόβλεψη είναι:',str(st.iloc[-i:-i+1])[4:15])
  print('Tο insample φτάνει μέχρι και την ημέρα:',str(insample.tail(1))[4:15])
  
  count=defaultdict(int)
  for word in insample.values:
    count[word]+=1
  print(word,count)
  count=sorted(count.items()) #list Η πρώτη τιμή είναι η κλάση και η δεύτερη πόσες φορές είδα τον αριθμό.
  temp=[]
  for k in range(5):
    flag=True
    for l in count:
      if(l[0]==k+1):
        temp.append(l[1]/len(insample))
        flag=False
        break
    if(flag):
      temp.append(0)
  # print(temp,count)
  data={
      'prediction':temp
  }
  forecast=pd.DataFrame(data)
  return forecast
# #για όλες τις μετοχές υπολογίζεται το counter τους
dummy(rd3['ABBV'],60)
# for k in rd3.columns:
#   n[k]=dummy(rd3[k],61)
# n['ABBV']

Η ημέρα που πραγματοποιείται η πρόβλεψη είναι: 
2022-01-04
Tο insample φτάνει μέχρι και την ημέρα: 
2022-01-03
2 defaultdict(<class 'int'>, {4: 61, 1: 42, 3: 58, 5: 47, 2: 45})


prediction
0    0.166008
1    0.177866
2    0.229249
3    0.241107
4    0.185771

In [ ]:
def pred(st):
  pred=dict()
  for j in st:
    temp=[]
    date=[]
    for i in range(60,1,-1):
      # print(i)
      date.append(rd3[j].iloc[-i:-i+1].index.date[0])
      print('imera provlepsis',rd3[j].iloc[-i:-i+1].index.date[0])
      temp.append(dummy(rd3[j],i)['prediction'].values)
      # pred[rd3[j].name]=temp
    #for the last day 
    date.append(rd3[j].iloc[-1:].index.date[0])
    temp.append(dummy(rd3[j],1)['prediction'].values)
    pred[rd3[j].name]=temp
  # print(date)
  pred['date']=date
  pred_final=pd.DataFrame.from_dict(pred)
  # pred_final['Date']=date
  # pred_final.set_index('Date')
  # print(pred_final)
  return pred_final
t=pred(rd3)

Η έξοδος ροής περικόπηκε στις τελευταίες 5000 γραμμές.
Name: GOOG, dtype: int64
3 defaultdict(<class 'int'>, {4: 61, 2: 48, 5: 54, 1: 41, 3: 65})
imera provlepsis 2022-01-28
TO insample ftanei mexri: Date
2022-01-27    5
Name: GOOG, dtype: int64
5 defaultdict(<class 'int'>, {4: 61, 2: 48, 5: 55, 1: 41, 3: 65})
imera provlepsis 2022-01-31
TO insample ftanei mexri: Date
2022-01-28    4
Name: GOOG, dtype: int64
4 defaultdict(<class 'int'>, {4: 62, 2: 48, 5: 55, 1: 41, 3: 65})
imera provlepsis 2022-02-01
TO insample ftanei mexri: Date
2022-01-31    4
Name: GOOG, dtype: int64
4 defaultdict(<class 'int'>, {4: 63, 2: 48, 5: 55, 1: 41, 3: 65})
imera provlepsis 2022-02-02
TO insample ftanei mexri: Date
2022-02-01    5
Name: GOOG, dtype: int64
5 defaultdict(<class 'int'>, {4: 63, 2: 48, 5: 56, 1: 41, 3: 65})
imera provlepsis 2022-02-03
TO insample ftanei mexri: Date
2022-02-02    1
Name: GOOG, dtype: int64
1 defaultdict(<class 'int'>, {4: 63, 2: 48, 5: 56, 1: 42, 3: 65})
imera provlepsis 2022-02

In [ ]:
t

ABBV  \
0   [0.16600790513833993, 0.17786561264822134, 0.2...   
1   [0.16535433070866143, 0.17716535433070865, 0.2...   
2   [0.16470588235294117, 0.1803921568627451, 0.22...   
3   [0.1640625, 0.1796875, 0.23046875, 0.23828125,...   
4   [0.16342412451361868, 0.17898832684824903, 0.2...   
5   [0.16279069767441862, 0.1821705426356589, 0.22...   
6   [0.16216216216216217, 0.18146718146718147, 0.2...   
7   [0.16538461538461538, 0.18076923076923077, 0.2...   
8   [0.16475095785440613, 0.18007662835249041, 0.2...   
9   [0.16412213740458015, 0.17938931297709923, 0.2...   
10  [0.1634980988593156, 0.18250950570342206, 0.22...   
11  [0.16287878787878787, 0.1856060606060606, 0.22...   
12  [0.16226415094339622, 0.18490566037735848, 0.2...   
13  [0.16165413533834586, 0.18796992481203006, 0.2...   
14  [0.16104868913857678, 0.18726591760299627, 0.2...   
15  [0.16044776119402984, 0.1865671641791045, 0.22...   
16  [0.15985130111524162, 0.18587360594795538, 0.2...   
17  [0.15925925925925927, 0.18518518518518517, 0.2...   
18  [0.16236162361623616, 0.18450184501845018, 0.2...   
19  [0.16176470588235295, 0.1875, 0.22426470588235...   
20  [0.16117216117216118, 0.18681318681318682, 0.2...   
21  [0.16058394160583941, 0.18613138686131386, 0.2...   
22  [0.16, 0.18545454545454546, 0.2254545454545454...   
23  [0.15942028985507245, 0.18478260869565216, 0.2...   
24  [0.1588447653429603, 0.18772563176895307, 0.22...   
25  [0.1618705035971223, 0.18705035971223022, 0.22...   
26  [0.16129032258064516, 0.1863799283154122, 0.22...   
27  [0.16071428571428573, 0.18571428571428572, 0.2...   
28  [0.1601423487544484, 0.18505338078291814, 0.22...   
29  [0.1595744680851064, 0.18439716312056736, 0.22...   
30  [0.15901060070671377, 0.18374558303886926, 0.2...   
31  [0.15845070422535212, 0.18309859154929578, 0.2...   
32  [0.15789473684210525, 0.18596491228070175, 0.2...   
33  [0.15734265734265734, 0.1853146853146853, 0.22...   
34  [0.156794425087108, 0.18466898954703834, 0.219...   
35  [0.1597222222222222, 0.1840277777777778, 0.218...   
36  [0.15916955017301038, 0.18339100346020762, 0.2...   
37  [0.15862068965517243, 0.18620689655172415, 0.2...   
38  [0.15807560137457044, 0.18556701030927836, 0.2...   
39  [0.15753424657534246, 0.18835616438356165, 0.2...   
40  [0.15699658703071673, 0.18771331058020477, 0.2...   
41  [0.1564625850340136, 0.1870748299319728, 0.221...   
42  [0.15593220338983052, 0.1864406779661017, 0.22...   
43  [0.1554054054054054, 0.1891891891891892, 0.219...   
44  [0.15488215488215487, 0.1919191919191919, 0.21...   
45  [0.15436241610738255, 0.1912751677852349, 0.21...   
46  [0.15384615384615385, 0.19063545150501673, 0.2...   
47  [0.15333333333333332, 0.19, 0.2166666666666666...   
48  [0.15282392026578073, 0.1893687707641196, 0.21...   
49  [0.152317880794702, 0.19205298013245034, 0.215...   
50  [0.15181518151815182, 0.19141914191419143, 0.2...   
51  [0.1513157894736842, 0.19078947368421054, 0.21...   
52  [0.15081967213114755, 0.1901639344262295, 0.21...   
53  [0.1503267973856209, 0.19281045751633988, 0.21...   
54  [0.1498371335504886, 0.19218241042345277, 0.21...   
55  [0.14935064935064934, 0.19155844155844157, 0.2...   
56  [0.1488673139158576, 0.19093851132686085, 0.22...   
57  [0.14838709677419354, 0.19032258064516128, 0.2...   
58  [0.15112540192926044, 0.18971061093247588, 0.2...   
59  [0.15064102564102563, 0.1891025641025641, 0.22...   

                                                  AEP  \
0   [0.1976284584980237, 0.21739130434782608, 0.20...   
1   [0.1968503937007874, 0.21653543307086615, 0.20...   
2   [0.19607843137254902, 0.2196078431372549, 0.20...   
3   [0.1953125, 0.21875, 0.203125, 0.2265625, 0.15...   
4   [0.19455252918287938, 0.2178988326848249, 0.20...   
5   [0.19767441860465115, 0.21705426356589147, 0.2...   
6   [0.1969111969111969, 0.21621621621621623, 0.20...   
7   [0.19615384615384615, 0.2153846153846154, 0.20...   
8   [0.19540229885057472, 0.21455938697318008, 0.2...   
9

In [ ]:
t2=pd.DataFrame.from_dict(t)
t2.set_index('date')

ABBV  \
date                                                            
2022-01-04  [0.16600790513833993, 0.17786561264822134, 0.2...   
2022-01-05  [0.16535433070866143, 0.17716535433070865, 0.2...   
2022-01-06  [0.16470588235294117, 0.1803921568627451, 0.22...   
2022-01-07  [0.1640625, 0.1796875, 0.23046875, 0.23828125,...   
2022-01-10  [0.16342412451361868, 0.17898832684824903, 0.2...   
2022-01-11  [0.16279069767441862, 0.1821705426356589, 0.22...   
2022-01-12  [0.16216216216216217, 0.18146718146718147, 0.2...   
2022-01-13  [0.16538461538461538, 0.18076923076923077, 0.2...   
2022-01-14  [0.16475095785440613, 0.18007662835249041, 0.2...   
2022-01-18  [0.16412213740458015, 0.17938931297709923, 0.2...   
2022-01-19  [0.1634980988593156, 0.18250950570342206, 0.22...   
2022-01-20  [0.16287878787878787, 0.1856060606060606, 0.22...   
2022-01-21  [0.16226415094339622, 0.18490566037735848, 0.2...   
2022-01-24  [0.16165413533834586, 0.18796992481203006, 0.2...   
2022-01-25  [0.16104868913857678, 0.18726591760299627, 0.2...   
2022-01-26  [0.16044776119402984, 0.1865671641791045, 0.22...   
2022-01-27  [0.15985130111524162, 0.18587360594795538, 0.2...   
2022-01-28  [0.15925925925925927, 0.18518518518518517, 0.2...   
2022-01-31  [0.16236162361623616, 0.18450184501845018, 0.2...   
2022-02-01  [0.16176470588235295, 0.1875, 0.22426470588235...   
2022-02-02  [0.16117216117216118, 0.18681318681318682, 0.2...   
2022-02-03  [0.16058394160583941, 0.18613138686131386, 0.2...   
2022-02-04  [0.16, 0.18545454545454546, 0.2254545454545454...   
2022-02-07  [0.15942028985507245, 0.18478260869565216, 0.2...   
2022-02-08  [0.1588447653429603, 0.18772563176895307, 0.22...   
2022-02-09  [0.1618705035971223, 0.18705035971223022, 0.22...   
2022-02-10  [0.16129032258064516, 0.1863799283154122, 0.22...   
2022-02-11  [0.16071428571428573, 0.18571428571428572, 0.2...   
2022-02-14  [0.1601423487544484, 0.18505338078291814, 0.22...   
2022-02-15  [0.1595744680851064, 0.18439716312056736, 0.22...   
2022-02-16  [0.15901060070671377, 0.18374558303886926, 0.2...   
2022-02-17  [0.15845070422535212, 0.18309859154929578, 0.2...   
2022-02-18  [0.15789473684210525, 0.18596491228070175, 0.2...   
2022-02-22  [0.15734265734265734, 0.1853146853146853, 0.22...   
2022-02-23  [0.156794425087108, 0.18466898954703834, 0.219...   
2022-02-24  [0.1597222222222222, 0.1840277777777778, 0.218...   
2022-02-25  [0.15916955017301038, 0.18339100346020762, 0.2...   
2022-02-28  [0.15862068965517243, 0.18620689655172415, 0.2...   
2022-03-01  [0.15807560137457044, 0.18556701030927836, 0.2...   
2022-03-02  [0.15753424657534246, 0.18835616438356165, 0.2...   
2022-03-03  [0.15699658703071673, 0.18771331058020477, 0.2...   
2022-03-04  [0.1564625850340136, 0.1870748299319728, 0.221...   
2022-03-07  [0.15593220338983052, 0.1864406779661017, 0.22...   
2022-03-08  [0.1554054054054054, 0.1891891891891892, 0.219...   
2022-03-09  [0.15488215488215487, 0.1919191919191919, 0.21...   
2022-03-10  [0.15436241610738255, 0.1912751677852349, 0.21...   
2022-03-11  [0.15384615384615385, 0.19063545150501673, 0.2...   
2022-03-14  [0.15333333333333332, 0.19, 0.2166666666666666...   
2022-03-15  [0.15282392026578073, 0.1893687707641196, 0.21...   
2022-03-16  [0.152317880794702, 0.19205298013245034, 0.215...   
2022-03-17  [0.15181518151815182, 0.19141914191419143, 0.2...   
2022-03-18  [0.1513157894736842, 0.19078947368421054, 0.21...   
2022-03-21  [0.15081967213114755, 0.1901639344262295, 0.21...   
2022-03-22  [0.1503267973856209, 0.19281045751633988, 0.21...   
2022-03-23  [0.1498371335504886, 0.19218241042345277, 0.21...   
2022-03-24  [0.14935064935064934, 0.19155844155844157, 0.2...   
2022-03-25  [0.1488673139158576, 0.19093851132686085, 0.22...   
2022-03-28  [0.14838709677419354, 0.19032258064516128, 0.2...   
2022-03-29  [0.15112540192926044, 0.18971061093247588, 0.2...   
2022-03-30  [0.15064102564102563, 0.1891025641025641, 0.22...   

                          

In [ ]:
def create_historical(prob):
  prob=prob.rename_axis("symbol", axis="columns")
  prob=prob.T
  prob['date']=prob.columns.date[0]
  prob.columns = ['price', 'date']
  prob=prob.reset_index()
  prob=prob[['symbol','date','price']]
  return prob

In [ ]:
RPS=pd.DataFrame()

for k in t2.index: #for everyday of a stock->index
  prob=pd.DataFrame()
  prob1=pd.DataFrame()
  predic=pd.DataFrame()
  if(t2['date'][k]!=t2['date'].tail(1).values): #if it's not for the last day 
    print(t2['date'][k])
    #for historical data of two days 
    prob=rd.loc[(rd.index.date==t2['date'][k])]
    prob1=rd.loc[ (rd.index.date==t2['date'][k+1])]
    prob=create_historical(prob)
    prob1=create_historical(prob1)
    hist_data=prob.append(prob1)
    # print(hist_data)
    predic=t2.loc[t2['date']==t2['date'][k]] #find predictions of this day
    predic=predic.drop('date',axis=1)
    # print(predic)
    data=pd.DataFrame(index=predic.columns)
    data=data.reset_index()
    # print(data)
    data[['Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']]=(0,0,0,0,0)
    for i in range(len(np.array_split(predic.values[0],46))-1):
      # print(i)
      # print(np.array_split(predic.values[0],46)[i][0])
      data.loc[i,['Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']]=np.array_split(predic.values[0],46)[i][0]
    data.columns = ['ID','Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']
    # print(data)
    #now we have data->predictions and hist_data->historical data so now we can call the RPS
    rps=RPS_calculation(hist_data = hist_data , submission = data)['details']
    # print(rps) ->rps for every stock for one day 
    # print(rps['RPS'])
    tmp=pd.DataFrame(rps['RPS'].values).T
    # print(tmp.T)
    RPS=RPS.append(tmp,ignore_index=True)
    # print(RPS[RPS.index==k])

    
  else:
    #for the last day
    prob=rd.loc[(rd.index.date==t2['date'][k])]
    prob1=rd.loc[ (rd.index.date==rd.index.date[-1])]
    prob=create_historical(prob)
    prob1=create_historical(prob1)
    hist_data=prob.append(prob1)
    # print(hist_data)
    predic=t2.loc[t2['date']==t2['date'][k]] #find predictions of this day
    predic=predic.drop('date',axis=1)
    # print(predic)
    data=pd.DataFrame(index=predic.columns)
    data=data.reset_index()
    # print(data)
    data[['Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']]=(0,0,0,0,0)
    for i in range(len(np.array_split(predic.values[0],46))-1):
      # print(i)
      # print(np.array_split(predic.values[0],46)[i][0])
      data.loc[i,['Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']]=np.array_split(predic.values[0],46)[i][0]
    data.columns = ['ID','Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']
    # print(data)
    #now we have data->predictions and hist_data->historical data so now we can call the RPS
    rps=RPS_calculation(hist_data = hist_data , submission = data)['details']
    # print(rps) ->rps for every stock for one day 
    # print(rps['RPS'])
    tmp=pd.DataFrame(rps['RPS'].values).T
    # print(tmp.T)
    RPS=RPS.append(tmp,ignore_index=True)    
            
print(RPS)


2022-01-04
      ID    Return  Position Rank Rank1 Rank2 Rank3 Rank4 Rank5
21   CZR -0.064480       1.0  1.0   1.0   0.0   0.0   0.0   0.0
27  GOOG -0.046830       2.0  1.0   1.0   0.0   0.0   0.0   0.0
20  CTAS -0.045000       3.0  1.0   1.0   0.0   0.0   0.0   0.0
32  META -0.036728       4.0  1.0   1.0   0.0   0.0   0.0   0.0
41   URI -0.034775       5.0  1.0   1.0   0.0   0.0   0.0   0.0
43  VRSK -0.033464       6.0  1.0   1.0   0.0   0.0   0.0   0.0
39  ROST -0.030930       7.0  1.0   1.0   0.0   0.0   0.0   0.0
38   ROL -0.029212       8.0  1.0   1.0   0.0   0.0   0.0   0.0
4   AMAT -0.029174       9.0  1.0   1.0   0.0   0.0   0.0   0.0
23   DPZ -0.027556      10.0  2.0   0.0   1.0   0.0   0.0   0.0
14  CARR -0.026942      11.0  2.0   0.0   1.0   0.0   0.0   0.0
24   DRE -0.026204      12.0  2.0   0.0   1.0   0.0   0.0   0.0
16  CHTR -0.024830      13.0  2.0   0.0   1.0   0.0   0.0   0.0
3   ALLE -0.023338      14.0  2.0   0.0   1.0   0.0   0.0   0.0
15   CDW -0.022102      15.0 

In [ ]:
d=t2['date']
name=t2.columns[:-1]
# print(np.split(name.values,len(name)))
# print(d.values)
RPS['date']=d.values
RPS=RPS.set_index('date')
RPS.columns=assets
RPS

ABBV       AEP       AIZ      ALLE      AMAT       AMP  \
date                                                                     
2022-01-04  0.227449  0.263710  0.114693  0.115971  0.230446  0.100323   
2022-01-05  0.135898  0.110456  0.110642  0.250493  0.195564  0.099535   
2022-01-06  0.072874  0.262533  0.265855  0.114414  0.230111  0.098756   
2022-01-07  0.226993  0.076111  0.254407  0.113522  0.154880  0.072986   
2022-01-10  0.135736  0.232718  0.067217  0.117310  0.138113  0.226505   
2022-01-11  0.072670  0.123941  0.110108  0.113301  0.195959  0.097620   
2022-01-12  0.269793  0.261210  0.109259  0.112428  0.155066  0.096868   
2022-01-13  0.227722  0.122281  0.066882  0.111565  0.195414  0.096124   
2022-01-14  0.225980  0.121346  0.066370  0.118375  0.230701  0.283129   
2022-01-18  0.135709  0.120421  0.065864  0.077778  0.228944  0.280971   
2022-01-19  0.134679  0.119507  0.108711  0.247530  0.227206  0.073516   
2022-01-20  0.103357  0.256482  0.065464  0.250204  0.152761  0.279020   
2022-01-21  0.134277  0.237947  0.117047  0.248319  0.199157  0.073145   
2022-01-24  0.226502  0.118868  0.116168  0.112621  0.226234  0.072596   
2022-01-25  0.224809  0.117979  0.267360  0.078071  0.199074  0.098270   
2022-01-26  0.223134  0.117100  0.254920  0.077489  0.225950  0.227389   
2022-01-27  0.074267  0.116231  0.065668  0.247918  0.129105  0.279233   
2022-01-28  0.272236  0.115372  0.109627  0.077196  0.199262  0.097909   
2022-01-31  0.135175  0.237769  0.108819  0.246369  0.128421  0.097188   
2022-02-01  0.073889  0.118377  0.065374  0.110737  0.139244  0.096475   
2022-02-02  0.224264  0.255973  0.116910  0.243994  0.152877  0.135330   
2022-02-03  0.102922  0.115422  0.116058  0.252435  0.126946  0.096388   
2022-02-04  0.222175  0.117493  0.065034  0.120420  0.138388  0.225870   
2022-02-07  0.136510  0.115194  0.115288  0.077520  0.137387  0.073511   
2022-02-08  0.271988  0.114364  0.266804  0.250247  0.197769  0.072982   
2022-02-09  0.222553  0.113542  0.110931  0.245572  0.229442  0.224975   
2022-02-10  0.102681  0.256816  0.265693  0.077507  0.227800  0.282147   
2022-02-11  0.220520  0.237842  0.113798  0.076954  0.126176  0.135849   
2022-02-14  0.075181  0.236152  0.263168  0.244379  0.199301  0.225276   
2022-02-15  0.219330  0.112494  0.261305  0.242649  0.197890  0.223681   
2022-02-16  0.101175  0.257990  0.111758  0.121502  0.153384  0.281467   
2022-02-17  0.138492  0.119557  0.065902  0.076986  0.228362  0.223150   
2022-02-18  0.218223  0.255562  0.111054  0.076447  0.226763  0.074219   
2022-02-22  0.216700  0.078953  0.110279  0.242347  0.125879  0.073700   
2022-02-23  0.276517  0.118125  0.065610  0.121497  0.200265  0.136602   
2022-02-24  0.075989  0.117306  0.109599  0.120655  0.151654  0.223155   
2022-02-25  0.138439  0.252827  0.257631  0.076223  0.150606  0.073517   
2022-02-28  0.101624  0.115914  0.116547  0.252250  0.149570  0.281287   
2022-03-01  0.138040  0.116494  0.065576  0.119248  0.138921  0.222999   
2022-03-02  0.101480  0.251314  0.256908  0.118432  0.225643  0.073529   
2022-03-03  0.075533  0.249601  0.065396  0.075987  0.224105  0.280537   
2022-03-04  0.100870  0.247906  0.255428  0.075471  0.147753  0.278632   
2022-03-07  0.138153  0.118093  0.065225  0.245808  0.204380  0.073356   
2022-03-08  0.137222  0.242972  0.064785  0.118474  0.139488  0.224212   
2022-03-09  0.101282  0.115412  0.108120  0.244950  0.224072  0.073210   
2022-03-10  0.218724  0.114639  0.253705  0.113108  0.124584  0.098223   
2022-03-11  0.217264  0.117887  0.064720  0.075563  0.222749  0.072818   
2022-03-14  0.099818  0.117102  0.064289  0.119060  0.205267  0.097667   
2022-03-15  0.139023  0.241907  0.119012  0.075081  0.203905  0.222600   
2022-03-16  0.099693  0.240307  0.063920  0.074584  0.124411  0.096625   
2022-03-17  0.075934  0.238724  0.118285  0.113037  0.202799  0.072886   
2022-03-18  0.099119  0.117419  0.254350  0.112294  0.148836  0.138197   
2022-03-21  0.139126

In [ ]:
RPS.mean(axis=1).mean()

0.158718303833372

In [ ]:
RPS.to_excel('method2_dummy.xlsx')
RPS.to_csv('method2_dummy.csv')

#####Compare with point forecast 
***

In [ ]:
t2.set_index('date',inplace=True)


In [ ]:
flag=False
for i in t2: #for every stock
  print(i)
  for j in range(len(t2[i].values)): #each day of this stock
    temp = t2[i].values[j]
    max= np.max(temp) #find max possiblity
    #replace this max possibility with 1
    temp2=np.where(temp!=max,0,temp)
    temp2=np.where(temp2==max,1,temp2)
    print(temp,'kai',temp2)
    if((temp2==1).sum()>1):
      print('isotimia')
      flag=True
      if((temp2==1).sum()==2):
        temp2=np.where(temp2==1,0.5,temp2)
        print(temp2)
      elif((temp2==1).sum()==3):
        temp2=np.where(temp2==1,0.333,temp2)
        print(temp2)
      elif((temp2==1).sum()==4):
        temp2=np.where(temp2==1,0.25,temp2)
        print(temp2)
      elif((temp2==1).sum()==5):
        temp2=np.where(temp2==1,0.2,temp2)
        print(temp2)
    t2[i].values[j]=temp2

ABBV
[0. 0. 0. 1. 0.] kai [0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.] kai [0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.] kai [0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.] kai [0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.] kai [0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.] kai [0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.] kai [0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.] kai [0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.] kai [0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.] kai [0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.] kai [0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.] kai [0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.] kai [0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.] kai [0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.] kai [0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.] kai [0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.] kai [0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.] kai [0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.] kai [0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.] kai [0. 0. 0. 1. 0.]
[0.  0.  0.5 0.5 0. ] kai [0. 0. 1. 1. 0.]
isotimia
[0.  0.  0.5 0.5 0. ]
[0.  0.  0.5 0.5 0. ] kai [0. 0. 1. 1. 0.]
isotimia
[0.  0.  0.5 0.5 0. ]
[0. 0. 0. 1. 0.] kai [0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.] kai [0. 0. 0. 1. 0.]
[0. 0. 0. 1

In [ ]:
flag

True

In [ ]:
t2=t2.reset_index()

In [ ]:
RPS=pd.DataFrame()

# RPS=RPS.drop('date',axis=1)
# print(RPS.index[2])
for k in t2.index: #for everyday of a stock->index
  prob=pd.DataFrame()
  prob1=pd.DataFrame()
  predic=pd.DataFrame()
  if(t2['date'][k]!=t2['date'].tail(1).values): #if it's not for the last day 
    #for historical data of two days 
    prob=rd.loc[(rd.index.date==t2['date'][k])]
    prob1=rd.loc[ (rd.index.date==t2['date'][k+1])]
    prob=create_historical(prob)
    prob1=create_historical(prob1)
    hist_data=prob.append(prob1)
    # print(hist_data)
    predic=t2.loc[t2['date']==t2['date'][k]] #find predictions of this day
    predic=predic.drop('date',axis=1)
    # print(predic)
    data=pd.DataFrame(index=predic.columns)
    data=data.reset_index()
    # print(data)
    data[['Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']]=(0,0,0,0,0)
    for i in range(len(np.array_split(predic.values[0],46))-1):
      # print(i)
      print(np.array_split(predic.values[0],46)[i][0])
      data.loc[i,['Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']]=np.array_split(predic.values[0],46)[i][0]
    data.columns = ['ID','Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']
    # print(data)
    print(np.max(hist_data.date))
    #now we have data->predictions and hist_data->historical data so now we can call the RPS
    rps=RPS_calculation(hist_data = hist_data , submission = data)['details']
    # print(rps) ->rps for every stock for one day 
    # print(rps['RPS'])
    tmp=pd.DataFrame(rps['RPS'].values).T
    # print(tmp.T)
    RPS=RPS.append(tmp,ignore_index=True)
    # print(RPS[RPS.index==k])

    
  else:
    #for the last day
    prob=rd.loc[(rd.index.date==t2['date'][k])]
    prob1=rd.loc[ (rd.index.date==rd.index.date[-1])]
    prob=create_historical(prob)
    prob1=create_historical(prob1)
    hist_data=prob.append(prob1)
    # print(hist_data)
    predic=t2.loc[t2['date']==t2['date'][k]] #find predictions of this day
    predic=predic.drop('date',axis=1)
    # print(predic)
    data=pd.DataFrame(index=predic.columns)
    data=data.reset_index()
    # print(data)
    data[['Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']]=(0,0,0,0,0)
    for i in range(len(np.array_split(predic.values[0],46))-1):
      # print(i)
      # print(np.array_split(predic.values[0],46)[i][0])
      data.loc[i,['Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']]=np.array_split(predic.values[0],46)[i][0]
    data.columns = ['ID','Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']
    # print(data)
    
    print(hist_data)
    #now we have data->predictions and hist_data->historical data so now we can call the RPS
    rps=RPS_calculation(hist_data = hist_data , submission = data)['details']
    
    # print(rps) ->rps for every stock for one day 
    # print(rps['RPS'])
    tmp=pd.DataFrame(rps['RPS'].values).T
    # print(tmp.T)
    RPS=RPS.append(tmp,ignore_index=True)              
print(RPS)

[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0. 1. 0. 0. 0.]
[0. 0. 0. 0. 1.]
[0. 0. 0. 1. 0.]
[1. 0. 0. 0. 0.]
[0. 0. 0. 1. 0.]
[0. 0. 1. 0. 0.]
[0.  0.5 0.  0.  0.5]
[0. 0. 1. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 0. 1. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 0. 1. 0. 0.]
[0.333 0.333 0.    0.    0.333]
[1. 0. 0. 0. 0.]
[0. 0. 1. 0. 0.]
[0. 0. 0. 0. 1.]
[0. 0. 0. 1. 0.]
[1. 0. 0. 0. 0.]
[0. 0. 1. 0. 0.]
[0. 0. 0. 0. 1.]
[0. 0. 1. 0. 0.]
[0. 0. 0. 0. 1.]
[0. 0. 0. 0. 1.]
[0. 0. 1. 0. 0.]
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 0. 0. 0. 1.]
[0. 0. 0. 1. 0.]
[0. 1. 0. 0. 0.]
[0.  0.  0.  0.5 0.5]
[1. 0. 0. 0. 0.]
[0. 0. 1. 0. 0.]
[1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]
[0. 0. 1. 0. 0.]
[0. 0. 0. 0. 1.]
[0. 0. 1. 0. 0.]
[0. 0. 0. 1. 0.]
[1. 0. 0. 0. 0.]
2022-01-05
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0. 1. 0. 0. 0.]
[0. 0. 0. 0. 1.]
[0. 0. 0. 1. 0.]
[1. 0. 0. 0. 0.]
[0. 0. 0. 1. 0.]
[0. 0. 1. 0. 0.]
[0.  0.5 0.  0.  0.5]
[0. 0. 1. 0. 0.]
[0. 1. 

In [ ]:
d=t2['date']
name=t2.columns[:-1]
# print(np.split(name.values,len(name)))
# print(d.values)
RPS['date']=d.values
RPS=RPS.set_index('date')
RPS.columns=assets
RPS

ABBV  AEP  AIZ  ALLE  AMAT  AMP  AMZN  AVB  AVY       AXP  ...  \
date                                                                   ...   
2022-01-04  0.20  0.2  0.0   0.0   0.8  0.0   0.4  0.2  0.2  0.150000  ...   
2022-01-05  0.40  0.4  0.4   0.2   0.0  0.0   0.2  0.2  0.0  0.150000  ...   
2022-01-06  0.20  0.2  0.2   0.0   0.8  0.0   0.4  0.4  0.0  0.066667  ...   
2022-01-07  0.20  0.2  0.6   0.0   0.6  0.2   0.2  0.2  0.4  0.200000  ...   
2022-01-10  0.40  0.6  0.2   0.4   0.2  0.2   0.8  0.4  0.4  0.200000  ...   
2022-01-11  0.20  0.0  0.4   0.0   0.0  0.0   0.2  0.0  0.2  0.250000  ...   
2022-01-12  0.60  0.2  0.4   0.0   0.6  0.0   0.0  0.0  0.0  0.044489  ...   
2022-01-13  0.20  0.0  0.1   0.0   0.0  0.0   0.6  0.2  0.2  0.400000  ...   
2022-01-14  0.20  0.0  0.1   0.4   0.8  0.6   0.2  0.0  0.2  0.000000  ...   
2022-01-18  0.40  0.0  0.1   0.2   0.8  0.6   0.0  0.4  0.0  0.400000  ...   
2022-01-19  0.40  0.0  0.1   0.2   0.8  0.2   0.0  0.2  0.2  0.200000  ...   
2022-01-20  0.00  0.2  0.2   0.6   0.6  0.6   0.0  0.0  0.0  0.000000  ...   
2022-01-21  0.40  0.6  0.4   0.6   0.0  0.2   0.6  0.6  0.2  0.200000  ...   
2022-01-24  0.20  0.0  0.1   0.0   0.8  0.2   0.0  0.2  0.2  0.400000  ...   
2022-01-25  0.20  0.0  0.2   0.2   0.0  0.0   0.4  0.2  0.0  0.400000  ...   
2022-01-26  0.20  0.0  0.6   0.2   0.8  0.2   0.6  0.4  0.2  0.400000  ...   
2022-01-27  0.20  0.4  0.2   0.2   0.4  0.6   0.8  0.0  0.0  0.400000  ...   
2022-01-28  0.60  0.4  0.4   0.2   0.0  0.0   0.8  0.4  0.4  0.200000  ...   
2022-01-31  0.40  0.6  0.1   0.2   0.4  0.0   0.6  0.4  0.0  0.400000  ...   
2022-02-01  0.20  0.0  0.2   0.0   0.2  0.0   0.2  0.2  0.4  0.300000  ...   
2022-02-02  0.25  0.2  0.4   0.2   0.6  0.4   0.0  0.0  0.4  0.100000  ...   
2022-02-03  0.05  0.4  0.1   0.6   0.4  0.0   0.8  0.4  0.4  0.044489  ...   
2022-02-04  0.20  0.0  0.2   0.4   0.2  0.2   0.4  0.6  0.4  0.200000  ...   
2022-02-07  0.40  0.4  0.0   0.2   0.2  0.2   0.8  0.6  0.2  0.050000  ...   
2022-02-08  0.60  0.4  0.2   0.6   0.0  0.2   0.0  0.2  0.2  0.400000  ...   
2022-02-09  0.20  0.4  0.4   0.2   0.8  0.2   0.4  0.6  0.2  0.000000  ...   
2022-02-10  0.00  0.2  0.2   0.2   0.8  0.6   0.0  0.0  0.2  0.600000  ...   
2022-02-11  0.20  0.6  0.0   0.2   0.4  0.4   0.8  0.4  0.2  0.000000  ...   
2022-02-14  0.20  0.6  0.2   0.2   0.0  0.2   0.2  0.4  0.2  0.000000  ...   
2022-02-15  0.20  0.4  0.2   0.2   0.0  0.2   0.8  0.4  0.0  0.400000  ...   
2022-02-16  0.00  0.2  0.0   0.4   0.6  0.6   0.2  0.2  0.2  0.400000  ...   
2022-02-17  0.40  0.0  0.2   0.2   0.8  0.2   0.0  0.2  0.2  0.400000  ...   
2022-02-18  0.20  0.2  0.0   0.2   0.8  0.2   0.0  0.2  0.2  0.600000  ...   
2022-02-22  0.20  0.2  0.0   0.2   0.4  0.2   0.0  0.0  0.2  0.400000  ...   
2022-02-23  0.60  0.0  0.2   0.4   0.0  0.4   0.8  0.2  0.2  0.300000  ...   
2022-02-24  0.20  0.0  0.0   0.4   0.6  0.2   0.0  0.0  0.2  0.100000  ...   
2022-02-25  0.40  0.2  0.2   0.2   0.6  0.2   0.6  0.6  0.4  0.200000  ...   
2022-02-28  0.00  0.0  0.4   0.6   0.6  0.6   0.4  0.2  0.4  0.400000  ...   
2022-03-01  0.40  0.4  0.2   0.4   0.2  0.2   0.2  0.0  0.2  0.200000  ...   
2022-03-02  0.00  0.2  0.2   0.4   0.8  0.2   0.0  0.2  0.2  0.000000  ...   
2022-03-03  0.20  0.2  0.2   0.2   0.8  0.6   0.4  0.0  0.2  0.400000  ...   
2022-03-04  0.00  0.2  0.2   0.2   0.6  0.6   0.0  0.0  0.4  0.400000  ...   
2022-03-07  0.40  0.4  0.2   0.2   0.0  0.2   0.4  0.4  0.2  0.200000  ...   
2022-03-08  0.40  0.6  0.2   0.4   0.2  0.2   0.4  0.2  0.4  0.400000  ...   
2022-03-09  0.00  0.0  0.0   0.2   0.8  0.2   0.8  0.2  0.2  0.200000  ...   
2022-03-10  0.20  0.0  0.2   0.0   0.4  0.0   0.4  0.2  0.2  0.000000  ...   
2022-03-11  0.20  0.4  0.2   0.2   0.8  0.2   0.0  0.4  0.4  0.400000  ...   
2022-03-14  0.00  0.4  0.2   0.4   0.0  0.0   0.8  0.6  0.4  0.000000  ...   
2022-03-15  0.40  0.6  0.4   0.2   0.0  0.2   0.6  0.4  0.0  0.000000  ...   
2022-03-16  0.00  0.6  0.2   0.2  

In [ ]:
RPS.mean(axis=1).mean()

0.2878291045185185

In [ ]:
#save results
RPS.to_excel('method2_dummy_POINT_FORECAST.xlsx')