#####Libraries
***

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
!pip install yfinance --upgrade --no-cache-dir
import yfinance as yf
from pandas_datareader import data as pdr
yf.pdr_override()
# pip install TA-lib
!wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz

!tar -xzf ta-lib-0.4.0-src.tar.gz
%cd ta-lib/
!./configure --prefix=$HOME
!make
!make install

!TA_LIBRARY_PATH=~/lib TA_INCLUDE_PATH=~/include pip install ta-lib
import talib as ta
import matplotlib.pyplot as plt

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 62 kB 6.8 MB/s 
  Attempting uninstall: requests
    Found existing installation: requests 2.23.0
    Uninstalling requests-2.23.0:
      Successfully uninstalled requests-2.23.0
--2022-08-31 09:50:14--  http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
Resolving prdownloads.sourceforge.net (prdownloads.sourceforge.net)... 204.68.111.105
Connecting to prdownloads.sourceforge.net (prdownloads.sourceforge.net)|204.68.111.105|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://downloads.sourceforge.net/project/ta-lib/ta-lib/0.4.0/ta-lib-0.4.0-src.tar.gz [following]
--2022-08-31 09:50:14--  http://downloads.sourceforge.net/project/ta-lib/ta-lib/0.4.0/ta-lib-0.4.0-src.tar.gz
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 204.68.111.105
Reusing existing connection to prdownlo

#####Load Dataset
***

In [4]:
#φτιάχνω τη λίστα με τα assets μου -> 50 μετοχές 
#διόρθωση : θα βγάλω τυχαία άλλες 4 μετοχές μαζί με την OGN επειδή δεν έχει το ίδιο μέγεθος με τις άλλες 
#βγάζω OGN ,WRK,HST,CE,ACN
assets= ["ABBV","AEP","AIZ","ALLE","AMAT","AMP","AMZN","AVB","AVY",   
  "AXP","BDX","BF-B","BMY","BR","CARR","CDW","CHTR","CNC",   
  "CNP","COP","CTAS","CZR","DG","DPZ","DRE","DXC","META","FTV",   
  "GOOG","GPC","HIG","JPM","KR","PG","PPL","PRU",   
  "PYPL","RE","ROL","ROST","UNH","URI","V","VRSK","XOM"]

In [5]:
#άρα πρέπει να κατεβάσουμε όλα τα adj close για όλες τις τιμές όλων των μετοχών και να κάνουμε απόλυτο ranking και σε 5 κλασεις (targets)
r=pd.DataFrame(index=pdr.get_data_yahoo(assets[0],'2021-01-01','2022-04-01')['Adj Close'].index)
#παίρνω τιμές για ένα χρόνο και 3 μήνες
for i in assets:
  # print('i metoxi me onoma:',i,'exei megethos',pdr.get_data_yahoo(i,'2021-01-01','2022-04-01')['Adj Close'].count())
  temp= pdr.get_data_yahoo(i,'2021-01-01','2022-04-01')['Adj Close']
  temp=temp.dropna()
  r[i]=temp.values
#φτιάχνω ένα αντίγραφο με τις τιμές για να το έχω 
rd=pd.DataFrame(r)
rd

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%********

ABBV        AEP         AIZ        ALLE        AMAT  \
Date                                                                    
2021-01-04   97.798592  76.819260  128.241989  112.358444   85.672470   
2021-01-05   98.809891  76.715630  128.280807  112.574356   88.364830   
2021-01-06   97.956322  77.327995  133.911026  115.136009   89.577881   
2021-01-07   99.004723  75.264778  135.260315  118.168732   93.256462   
2021-01-08   99.524284  74.595879  134.551666  117.756523   94.242661   
...                ...        ...         ...         ...         ...   
2022-03-25  158.487930  95.333145  183.029373  111.845345  136.376923   
2022-03-28  159.116653  96.091171  182.225754  113.020569  136.973938   
2022-03-29  159.322952  97.154373  179.884308  114.584213  140.735077   
2022-03-30  160.865295  97.873009  180.737549  112.891090  135.123199   
2022-03-31  159.254181  98.217552  180.400223  109.335548  131.143143   

                   AMP        AMZN         AVB         AVY         AXP  ...  \
Date                                                                    ...   
2021-01-04  182.556015  159.331497  148.850800  148.753860  115.625526  ...   
2021-01-05  181.488495  160.925507  148.420074  149.077026  116.242622  ...   
2021-01-06  191.901703  156.919006  152.401672  154.776474  120.542824  ...   
2021-01-07  194.221130  158.108002  150.324753  159.604355  119.589340  ...   
2021-01-08  195.599213  159.134995  151.645554  153.503403  119.707306  ...   
...                ...         ...         ...         ...         ...  ...   
2022-03-25  311.729828  164.773499  243.735245  172.392029  189.033966  ...   
2022-03-28  308.232391  168.990494  246.446274  172.750473  188.457764  ...   
2022-03-29  309.342041  169.315002  254.599045  178.127136  189.689651  ...   
2022-03-30  307.737000  166.300995  249.917114  176.066086  188.517365  ...   
2022-03-31  297.591339  162.997498  246.365997  173.218445  185.775452  ...   

                   PRU        PYPL          RE        ROL        ROST  \
Date                                                                    
2021-01-04   70.458305  231.919998  218.876434  37.469650  115.092255   
2021-01-05   71.140755  234.910004  217.072540  38.086956  115.190552   
2021-01-06   75.355347  226.830002  229.939713  38.714066  120.224060   
2021-01-07   75.023346  235.039993  231.590103  39.360771  119.958611   
2021-01-08   74.423882  242.460007  229.296799  39.978081  120.342026   
...                ...         ...         ...        ...         ...   
2022-03-25  118.004997  113.760002  295.426666  33.621418   89.881897   
2022-03-28  117.223892  116.169998  294.201508  34.228012   91.216866   
2022-03-29  118.004997  121.180000  298.953888  34.953945   95.191925   
2022-03-30  117.458237  118.489998  301.068237  35.242325   92.262939   
2022-03-31  115.378540  115.650002  297.768280  34.854500   90.120995   

                   UNH         URI           V        VRSK        XOM  
Date                                                                   
2021-01-04  342.416077  229.649994  215.285767  200.928055  37.906906  
2021-01-05  337.811310  235.570007  212.072678  200.026810  39.733746  
2021-01-06  351.988037  256.549988  210.204147  198.135162  40.747643  
2021-01-07  357.631226  264.679993  211.380630  199.036392  41.067341  
2021-01-08  356.024506  260.149994  213.002014  198.967087  41.524048  
...                ...         ...         ...         ...        ...  
2022-03-25  511.206970  363.670013  217.628159  207.601166  83.524574  
2022-03-28  511.376343  363.399994  219.959564  211.194260  81.181572  
2022-03-29  508.915131  365.200012  227.282578  214.388123  80.750229  
2022-03-30  518.969238  359.190002  223.127884  216.553970  82.132500  
2022-03-31  508.157806  355.209991  220.955887  214.218460  80.965904  

[314 rows x 45 columns]

In [6]:
rd1= rd.pct_change().shift(-1)
rd2=rd1.rank(axis=1,method='first')
rd2=rd2.dropna()
rd2.astype(int)
jk=rd2.copy()
jk.astype(int)

ABBV  AEP  AIZ  ALLE  AMAT  AMP  AMZN  AVB  AVY  AXP  ...  PRU  \
Date                                                              ...        
2021-01-04    34   14   15    21    41    9    33   12   22   25  ...   32   
2021-01-05     8   14   37    25    20   40     3   28   31   29  ...   41   
2021-01-06    25    2   23    36    44   28    20    3   40    8  ...    9   
2021-01-07    28    8   13    17    37   31    30   34    1   22  ...   11   
2021-01-08    39   23   22    29    42   26     5   20   43   21  ...   27   
...          ...  ...  ...   ...   ...  ...   ...  ...  ...  ...  ...  ...   
2022-03-24    21   16   27     4     3   28    22   40   45   24  ...   38   
2022-03-25    22   27    9    31    23    4    45   36   19   13  ...    8   
2022-03-28     7   20    2    24    36   11     9   41   39   14  ...   15   
2022-03-29    41   38   33    11     2   21     9    6   14   20  ...   22   
2022-03-30    33   44   40     4     6    3    16   23   20   22  ...   19   

            PYPL  RE  ROL  ROST  UNH  URI   V  VRSK  XOM  
Date                                                      
2021-01-04    36   6   38    17    5   40   3    11   44  
2021-01-05     1  42   21    36   35   44   7     6   26  
2021-01-06    43  19   30    11   29   41  18    16   21  
2021-01-07    45   6   42    26   14    3  33    19   38  
2021-01-08     7  16   28    10   15   13  11     9   44  
...          ...  ..  ...   ...  ...  ...  ..   ...  ...  
2022-03-24     2  37   25     5    8   36  19     7   42  
2022-03-25    42  11   41    38   18   16  32    40    2  
2022-03-28    43  26   33    44    5   12  42    25    4  
2022-03-29     5  37   39     3   45   10   7    42   44  
2022-03-30     9  29   28    11   15   27  34    31   24  

[313 rows x 45 columns]

In [7]:
def rank_data(df1):
  for i in range(len(df1.index)):
    d=df1.loc[df1.index[i]]  #της κάθε μέρας d[1] δίνει μόνο τις τιμές 
    #print(d)
    d=d.sort_values()
    d[0:9]=1
    d[9:18]=2
    d[18:27]=3
    d[27:36]=4
    d[36:45]=5
    df1.loc[df1.index[i]]=d
    #print(df1.loc[df1.index[i]])
    #print(d)
  df1=df1.astype(int)
  return df1
r5=rd2.copy()
rd3=rank_data(r5)
rd3

ABBV  AEP  AIZ  ALLE  AMAT  AMP  AMZN  AVB  AVY  AXP  ...  PRU  \
Date                                                              ...        
2021-01-04     4    2    2     3     5    1     4    2    3    3  ...    4   
2021-01-05     1    2    5     3     3    5     1    4    4    4  ...    5   
2021-01-06     3    1    3     4     5    4     3    1    5    1  ...    1   
2021-01-07     4    1    2     2     5    4     4    4    1    3  ...    2   
2021-01-08     5    3    3     4     5    3     1    3    5    3  ...    3   
...          ...  ...  ...   ...   ...  ...   ...  ...  ...  ...  ...  ...   
2022-03-24     3    2    3     1     1    4     3    5    5    3  ...    5   
2022-03-25     3    3    1     4     3    1     5    4    3    2  ...    1   
2022-03-28     1    3    1     3     4    2     1    5    5    2  ...    2   
2022-03-29     5    5    4     2     1    3     1    1    2    3  ...    3   
2022-03-30     4    5    5     1     1    1     2    3    3    3  ...    3   

            PYPL  RE  ROL  ROST  UNH  URI  V  VRSK  XOM  
Date                                                     
2021-01-04     4   1    5     2    1    5  1     2    5  
2021-01-05     1   5    3     4    4    5  1     1    3  
2021-01-06     5   3    4     2    4    5  2     2    3  
2021-01-07     5   1    5     3    2    1  4     3    5  
2021-01-08     1   2    4     2    2    2  2     1    5  
...          ...  ..  ...   ...  ...  ... ..   ...  ...  
2022-03-24     1   5    3     1    1    4  3     1    5  
2022-03-25     5   2    5     5    2    2  4     5    1  
2022-03-28     5   3    4     5    1    2  5     3    1  
2022-03-29     1   5    5     1    5    2  1     5    5  
2022-03-30     1   4    4     2    2    3  4     4    3  

[313 rows x 45 columns]

#####Necessary funtions for RPS calculation 
***

In [14]:
def RPS_calculation(hist_data, submission, asset_no=44):
    # print('check')
    if hist_data.shape[0]<=asset_no:
        return np.nan    
    # print('check')
    asset_id = pd.unique(hist_data.symbol)
    
    for i in range(len(pd.unique(hist_data.date))):
        if len(hist_data[hist_data.date == pd.unique(hist_data.date)[i]])<len(asset_id):
            for asset in [x for x in asset_id if x not in hist_data[hist_data.date == pd.unique(hist_data.date)[i]].symbol.values]:
                right_price = hist_data[hist_data.symbol==asset].sort_values(by='date')
                right_price = right_price[right_price.date <= pd.unique(hist_data.date)[i]]
                right_price = right_price.price.iloc[-1]
                hist_data = hist_data.append({'date' : pd.unique(hist_data.date)[i],
                                               'symbol' : asset,
                                               'price' : right_price}, ignore_index=True)

    #Compute percentage returns
    asset_id = sorted(asset_id) 

    #Compute percentage returns
    returns = pd.DataFrame(columns = ["ID", "Return"])
    
    min_date = min(hist_data.date)
    max_date = max(hist_data.date)
    
    for i in range(0,len(asset_id)):
        temp = hist_data.loc[hist_data.symbol==asset_id[i]]
        
        open_price = float(temp.loc[temp.date==min_date].price)
        close_price = float(temp.loc[temp.date==max_date].price)
        
        returns = returns.append({'ID': temp.symbol.iloc[0], 
                                'Return': (close_price - open_price)/open_price}, ignore_index=True)

    #Define the relevant position of each asset
    ranking = pd.DataFrame(columns=["ID", "Position", "Return"])
    ranking.ID = list(asset_id)
    ranking.Return = returns.Return
    ranking.Position = ranking.Return.rank(method = 'min')

    #Handle Ties
    Series_per_position = pd.DataFrame(columns=["Position","Series", "Rank", "Rank1", "Rank2","Rank3", "Rank4", "Rank5"])
    Series_per_position.Position = list(pd.unique(ranking.Position.sort_values(ascending=True)))
    temp = ranking.Position.value_counts()
    temp = pd.DataFrame(zip(temp.index, temp), columns = ["Rank", "Occurencies"])
    temp = temp.sort_values(by = ["Rank"],ascending=True)
    Series_per_position.Series = list(temp.Occurencies)
    Series_per_position

    total_ranks = Series_per_position.Position.values[-1]
    for i in range(0,Series_per_position.shape[0]):
    
        start_p = Series_per_position.Position[i]
        end_p = Series_per_position.Position[i] + Series_per_position.Series[i]
        temp = pd.DataFrame(columns = ["Position","Rank", "Rank1", "Rank2", "Rank3", "Rank4","Rank5"])
        temp.Position = list(range(int(start_p),int(end_p)))

        if(temp.loc[temp.Position.isin(list(range(1,int(0.2*total_ranks+1))))].empty==False):
            temp.loc[temp.Position.isin(list(range(1,int(0.2*total_ranks+1))))] = temp.loc[temp.Position.isin(list(range(1,int(0.2*total_ranks+1))))].assign(Rank=1)
            temp.loc[temp.Position.isin(list(range(1,int(0.2*total_ranks+1))))] = temp.loc[temp.Position.isin(list(range(1,int(0.2*total_ranks+1))))].assign(Rank1=1.0)

        elif(temp.loc[temp.Position.isin(list(range(int(0.2*total_ranks+1),int(0.4*total_ranks+1))))].empty==False):
            temp.loc[temp.Position.isin(list(range(int(0.2*total_ranks+1),int(0.4*total_ranks+1))))] = temp.loc[temp.Position.isin(list(range(int(0.2*total_ranks+1),int(0.4*total_ranks+1))))].assign(Rank=2)
            temp.loc[temp.Position.isin(list(range(int(0.2*total_ranks+1),int(0.4*total_ranks+1))))] = temp.loc[temp.Position.isin(list(range(int(0.2*total_ranks+1),int(0.4*total_ranks+1))))].assign(Rank2=1.0)

        elif(temp.loc[temp.Position.isin(list(range(int(0.4*total_ranks+1),int(0.6*total_ranks+1))))].empty==False):
            temp.loc[temp.Position.isin(list(range(int(0.4*total_ranks+1),int(0.6*total_ranks+1))))] = temp.loc[temp.Position.isin(list(range(int(0.4*total_ranks+1),int(0.6*total_ranks+1))))].assign(Rank=3)
            temp.loc[temp.Position.isin(list(range(int(0.4*total_ranks+1),int(0.6*total_ranks+1))))] = temp.loc[temp.Position.isin(list(range(int(0.4*total_ranks+1),int(0.6*total_ranks+1))))].assign(Rank3=1.0)

        elif(temp.loc[temp.Position.isin(list(range(int(0.6*total_ranks+1),int(0.8*total_ranks+1))))].empty==False):
            temp.loc[temp.Position.isin(list(range(int(0.6*total_ranks+1),int(0.8*total_ranks+1))))] = temp.loc[temp.Position.isin(list(range(int(0.6*total_ranks+1),int(0.8*total_ranks+1))))].assign(Rank=4)
            temp.loc[temp.Position.isin(list(range(int(0.6*total_ranks+1),int(0.8*total_ranks+1))))] = temp.loc[temp.Position.isin(list(range(int(0.6*total_ranks+1),int(0.8*total_ranks+1))))].assign(Rank4=1.0)

        elif(temp.loc[temp.Position.isin(list(range(int(0.8*total_ranks+1),int(total_ranks+1))))].empty==False):
            temp.loc[temp.Position.isin(list(range(int(0.8*total_ranks+1),int(total_ranks+1))))] = temp.loc[temp.Position.isin(list(range(int(0.8*total_ranks+1),int(total_ranks+1))))].assign(Rank=5)
            temp.loc[temp.Position.isin(list(range(int(0.8*total_ranks+1),int(total_ranks+1))))] = temp.loc[temp.Position.isin(list(range(int(0.8*total_ranks+1),int(total_ranks+1))))].assign(Rank5=1.0)
        temp = temp.fillna(0)
        Series_per_position.iloc[i,2:Series_per_position.shape[1]] = temp.mean(axis = 0).iloc[1:temp.shape[1]]

    Series_per_position = Series_per_position.drop('Series', axis = 1)
    ranking = pd.merge(ranking,Series_per_position, on = "Position")
    ranking = ranking[["ID", "Return", "Position", "Rank", "Rank1", "Rank2", "Rank3", "Rank4", "Rank5"]]
    ranking = ranking.sort_values(["Position"])
    # print(ranking)
    #Evaluate submission
    rps_sub = []
    #for aid in list((pd.unique(ranking.ID))):
    for aid in asset_id:

        target = np.cumsum(ranking.loc[ranking.ID==aid].iloc[:,4:9].values).tolist()
        frc = np.cumsum(submission.loc[submission.ID==aid].iloc[:,1:6].values).tolist()
        rps_sub.append(np.mean([(a - b)**2 for a, b in zip(target, frc)]))
    submission["RPS"] = rps_sub
    
    output = {'RPS' : np.mean(rps_sub),
              'details' : submission}
    
    return(output)

In [15]:
def create_historical(prob):
  prob=prob.rename_axis("symbol", axis="columns")
  prob=prob.T
  prob['date']=prob.columns.date[0]
  prob.columns = ['price', 'date']
  prob=prob.reset_index()
  prob=prob[['symbol','date','price']]
  return prob

#####Preparation of the Data-**Features**
***

In [10]:
stock=dict()
for i in assets:
  #παίρνω δεδομένα για 15 μήνες περιπου->από Ιανουάριο 2021 μέχρι Μάρτιο 2022
  stock[i]=pdr.get_data_yahoo(i,'2021-01-01','2022-04-01') 
  # print(df)
  #από αυτές κρατάμε μόνο τις πρώτες 5 στήλες 
  stock[i]=stock[i].iloc[:,:5]

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%********

In [11]:
stock

{'ABBV':                   Open        High         Low       Close   Adj Close
 Date                                                                  
 2021-01-04  107.180000  107.349998  103.860001  105.410004   97.798584
 2021-01-05  105.410004  107.019997  104.629997  106.500000   98.809883
 2021-01-06  104.750000  107.190002  104.180000  105.580002   97.956322
 2021-01-07  106.110001  107.059998  105.570000  106.709999   99.004715
 2021-01-08  106.839996  107.529999  105.760002  107.269997   99.524284
 ...                ...         ...         ...         ...         ...
 2022-03-25  160.550003  161.979996  160.229996  161.330002  158.487930
 2022-03-28  160.610001  162.029999  159.529999  161.970001  159.116653
 2022-03-29  162.990005  163.279999  161.289993  162.179993  159.322952
 2022-03-30  161.720001  164.350006  161.720001  163.750000  160.865295
 2022-03-31  162.929993  164.660004  162.100006  162.110001  159.254181
 
 [314 rows x 5 columns],
 'AEP':                  Open

In [12]:
#---Prepare the new features that have been selected previously---#

for j in assets:
    df=stock[j] #all the days we need so we can fix the columns 
    # print('to df ftanei mexri ',stock[j].iloc[:-61].tail(1))
    # print(df)
    #τώρα θα προσθέσουμε τις καινούριες στήλες με τα features μας 
    df['(high2-high1)/high2']= (df['High'].shift(2)-df['High'].shift(1))/df['High'].shift(2)
    df['(low2-low1)/low2']= (df['Low'].shift(2)-df['Low'].shift(1))/df['Low'].shift(2)
    df['av_3']=df['Adj Close'].shift(1).rolling(window=3).mean().pct_change()
    df['av_10']=df['Adj Close'].shift(1).rolling(window=10).mean().pct_change()
    df['av_14']=df['Adj Close'].shift(1).rolling(window=14).mean().pct_change()
    df['ADX'] = ta.ADX(df['High'].shift(1), df['Low'].shift(1), df['Close'].shift(1), timeperiod=6)/100
    df['ADX_14'] = ta.ADX(df['High'].shift(1), df['Low'].shift(1), df['Close'].shift(1), timeperiod=14)/100
    df['WILLR']= ta.WILLR(df['High'].shift(1), df['Low'].shift(1), df['Close'].shift(1),timeperiod=14)/100
    # df['dist_from_mean_10'] = (df['Adj Close'].shift(1) - (df['Adj Close'].shift(1).rolling(window=10).mean()))
    df = df.iloc[1: , :]
    df['absolute rank']= jk[j].astype(int).shift(1)
    df['Rank']= rd3[j]
    stock[j]=df

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


In [13]:
stock

{'ABBV':                   Open        High         Low       Close   Adj Close  \
 Date                                                                     
 2021-01-05  105.410004  107.019997  104.629997  106.500000   98.809883   
 2021-01-06  104.750000  107.190002  104.180000  105.580002   97.956322   
 2021-01-07  106.110001  107.059998  105.570000  106.709999   99.004715   
 2021-01-08  106.839996  107.529999  105.760002  107.269997   99.524284   
 2021-01-11  107.070000  109.559998  107.070000  109.019997  101.147919   
 ...                ...         ...         ...         ...         ...   
 2022-03-25  160.550003  161.979996  160.229996  161.330002  158.487930   
 2022-03-28  160.610001  162.029999  159.529999  161.970001  159.116653   
 2022-03-29  162.990005  163.279999  161.289993  162.179993  159.322952   
 2022-03-30  161.720001  164.350006  161.720001  163.750000  160.865295   
 2022-03-31  162.929993  164.660004  162.100006  162.110001  159.254181   
 
             (h

#####Model Logistic Regression 

In [16]:
from sklearn.linear_model import LogisticRegression

In [18]:
model1=LogisticRegression(multi_class='multinomial', solver='lbfgs',max_iter=500)
model2= LogisticRegression(multi_class='multinomial', solver='newton-cg',max_iter=500)

In [19]:
prob1=dict()
prob2=dict()

for j in assets:
    tmp1=[]
    tmp2=[]
    df=stock[j]
    df1=df.dropna()
    X= df1.iloc[:,5:14]
    # print(X) #it has all the days
    y= df1['Rank']
    X_train= X.iloc[:-60] #only the days of one year until 3/01
    # print(X_train)
    Y_train= y.iloc[:-60]
    # print(Y_train)
    model1.fit(X_train,Y_train)
    model2.fit(X_train,Y_train)
    #now each day we will use the models to predict 
    for i in range(59,0,-1): #from 4/01 and later -->predictions
      X_validation=X.iloc[-(i+1):-i] 
      # print(X_validation)
      Y_validation= y.iloc[-(i+1):-i]
      print(Y_validation.index) 
      probability1= model1.predict_proba(X_validation)
      print(probability1[0])
      tmp1.append(probability1[0])
      probability2= model2.predict_proba(X_validation)
      tmp2.append(probability2[0])
    X_validation=X.tail(1) 
    # print(X_validation)
    Y_validation= y.tail(1)
    print(Y_validation.index) 
    probability1= model1.predict_proba(X_validation)
    print(probability1[0])
    tmp1.append(probability1[0])
    probability2= model2.predict_proba(X_validation)
    tmp2.append(probability2[0])
    prob1[j]=tmp1
    prob2[j]=tmp2

Η έξοδος ροής περικόπηκε στις τελευταίες 5000 γραμμές.
DatetimeIndex(['2022-02-02'], dtype='datetime64[ns]', name='Date', freq=None)
[0.10915104 0.26989213 0.18325877 0.2899456  0.14775246]
DatetimeIndex(['2022-02-03'], dtype='datetime64[ns]', name='Date', freq=None)
[0.09537738 0.27535399 0.18069006 0.29762441 0.15095417]
DatetimeIndex(['2022-02-04'], dtype='datetime64[ns]', name='Date', freq=None)
[0.1754385  0.24426439 0.19947236 0.26136022 0.11946453]
DatetimeIndex(['2022-02-07'], dtype='datetime64[ns]', name='Date', freq=None)
[0.19107092 0.23236479 0.19895536 0.22326816 0.15434077]
DatetimeIndex(['2022-02-08'], dtype='datetime64[ns]', name='Date', freq=None)
[0.15410962 0.24287867 0.19781744 0.23033136 0.17486291]
DatetimeIndex(['2022-02-09'], dtype='datetime64[ns]', name='Date', freq=None)
[0.20838646 0.21565992 0.216093   0.18232479 0.17753582]
DatetimeIndex(['2022-02-10'], dtype='datetime64[ns]', name='Date', freq=None)
[0.12033099 0.23741644 0.19311901 0.20110829 0.24802527]


In [20]:
prob1['date']=X.iloc[-60:].index
prob1_final=pd.DataFrame.from_dict(prob1)
prob1_final.set_index('date')
prob2['date']=X.iloc[-60:].index
prob2_final=pd.DataFrame.from_dict(prob2)
prob2_final.set_index('date')

ABBV  \
date                                                            
2022-01-04  [0.11451990658566992, 0.20500731722344379, 0.2...   
2022-01-05  [0.15599800336594474, 0.1765179831906511, 0.19...   
2022-01-06  [0.1091521597514361, 0.2035454485473406, 0.264...   
2022-01-07  [0.12798830257241442, 0.18400874137264608, 0.2...   
2022-01-10  [0.15752470370800487, 0.16822391180935928, 0.2...   
2022-01-11  [0.11989225118365363, 0.2129435603053818, 0.24...   
2022-01-12  [0.13704590366045535, 0.21019654210239952, 0.2...   
2022-01-13  [0.11025090583398571, 0.23019990713583588, 0.2...   
2022-01-14  [0.16557774868761777, 0.1151099591715128, 0.22...   
2022-01-18  [0.17768619834330263, 0.16713051853394015, 0.1...   
2022-01-19  [0.1297156498760549, 0.22060100731841378, 0.24...   
2022-01-20  [0.12370088125325822, 0.1926764709890375, 0.27...   
2022-01-21  [0.15570495809995283, 0.13520957709867767, 0.2...   
2022-01-24  [0.1363396309083672, 0.1356504937391096, 0.285...   
2022-01-25  [0.17693430847112, 0.14950157003634434, 0.2107...   
2022-01-26  [0.17631691851755446, 0.15947357875138096, 0.2...   
2022-01-27  [0.18177179008096248, 0.17388992718345966, 0.1...   
2022-01-28  [0.14495682544067545, 0.22025572971871757, 0.2...   
2022-01-31  [0.11704838930232528, 0.2753499428026293, 0.24...   
2022-02-01  [0.14045652029030314, 0.24641950036249782, 0.2...   
2022-02-02  [0.1640347780657329, 0.2316580751897211, 0.197...   
2022-02-03  [0.19024154678525756, 0.21886427707337996, 0.1...   
2022-02-04  [0.17011183760849805, 0.2370297460683742, 0.18...   
2022-02-07  [0.201050032854301, 0.2060609228245862, 0.1636...   
2022-02-08  [0.15098186931417862, 0.25825644716161256, 0.2...   
2022-02-09  [0.13061513026834307, 0.27732221924259004, 0.2...   
2022-02-10  [0.19649601433118927, 0.2169406705281946, 0.15...   
2022-02-11  [0.18306812888046178, 0.22101110108541033, 0.1...   
2022-02-14  [0.2059436794693217, 0.20076721238922, 0.16188...   
2022-02-15  [0.15889224736575294, 0.23886749485677522, 0.2...   
2022-02-16  [0.19225152121606343, 0.2241172851277271, 0.16...   
2022-02-17  [0.18344981400259178, 0.22419242810493972, 0.1...   
2022-02-18  [0.1528329826350372, 0.23994565506809076, 0.21...   
2022-02-22  [0.20493017649614764, 0.19447720130528834, 0.1...   
2022-02-23  [0.20704394211356023, 0.2063627352532021, 0.15...   
2022-02-24  [0.13820368662709714, 0.2512320574208079, 0.23...   
2022-02-25  [0.17543666808908395, 0.20513082831434734, 0.2...   
2022-02-28  [0.1493545883333109, 0.2535070738105569, 0.208...   
2022-03-01  [0.18600316759018015, 0.20456387328451672, 0.1...   
2022-03-02  [0.1501365075861512, 0.22429371037989138, 0.22...   
2022-03-03  [0.181445416885755, 0.2091008726202215, 0.1787...   
2022-03-04  [0.16025894388204331, 0.22885921934658338, 0.1...   
2022-03-07  [0.17909504941271825, 0.21542022398216706, 0.1...   
2022-03-08  [0.14330964936182763, 0.22551930749270008, 0.2...   
2022-03-09  [0.14192589713079076, 0.2029655601530935, 0.24...   
2022-03-10  [0.1719652868459633, 0.20893158269648213, 0.19...   
2022-03-11  [0.19681336129775934, 0.2000936464954313, 0.17...   
2022-03-14  [0.1995976443903771, 0.19768241295859224, 0.16...   
2022-03-15  [0.17562692478049508, 0.22344003437710327, 0.1...   
2022-03-16  [0.1314729938604391, 0.25430194350362145, 0.22...   
2022-03-17  [0.16773356010650153, 0.2141101584635507, 0.18...   
2022-03-18  [0.1405865902227135, 0.23482275895388435, 0.20...   
2022-03-21  [0.1637928347429135, 0.20693166129269355, 0.18...   
2022-03-22  [0.12195913232877788, 0.2251880435245021, 0.23...   
2022-03-23  [0.14236823545681537, 0.20831182645846189, 0.2...   
2022-03-24  [0.13936170214479307, 0.19247342970071224, 0.2...   
2022-03-25  [0.13117006230083852, 0.2130237142863139, 0.21...   
2022-03-28  [0.1308536511476306, 0.2123474691445984, 0.217...   
2022-03-29  [0.10794096155481828, 0.23771382000632002, 0.2...   
2022-03-30  [0.1636984127275913, 0.18586067224910577, 0.17...   

                          

######SOLVER 1
***

In [21]:
RPS=pd.DataFrame()

# RPS=RPS.drop('date',axis=1)
# print(RPS.index[2])
for k in prob1_final.index: #for everyday of a stock->index
  prob=pd.DataFrame()
  prob1=pd.DataFrame()
  predic=pd.DataFrame()
  if(prob1_final['date'][k]!=prob1_final['date'].tail(1).values): #if it's not for the last day 
    #for historical data of two days 
    prob=rd.loc[(rd.index.date==prob1_final['date'][k])]
    prob1=rd.loc[ (rd.index.date==prob1_final['date'][k+1])]
    prob=create_historical(prob)
    prob1=create_historical(prob1)
    hist_data=prob.append(prob1)
    # print(hist_data)
    predic=prob1_final.loc[prob1_final['date']==prob1_final['date'][k]] #find predictions of this day
    predic=predic.drop('date',axis=1)
    # print(predic)
    data=pd.DataFrame(index=predic.columns)
    data=data.reset_index()
    # print(data)
    data[['Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']]=(0,0,0,0,0)
    for i in range(len(np.array_split(predic.values[0],46))-1):
      # print(i)
      # print(np.array_split(predic.values[0],46)[i][0])
      data.loc[i,['Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']]=np.array_split(predic.values[0],46)[i][0]
    data.columns = ['ID','Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']
    # print(data)
    #now we have data->predictions and hist_data->historical data so now we can call the RPS
    rps=RPS_calculation(hist_data = hist_data , submission = data)['details']
    # print(rps) ->rps for every stock for one day 
    # print(rps['RPS'])
    tmp=pd.DataFrame(rps['RPS'].values).T
    # print(tmp.T)
    RPS=RPS.append(tmp,ignore_index=True)
    # print(RPS[RPS.index==k])

    
  else:
    #for the last day
    prob=rd.loc[(rd.index.date==prob1_final['date'][k])]
    prob1=rd.loc[ (rd.index.date==rd.index.date[-1])]
    prob=create_historical(prob)
    prob1=create_historical(prob1)
    hist_data=prob.append(prob1)
    # print(hist_data)
    predic=prob1_final.loc[prob1_final['date']==prob1_final['date'][k]] #find predictions of this day
    predic=predic.drop('date',axis=1)
    # print(predic)
    data=pd.DataFrame(index=predic.columns)
    data=data.reset_index()
    # print(data)
    data[['Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']]=(0,0,0,0,0)
    for i in range(len(np.array_split(predic.values[0],46))-1):
      # print(i)
      # print(np.array_split(predic.values[0],46)[i][0])
      data.loc[i,['Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']]=np.array_split(predic.values[0],46)[i][0]
    data.columns = ['ID','Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']
    # print(data)
    #now we have data->predictions and hist_data->historical data so now we can call the RPS
    rps=RPS_calculation(hist_data = hist_data , submission = data)['details']
    # print(rps) ->rps for every stock for one day 
    # print(rps['RPS'])
    tmp=pd.DataFrame(rps['RPS'].values).T
    # print(tmp.T)
    RPS=RPS.append(tmp,ignore_index=True)              
print(RPS)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior.  In a future version these will be considered non-comparable.Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.
  # This is added back by InteractiveShellApp.init_path()
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior.  In a future version these will be considered non-comparable.Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.
  if sys.path[0] == '':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:42: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior.  In a future version these will be considered non-comparable.Use 'ts == pd.Timestamp(date)' or 'ts.date() == dat

          0         1         2         3         4         5         6   \
0   0.207296  0.276089  0.090933  0.109802  0.249597  0.126248  0.104309   
1   0.149639  0.099568  0.130542  0.267039  0.173454  0.123140  0.121897   
2   0.067546  0.264453  0.259943  0.131117  0.188133  0.117335  0.097844   
3   0.201159  0.059611  0.262438  0.122122  0.180455  0.076393  0.117184   
4   0.150883  0.219676  0.075249  0.096903  0.113346  0.252290  0.250839   
5   0.068461  0.124331  0.110045  0.109250  0.202468  0.122852  0.117278   
6   0.279489  0.285580  0.107900  0.123293  0.129372  0.129001  0.214223   
7   0.228302  0.133410  0.066868  0.125246  0.183029  0.119933  0.126335   
8   0.174591  0.127918  0.063155  0.101605  0.156123  0.255860  0.118494   
9   0.144112  0.129701  0.056719  0.077633  0.267478  0.263697  0.212126   
10  0.127666  0.125989  0.092154  0.267319  0.330134  0.070072  0.212307   
11  0.101730  0.273558  0.050508  0.231387  0.218464  0.288472  0.211924   
12  0.159506

In [22]:
d=prob1_final['date']
name=prob1_final.columns[:-1]
# print(np.split(name.values,len(name)))
# print(d.values)
RPS['date']=d.values
RPS=RPS.set_index('date')
RPS.columns=assets
RPS

ABBV       AEP       AIZ      ALLE      AMAT       AMP  \
date                                                                     
2022-01-04  0.207296  0.276089  0.090933  0.109802  0.249597  0.126248   
2022-01-05  0.149639  0.099568  0.130542  0.267039  0.173454  0.123140   
2022-01-06  0.067546  0.264453  0.259943  0.131117  0.188133  0.117335   
2022-01-07  0.201159  0.059611  0.262438  0.122122  0.180455  0.076393   
2022-01-10  0.150883  0.219676  0.075249  0.096903  0.113346  0.252290   
2022-01-11  0.068461  0.124331  0.110045  0.109250  0.202468  0.122852   
2022-01-12  0.279489  0.285580  0.107900  0.123293  0.129372  0.129001   
2022-01-13  0.228302  0.133410  0.066868  0.125246  0.183029  0.119933   
2022-01-14  0.174591  0.127918  0.063155  0.101605  0.156123  0.255860   
2022-01-18  0.144112  0.129701  0.056719  0.077633  0.267478  0.263697   
2022-01-19  0.127666  0.125989  0.092154  0.267319  0.330134  0.070072   
2022-01-20  0.101730  0.273558  0.050508  0.231387  0.218464  0.288472   
2022-01-21  0.159506  0.240531  0.143095  0.275427  0.126040  0.069021   
2022-01-24  0.193205  0.107572  0.139052  0.107513  0.229370  0.067363   
2022-01-25  0.204731  0.121113  0.281113  0.080756  0.124463  0.094331   
2022-01-26  0.209767  0.120548  0.248466  0.078950  0.203755  0.228564   
2022-01-27  0.080440  0.111160  0.060643  0.261820  0.136211  0.282384   
2022-01-28  0.266010  0.126402  0.099033  0.076951  0.161142  0.096788   
2022-01-31  0.106544  0.239943  0.101180  0.260688  0.130142  0.094859   
2022-02-01  0.068488  0.104679  0.064353  0.129619  0.118985  0.100758   
2022-02-02  0.251250  0.261431  0.117612  0.278522  0.147603  0.122219   
2022-02-03  0.111683  0.110617  0.107747  0.234297  0.128069  0.101931   
2022-02-04  0.255910  0.111707  0.069157  0.120916  0.114572  0.227516   
2022-02-07  0.119765  0.111822  0.097491  0.076443  0.127566  0.074961   
2022-02-08  0.247465  0.121423  0.251478  0.243199  0.205513  0.075447   
2022-02-09  0.267875  0.124246  0.142865  0.223879  0.168240  0.233538   
2022-02-10  0.111841  0.243792  0.252391  0.081140  0.258087  0.250357   
2022-02-11  0.251985  0.239475  0.094592  0.072997  0.125856  0.144806   
2022-02-14  0.083334  0.251258  0.256998  0.255936  0.181730  0.200181   
2022-02-15  0.255684  0.128262  0.257866  0.294246  0.245073  0.220840   
2022-02-16  0.113379  0.231695  0.085728  0.092159  0.126873  0.266220   
2022-02-17  0.115776  0.143431  0.076068  0.075019  0.263705  0.202609   
2022-02-18  0.255616  0.278408  0.089108  0.075707  0.324543  0.071474   
2022-02-22  0.246697  0.074632  0.088343  0.258211  0.134024  0.071423   
2022-02-23  0.235734  0.137535  0.071989  0.089888  0.148851  0.163755   
2022-02-24  0.066964  0.138811  0.101249  0.107746  0.156183  0.188883   
2022-02-25  0.122260  0.276057  0.256072  0.083136  0.177995  0.070762   
2022-02-28  0.115454  0.140106  0.143848  0.246782  0.161897  0.280028   
2022-03-01  0.122224  0.100531  0.073041  0.131614  0.113558  0.199794   
2022-03-02  0.108851  0.266737  0.268956  0.119096  0.228653  0.068806   
2022-03-03  0.079205  0.306041  0.072293  0.081461  0.297755  0.292406   
2022-03-04  0.108303  0.303108  0.246867  0.080715  0.192048  0.294738   
2022-03-07  0.121827  0.093978  0.073400  0.240352  0.134218  0.066272   
2022-03-08  0.122341  0.212646  0.069330  0.099599  0.138893  0.205927   
2022-03-09  0.104129  0.131116  0.111109  0.247374  0.218220  0.066309   
2022-03-10  0.242501  0.145338  0.253604  0.128115  0.130707  0.094696   
2022-03-11  0.246320  0.090366  0.073661  0.078912  0.241188  0.067478   
2022-03-14  0.108689  0.101402  0.071687  0.113417  0.135123  0.095760   
2022-03-15  0.118001  0.215198  0.122963  0.081458  0.218713  0.232490   
2022-03-16  0.112400  0.218236  0.075314  0.082199  0.132691  0.108549   
2022-03-17  0.078044  0.226182  0.126398  0.119009  0.205186  0.074158   
2022-03-18  0.105706  0.114886  0.245277  0.123879  0.123526  0.109405   
2022-03-21  0.131356

######SOLVER 2
***

In [23]:
#--- do the same but with solver 2 -->prob2_final---#
RPS2=pd.DataFrame()

# RPS2=RPS2.drop('date',axis=1)
# print(RPS2.index[2])
for k in prob2_final.index: #for everyday of a stock->index
  prob=pd.DataFrame()
  prob1=pd.DataFrame()
  predic=pd.DataFrame()
  if(prob2_final['date'][k]!=prob2_final['date'].tail(1).values): #if it's not for the last day 
    #for historical data of two days 
    prob=rd.loc[(rd.index.date==prob2_final['date'][k])]
    prob1=rd.loc[ (rd.index.date==prob2_final['date'][k+1])]
    prob=create_historical(prob)
    prob1=create_historical(prob1)
    hist_data=prob.append(prob1)
    # print(hist_data)
    predic=prob2_final.loc[prob2_final['date']==prob2_final['date'][k]] #find predictions of this day
    predic=predic.drop('date',axis=1)
    # print(predic)
    data=pd.DataFrame(index=predic.columns)
    data=data.reset_index()
    # print(data)
    data[['Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']]=(0,0,0,0,0)
    for i in range(len(np.array_split(predic.values[0],46))-1):
      # print(i)
      # print(np.array_split(predic.values[0],46)[i][0])
      data.loc[i,['Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']]=np.array_split(predic.values[0],46)[i][0]
    data.columns = ['ID','Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']
    # print(data)
    #now we have data->predictions and hist_data->historical data so now we can call the RPS2
    rps2=RPS_calculation(hist_data = hist_data , submission = data)['details']
    # print(RPS2) ->RPS2 for every stock for one day 
    # print(RPS2['RPS'])
    tmp=pd.DataFrame(rps2['RPS'].values).T
    # print(tmp.T)
    RPS2=RPS2.append(tmp,ignore_index=True)
    # print(RPS2[RPS2.index==k])

    
  else:
    #for the last day
    prob=rd.loc[(rd.index.date==prob2_final['date'][k])]
    prob1=rd.loc[ (rd.index.date==rd.index.date[-1])]
    prob=create_historical(prob)
    prob1=create_historical(prob1)
    hist_data=prob.append(prob1)
    # print(hist_data)
    predic=prob2_final.loc[prob2_final['date']==prob2_final['date'][k]] #find predictions of this day
    predic=predic.drop('date',axis=1)
    # print(predic)
    data=pd.DataFrame(index=predic.columns)
    data=data.reset_index()
    # print(data)
    data[['Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']]=(0,0,0,0,0)
    for i in range(len(np.array_split(predic.values[0],46))-1):
      # print(i)
      # print(np.array_split(predic.values[0],46)[i][0])
      data.loc[i,['Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']]=np.array_split(predic.values[0],46)[i][0]
    data.columns = ['ID','Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']
    # print(data)
    #now we have data->predictions and hist_data->historical data so now we can call the RPS2
    rps2=RPS_calculation(hist_data = hist_data , submission = data)['details']
    # print(RPS2) ->RPS2 for every stock for one day 
    # print(RPS2['RPS2'])
    tmp=pd.DataFrame(rps2['RPS'].values).T
    # print(tmp.T)
    RPS2=RPS2.append(tmp,ignore_index=True)              
print(RPS2)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior.  In a future version these will be considered non-comparable.Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.
  if sys.path[0] == '':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:13: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior.  In a future version these will be considered non-comparable.Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.
  del sys.path[0]
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:43: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior.  In a future version these will be considered non-comparable.Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.


          0         1         2         3         4         5         6   \
0   0.207156  0.276100  0.090985  0.109773  0.249631  0.126381  0.104084   
1   0.149597  0.099599  0.130546  0.267121  0.173516  0.123177  0.122030   
2   0.067543  0.264519  0.260148  0.131210  0.188042  0.117371  0.097654   
3   0.201089  0.059633  0.262584  0.122147  0.180266  0.076359  0.117266   
4   0.150824  0.219714  0.075164  0.096797  0.113466  0.252261  0.250697   
5   0.068455  0.124333  0.109961  0.109179  0.202696  0.122877  0.117351   
6   0.279580  0.285545  0.107727  0.123341  0.129393  0.129014  0.214549   
7   0.228127  0.133385  0.066827  0.125306  0.183066  0.119904  0.126061   
8   0.174849  0.127918  0.063117  0.101525  0.156264  0.255893  0.118582   
9   0.144048  0.129695  0.056690  0.077540  0.267472  0.263899  0.212388   
10  0.127747  0.126013  0.092155  0.267465  0.329511  0.070143  0.212396   
11  0.101683  0.273599  0.050547  0.231468  0.217922  0.288549  0.211836   
12  0.159384

In [24]:
d2=prob2_final['date']
name2=prob2_final.columns[:-1]
RPS2['date']=d2.values
RPS2=RPS2.set_index('date')
RPS2.columns=assets
RPS2

ABBV       AEP       AIZ      ALLE      AMAT       AMP  \
date                                                                     
2022-01-04  0.207156  0.276100  0.090985  0.109773  0.249631  0.126381   
2022-01-05  0.149597  0.099599  0.130546  0.267121  0.173516  0.123177   
2022-01-06  0.067543  0.264519  0.260148  0.131210  0.188042  0.117371   
2022-01-07  0.201089  0.059633  0.262584  0.122147  0.180266  0.076359   
2022-01-10  0.150824  0.219714  0.075164  0.096797  0.113466  0.252261   
2022-01-11  0.068455  0.124333  0.109961  0.109179  0.202696  0.122877   
2022-01-12  0.279580  0.285545  0.107727  0.123341  0.129393  0.129014   
2022-01-13  0.228127  0.133385  0.066827  0.125306  0.183066  0.119904   
2022-01-14  0.174849  0.127918  0.063117  0.101525  0.156264  0.255893   
2022-01-18  0.144048  0.129695  0.056690  0.077540  0.267472  0.263899   
2022-01-19  0.127747  0.126013  0.092155  0.267465  0.329511  0.070143   
2022-01-20  0.101683  0.273599  0.050547  0.231468  0.217922  0.288549   
2022-01-21  0.159384  0.240477  0.143057  0.275622  0.126551  0.069146   
2022-01-24  0.193319  0.107697  0.138901  0.107436  0.228948  0.067509   
2022-01-25  0.204871  0.121162  0.281072  0.080679  0.124825  0.094298   
2022-01-26  0.209848  0.120593  0.248616  0.078837  0.203567  0.228372   
2022-01-27  0.080458  0.111134  0.060736  0.261922  0.136011  0.282335   
2022-01-28  0.266197  0.126302  0.098993  0.076908  0.161571  0.096687   
2022-01-31  0.106690  0.239843  0.101096  0.260768  0.130135  0.094857   
2022-02-01  0.068453  0.104777  0.064364  0.129707  0.119058  0.100780   
2022-02-02  0.251099  0.261415  0.117605  0.278623  0.147508  0.122166   
2022-02-03  0.111647  0.110613  0.107743  0.234343  0.128000  0.101874   
2022-02-04  0.255731  0.111758  0.069101  0.121073  0.114727  0.227646   
2022-02-07  0.119818  0.111821  0.097588  0.076424  0.127757  0.074927   
2022-02-08  0.247729  0.121378  0.251416  0.243190  0.205841  0.075384   
2022-02-09  0.267611  0.124187  0.143014  0.223768  0.168204  0.233785   
2022-02-10  0.111810  0.243881  0.252667  0.081302  0.257930  0.250229   
2022-02-11  0.251879  0.239523  0.094482  0.073046  0.125881  0.144853   
2022-02-14  0.083354  0.251160  0.256929  0.255925  0.182085  0.200147   
2022-02-15  0.255509  0.128230  0.257762  0.294419  0.245281  0.220939   
2022-02-16  0.113304  0.231701  0.085602  0.092027  0.126901  0.266059   
2022-02-17  0.115871  0.143308  0.076105  0.074943  0.263410  0.202598   
2022-02-18  0.255433  0.278243  0.089131  0.075618  0.323843  0.071508   
2022-02-22  0.246697  0.074611  0.088280  0.258299  0.133872  0.071502   
2022-02-23  0.235718  0.137461  0.072052  0.089761  0.149400  0.163884   
2022-02-24  0.066918  0.138733  0.101331  0.107745  0.155930  0.188486   
2022-02-25  0.122335  0.275995  0.256015  0.082999  0.177781  0.070809   
2022-02-28  0.115293  0.140040  0.143934  0.246812  0.161782  0.280078   
2022-03-01  0.122284  0.100561  0.073035  0.131653  0.113654  0.199534   
2022-03-02  0.108739  0.266785  0.268934  0.119082  0.228327  0.068885   
2022-03-03  0.079204  0.305930  0.072284  0.081462  0.297305  0.292469   
2022-03-04  0.108232  0.302997  0.246958  0.080745  0.191751  0.294961   
2022-03-07  0.121882  0.094048  0.073373  0.240385  0.134640  0.066481   
2022-03-08  0.122432  0.212693  0.069295  0.099461  0.139059  0.205419   
2022-03-09  0.104049  0.131065  0.111198  0.247404  0.218050  0.066403   
2022-03-10  0.242408  0.145216  0.253590  0.128208  0.130622  0.094651   
2022-03-11  0.246291  0.090450  0.073625  0.078896  0.241019  0.067540   
2022-03-14  0.108666  0.101437  0.071653  0.113395  0.135463  0.095742   
2022-03-15  0.118088  0.215223  0.122820  0.081388  0.219005  0.232272   
2022-03-16  0.112283  0.218192  0.075268  0.082177  0.132704  0.108601   
2022-03-17  0.078038  0.226091  0.126250  0.119059  0.205282  0.074144   
2022-03-18  0.105660  0.114972  0.245472  0.123973  0.123578  0.109482   
2022-03-21  0.131379

#####Final RPS calculation for Logistic Regression

In [26]:
print(RPS.mean(axis=1).mean())
print(RPS2.mean(axis=1).mean())

0.15973738477770036
0.15973583679836742


#####Model Random Forest

Random forest algorithm can be used for both classifications and regression task. It provides higher accuracy through cross validation. Random forest classifier will handle the missing values and maintain the accuracy of a large proportion of data.

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
model3=RandomForestClassifier(n_estimators=100)

In [ ]:
prob3=dict()

for j in assets:
    tmp3=[]
    df=stock[j]
    df1=df.dropna()
    X= df1.iloc[:,5:14]
    # print(X) #it has all the days
    y= df1['Rank']
    X_train= X.iloc[:-60] #only the days of one year until 3/01
    # print(X_train)
    Y_train= y.iloc[:-60]
    # print(Y_train)
    model3.fit(X_train,Y_train)
    #now each day we will use the models to predict 
    for i in range(59,0,-1): #from 4/01 and later -->predictions
      X_validation=X.iloc[-(i+1):-i] 
      # print(X_validation)
      Y_validation= y.iloc[-(i+1):-i]
      print(Y_validation.index) 
      probability3= model3.predict_proba(X_validation)
      print(probability3[0])
      tmp3.append(probability3[0])
    X_validation=X.tail(1) 
    # print(X_validation)
    Y_validation= y.tail(1)
    print(Y_validation.index) 
    probability3= model3.predict_proba(X_validation)
    print(probability3[0])
    tmp3.append(probability3[0])
    prob3[j]=tmp3
   

Streaming output truncated to the last 5000 lines.
DatetimeIndex(['2022-02-02'], dtype='datetime64[ns]', name='Date', freq=None)
[0.05 0.32 0.07 0.47 0.09]
DatetimeIndex(['2022-02-03'], dtype='datetime64[ns]', name='Date', freq=None)
[0.11 0.25 0.17 0.31 0.16]
DatetimeIndex(['2022-02-04'], dtype='datetime64[ns]', name='Date', freq=None)
[0.08 0.32 0.12 0.17 0.31]
DatetimeIndex(['2022-02-07'], dtype='datetime64[ns]', name='Date', freq=None)
[0.04 0.36 0.07 0.38 0.15]
DatetimeIndex(['2022-02-08'], dtype='datetime64[ns]', name='Date', freq=None)
[0.28 0.13 0.18 0.32 0.09]
DatetimeIndex(['2022-02-09'], dtype='datetime64[ns]', name='Date', freq=None)
[0.13 0.27 0.12 0.29 0.19]
DatetimeIndex(['2022-02-10'], dtype='datetime64[ns]', name='Date', freq=None)
[0.13 0.22 0.11 0.19 0.35]
DatetimeIndex(['2022-02-11'], dtype='datetime64[ns]', name='Date', freq=None)
[0.15 0.48 0.13 0.11 0.13]
DatetimeIndex(['2022-02-14'], dtype='datetime64[ns]', name='Date', freq=None)
[0.12 0.31 0.16 0.32 0.09]
Date

In [ ]:
prob3['date']=X.iloc[-60:].index
prob3_final=pd.DataFrame.from_dict(prob3)
prob3_final.set_index('date')


ABBV                             AEP  \
date                                                                         
2022-01-04  [0.12, 0.33, 0.19, 0.13, 0.23]    [0.13, 0.21, 0.26, 0.3, 0.1]   
2022-01-05  [0.05, 0.13, 0.21, 0.27, 0.34]  [0.19, 0.31, 0.18, 0.24, 0.08]   
2022-01-06  [0.05, 0.16, 0.29, 0.26, 0.24]  [0.31, 0.23, 0.16, 0.28, 0.02]   
2022-01-07   [0.1, 0.26, 0.25, 0.17, 0.22]  [0.29, 0.27, 0.21, 0.18, 0.05]   
2022-01-10   [0.13, 0.2, 0.33, 0.12, 0.22]  [0.34, 0.26, 0.09, 0.16, 0.15]   
2022-01-11  [0.05, 0.29, 0.23, 0.24, 0.19]   [0.4, 0.23, 0.05, 0.23, 0.09]   
2022-01-12  [0.06, 0.49, 0.12, 0.12, 0.21]  [0.14, 0.19, 0.25, 0.31, 0.11]   
2022-01-13  [0.05, 0.31, 0.13, 0.23, 0.28]   [0.22, 0.17, 0.22, 0.29, 0.1]   
2022-01-14  [0.31, 0.08, 0.26, 0.09, 0.26]  [0.23, 0.27, 0.12, 0.19, 0.19]   
2022-01-18  [0.08, 0.26, 0.29, 0.21, 0.16]  [0.29, 0.21, 0.14, 0.22, 0.14]   
2022-01-19  [0.08, 0.21, 0.37, 0.27, 0.07]  [0.04, 0.15, 0.16, 0.56, 0.09]   
2022-01-20  [0.15, 0.24, 0.23, 0.23, 0.15]  [0.17, 0.15, 0.19, 0.41, 0.08]   
2022-01-21   [0.21, 0.1, 0.28, 0.18, 0.23]  [0.11, 0.15, 0.29, 0.33, 0.12]   
2022-01-24   [0.2, 0.09, 0.28, 0.18, 0.25]  [0.45, 0.16, 0.16, 0.16, 0.07]   
2022-01-25    [0.2, 0.07, 0.34, 0.1, 0.29]  [0.29, 0.14, 0.22, 0.18, 0.17]   
2022-01-26   [0.16, 0.12, 0.28, 0.24, 0.2]  [0.23, 0.06, 0.31, 0.22, 0.18]   
2022-01-27   [0.16, 0.13, 0.29, 0.2, 0.22]  [0.27, 0.05, 0.39, 0.13, 0.16]   
2022-01-28  [0.13, 0.09, 0.45, 0.18, 0.15]  [0.15, 0.29, 0.17, 0.15, 0.24]   
2022-01-31   [0.11, 0.41, 0.1, 0.27, 0.11]  [0.14, 0.15, 0.13, 0.21, 0.37]   
2022-02-01     [0.2, 0.2, 0.2, 0.28, 0.12]  [0.21, 0.24, 0.14, 0.19, 0.22]   
2022-02-02  [0.29, 0.12, 0.08, 0.29, 0.22]  [0.29, 0.15, 0.19, 0.29, 0.08]   
2022-02-03  [0.31, 0.14, 0.16, 0.26, 0.13]    [0.1, 0.2, 0.36, 0.27, 0.07]   
2022-02-04   [0.2, 0.05, 0.08, 0.32, 0.35]  [0.22, 0.16, 0.25, 0.21, 0.16]   
2022-02-07     [0.11, 0.2, 0.3, 0.3, 0.09]   [0.09, 0.47, 0.2, 0.23, 0.01]   
2022-02-08   [0.25, 0.21, 0.07, 0.37, 0.1]   [0.14, 0.26, 0.22, 0.3, 0.08]   
2022-02-09   [0.2, 0.18, 0.05, 0.44, 0.13]   [0.3, 0.13, 0.12, 0.38, 0.07]   
2022-02-10   [0.2, 0.24, 0.04, 0.35, 0.17]  [0.13, 0.19, 0.25, 0.32, 0.11]   
2022-02-11  [0.24, 0.24, 0.06, 0.23, 0.23]   [0.2, 0.17, 0.43, 0.15, 0.05]   
2022-02-14  [0.17, 0.32, 0.17, 0.27, 0.07]  [0.37, 0.11, 0.13, 0.17, 0.22]   
2022-02-15   [0.19, 0.31, 0.1, 0.25, 0.15]   [0.17, 0.3, 0.16, 0.28, 0.09]   
2022-02-16   [0.2, 0.14, 0.08, 0.27, 0.31]   [0.32, 0.27, 0.23, 0.08, 0.1]   
2022-02-17  [0.21, 0.08, 0.11, 0.38, 0.22]  [0.24, 0.41, 0.23, 0.05, 0.07]   
2022-02-18  [0.17, 0.32, 0.12, 0.31, 0.08]  [0.05, 0.48, 0.15, 0.21, 0.11]   
2022-02-22  [0.17, 0.39, 0.14, 0.13, 0.17]   [0.09, 0.51, 0.1, 0.14, 0.16]   
2022-02-23  [0.17, 0.26, 0.05, 0.24, 0.28]  [0.07, 0.45, 0.17, 0.15, 0.16]   
2022-02-24   [0.2, 0.29, 0.23, 0.19, 0.09]  [0.08, 0.47, 0.09, 0.13, 0.23]   
2022-02-25   [0.15, 0.25, 0.31, 0.19, 0.1]   [0.06, 0.52, 0.1, 0.17, 0.15]   
2022-02-28    [0.1, 0.11, 0.17, 0.22, 0.4]  [0.25, 0.34, 0.25, 0.04, 0.12]   
2022-03-01     [0.1, 0.21, 0.4, 0.2, 0.09]  [0.19, 0.37, 0.13, 0.15, 0.16]   
2022-03-02  [0.12, 0.28, 0.37, 0.21, 0.02]  [0.33, 0.34, 0.07, 0.21, 0.05]   
2022-03-03  [0.31, 0.15, 0.24, 0.22, 0.08]  [0.32, 0.26, 0.11, 0.18, 0.13]   
2022-03-04  [0.22, 0.23, 0.04, 0.44, 0.07]   [0.19, 0.25, 0.2, 0.17, 0.19]   
2022-03-07  [0.21, 0.26, 0.12, 0.33, 0.08]  [0.22, 0.29, 0.15, 0.18, 0.16]   
2022-03-08  [0.12, 0.28, 0.25, 0.23, 0.12]  [0.26, 0.26, 0.08, 0.14, 0.26]   
2022-03-09  [0.07, 0.38, 0.41, 0.12, 0.02]    [0.42, 0.1, 0.1, 0.22, 0.16]   
2022-03-10  [0.14, 0.26, 0.24, 0.25, 0.11]  [0.22, 0.31, 0.17, 0.19, 0.11]   
2022-03-11  [0.11, 0.37, 0.28, 0.15, 0.09]  [0.24, 0.27, 0.15, 0.21, 0.13]   
2022-03-14  [0.14, 0.24, 0.16, 0.28, 0.18]  [0.33, 0.15, 0.07, 0.28, 0.17]   
2022-03-15  [0.37, 0.13, 0.11, 0.32, 0.07]  [0.28, 0.32, 0.16, 0.13, 0.11]   
2022-03-16  [0.05, 0.04, 0.24, 0.18, 0.49]   [0.4, 0.15, 0.1

In [ ]:
RPS3=pd.DataFrame()

for k in prob3_final.index: #for everyday of a stock->index
  prob=pd.DataFrame()
  prob1=pd.DataFrame()
  predic=pd.DataFrame()
  if(prob3_final['date'][k]!=prob3_final['date'].tail(1).values): #if it's not for the last day 
    #for historical data of two days 
    prob=rd.loc[(rd.index.date==prob1_final['date'][k])]
    prob1=rd.loc[ (rd.index.date==prob1_final['date'][k+1])]
    prob=create_historical(prob)
    prob1=create_historical(prob1)
    hist_data=prob.append(prob1)
    # print(hist_data)
    predic=prob3_final.loc[prob3_final['date']==prob3_final['date'][k]] #find predictions of this day
    predic=predic.drop('date',axis=1)
    # print(predic)
    data=pd.DataFrame(index=predic.columns)
    data=data.reset_index()
    # print(data)
    data[['Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']]=(0,0,0,0,0)
    for i in range(len(np.array_split(predic.values[0],46))-1):
      # print(i)
      # print(np.array_split(predic.values[0],46)[i][0])
      data.loc[i,['Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']]=np.array_split(predic.values[0],46)[i][0]
    data.columns = ['ID','Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']
    # print(data)
    #now we have data->predictions and hist_data->historical data so now we can call the RPS
    rps3=RPS_calculation(hist_data = hist_data , submission = data)['details']
    # print(rps) ->rps for every stock for one day 
    # print(rps['RPS'])
    tmp=pd.DataFrame(rps3['RPS'].values).T
    # print(tmp.T)
    RPS3=RPS3.append(tmp,ignore_index=True)
    # print(RPS[RPS.index==k])

    
  else:
    #for the last day
    prob=rd.loc[(rd.index.date==prob1_final['date'][k])]
    prob1=rd.loc[ (rd.index.date==rd.index.date[-1])]
    prob=create_historical(prob)
    prob1=create_historical(prob1)
    hist_data=prob.append(prob1)
    # print(hist_data)
    predic=prob3_final.loc[prob3_final['date']==prob3_final['date'][k]] #find predictions of this day
    predic=predic.drop('date',axis=1)
    # print(predic)
    data=pd.DataFrame(index=predic.columns)
    data=data.reset_index()
    # print(data)
    data[['Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']]=(0,0,0,0,0)
    for i in range(len(np.array_split(predic.values[0],46))-1):
      # print(i)
      # print(np.array_split(predic.values[0],46)[i][0])
      data.loc[i,['Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']]=np.array_split(predic.values[0],46)[i][0]
    data.columns = ['ID','Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']
    # print(data)
    #now we have data->predictions and hist_data->historical data so now we can call the RPS
    rps3=RPS_calculation(hist_data = hist_data , submission = data)['details']
    # print(rps) ->rps for every stock for one day 
    # print(rps['RPS'])
    tmp=pd.DataFrame(rps3['RPS'].values).T
    # print(tmp.T)
    RPS3=RPS3.append(tmp,ignore_index=True)              
print(RPS3)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior.  In a future version these will be considered non-comparable.Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior.  In a future version these will be considered non-comparable.Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:40: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior.  In a future version these will be considered non-comparable.Use 'ts == pd.Timestamp(date)' or 'ts.date() == dat

         0        1        2        3        4        5        6        7   \
0   0.24388  0.26050  0.04522  0.07290  0.18150  0.09364  0.09992  0.06964   
1   0.23252  0.07898  0.22860  0.17782  0.15930  0.14038  0.16188  0.07558   
2   0.07084  0.36762  0.24078  0.06274  0.19306  0.08764  0.09096  0.11330   
3   0.22402  0.09062  0.29660  0.13332  0.16556  0.10524  0.10920  0.07022   
4   0.12596  0.14284  0.08772  0.14366  0.13302  0.25590  0.30992  0.15458   
5   0.06782  0.20548  0.12200  0.03006  0.11106  0.09828  0.12364  0.09454   
6   0.24782  0.25140  0.14390  0.12268  0.18068  0.20700  0.15034  0.14740   
7   0.17812  0.11652  0.07260  0.08406  0.18444  0.10300  0.12626  0.08316   
8   0.24366  0.14468  0.09302  0.11420  0.26450  0.26572  0.14250  0.08300   
9   0.12090  0.15266  0.09582  0.09170  0.15642  0.23286  0.24814  0.26238   
10  0.12620  0.03366  0.06918  0.34796  0.40650  0.03800  0.26484  0.13284   
11  0.11630  0.24756  0.07284  0.20522  0.21140  0.32102  0.2373

In [ ]:
d3=prob3_final['date']
name3=prob3_final.columns[:-1]
# print(np.split(name.values,len(name)))
# print(d.values)
RPS3['date']=d3.values
RPS3=RPS3.set_index('date')
RPS3.columns=assets
RPS3

ABBV      AEP      AIZ     ALLE     AMAT      AMP     AMZN  \
date                                                                        
2022-01-04  0.24388  0.26050  0.04522  0.07290  0.18150  0.09364  0.09992   
2022-01-05  0.23252  0.07898  0.22860  0.17782  0.15930  0.14038  0.16188   
2022-01-06  0.07084  0.36762  0.24078  0.06274  0.19306  0.08764  0.09096   
2022-01-07  0.22402  0.09062  0.29660  0.13332  0.16556  0.10524  0.10920   
2022-01-10  0.12596  0.14284  0.08772  0.14366  0.13302  0.25590  0.30992   
2022-01-11  0.06782  0.20548  0.12200  0.03006  0.11106  0.09828  0.12364   
2022-01-12  0.24782  0.25140  0.14390  0.12268  0.18068  0.20700  0.15034   
2022-01-13  0.17812  0.11652  0.07260  0.08406  0.18444  0.10300  0.12626   
2022-01-14  0.24366  0.14468  0.09302  0.11420  0.26450  0.26572  0.14250   
2022-01-18  0.12090  0.15266  0.09582  0.09170  0.15642  0.23286  0.24814   
2022-01-19  0.12620  0.03366  0.06918  0.34796  0.40650  0.03800  0.26484   
2022-01-20  0.11630  0.24756  0.07284  0.20522  0.21140  0.32102  0.23734   
2022-01-21  0.14824  0.31132  0.14346  0.20784  0.13340  0.04308  0.16638   
2022-01-24  0.20230  0.23448  0.08294  0.16908  0.21486  0.11926  0.09828   
2022-01-25  0.19782  0.14408  0.28930  0.08890  0.03698  0.07132  0.12102   
2022-01-26  0.21152  0.10588  0.26422  0.08740  0.10716  0.23330  0.17448   
2022-01-27  0.06690  0.12900  0.05192  0.23084  0.15782  0.30340  0.31496   
2022-01-28  0.29934  0.10916  0.10132  0.08766  0.12756  0.12472  0.24814   
2022-01-31  0.07980  0.34340  0.10230  0.27398  0.13454  0.06262  0.21410   
2022-02-01  0.07488  0.12862  0.06898  0.14998  0.10330  0.11688  0.04712   
2022-02-02  0.22014  0.30420  0.11108  0.32422  0.23620  0.11820  0.17224   
2022-02-03  0.13752  0.12410  0.02900  0.22564  0.12410  0.12238  0.30906   
2022-02-04  0.12678  0.12306  0.08394  0.10658  0.13878  0.17992  0.07766   
2022-02-07  0.12968  0.05188  0.08716  0.09300  0.09028  0.08750  0.28430   
2022-02-08  0.21700  0.10608  0.25380  0.28454  0.23492  0.04638  0.10620   
2022-02-09  0.22524  0.12446  0.09436  0.27668  0.09982  0.33046  0.11428   
2022-02-10  0.09858  0.24726  0.25250  0.11070  0.27846  0.24788  0.24914   
2022-02-11  0.23450  0.21588  0.08764  0.09878  0.10972  0.19340  0.31970   
2022-02-14  0.07790  0.17356  0.28692  0.25510  0.15938  0.12696  0.14300   
2022-02-15  0.27372  0.09096  0.32752  0.30062  0.29170  0.14732  0.31620   
2022-02-16  0.08562  0.38658  0.10518  0.11764  0.21210  0.30460  0.08414   
2022-02-17  0.19132  0.25188  0.05032  0.08172  0.26520  0.28446  0.14588   
2022-02-18  0.29750  0.30758  0.06480  0.09682  0.34780  0.08268  0.21332   
2022-02-22  0.30428  0.09674  0.16622  0.36290  0.16710  0.09564  0.22796   
2022-02-23  0.27252  0.15540  0.04882  0.11052  0.09540  0.22728  0.22538   
2022-02-24  0.07332  0.15428  0.11916  0.10828  0.12328  0.18140  0.21470   
2022-02-25  0.09532  0.30498  0.26602  0.09686  0.20260  0.18666  0.10114   
2022-02-28  0.07170  0.22612  0.15860  0.46530  0.18502  0.22452  0.11300   
2022-03-01  0.11566  0.07028  0.07812  0.13812  0.14300  0.20366  0.11944   
2022-03-02  0.15354  0.40158  0.27844  0.06290  0.34806  0.16456  0.25650   
2022-03-03  0.08082  0.33436  0.07414  0.13172  0.29090  0.34222  0.09212   
2022-03-04  0.09918  0.25908  0.20468  0.11098  0.32938  0.30340  0.22810   
2022-03-07  0.09990  0.08594  0.08052  0.24030  0.16082  0.06590  0.11892   
2022-03-08  0.10226  0.20112  0.05802  0.12500  0.27588  0.14562  0.12040   
2022-03-09  0.18948  0.17136  0.14696  0.26956  0.16826  0.13458  0.28348   
2022-03-10  0.27626  0.16628  0.27764  0.05450  0.12566  0.08648  0.09522   
2022-03-11  0.32964  0.08604  0.04678  0.07834  0.35244  0.07384  0.18066   
2022-03-14  0.09760  0.12214  0.10426  0.06376  0.06852  0.10614  0.23268   
2022-03-15  0.10878  0.14962  0.14540  0.08894  0.30354  0.26826  0.13212   
2022-03-16  0.07192  0.13810  0.12404  0.12172  0.17352  0.19890  0.30596   
2022-03-17 

#####Final RPS calculation for Random Forest

In [ ]:
print(RPS3.mean(axis=1).mean())

0.1677988074074074


#####Model Gradient Boosting


Gradient boosting classifiers are a group of machine learning algorithms that combine many weak learning models together to create a strong predictive model. Decision trees are usually used when doing gradient boosting. Gradient boosting models are becoming popular because of their effectiveness at classifying complex datasets, and have recently been used to win many Kaggle data science competitions.

The Python machine learning library, Scikit-Learn, supports different implementations of gradient boosting classifiers, including XGBoost.

The objective of Gradient Boosting classifiers is to minimize the loss, or the difference between the actual class value of the training example and the predicted class value. It isn't required to understand the process for reducing the classifier's loss, but it operates similarly to gradient descent in a neural network.

**Tuning the model's hyperparameters requires some active decision making on our part. There are various arguments/hyperparameters we can tune to try and get the best accuracy for the model. One of the ways we can do this is by altering the learning rate of the model. We'll want to check the performance of the model on the training set at different learning rates, and then use the best learning rate to make predictions.**

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
model4=GradientBoostingClassifier(n_estimators=60)

In [ ]:
prob4=dict()

for j in assets:
    tmp4=[]
    df=stock[j]
    df1=df.dropna()
    X= df1.iloc[:,5:14]
    # print(X) #it has all the days
    y= df1['Rank']
    X_train= X.iloc[:-60] #only the days of one year until 3/01
    # print(X_train)
    Y_train= y.iloc[:-60]
    # print(Y_train)
    model4.fit(X_train,Y_train)
    #now each day we will use the models to predict 
    for i in range(59,0,-1): #from 4/01 and later -->predictions
      X_validation=X.iloc[-(i+1):-i] 
      # print(X_validation)
      Y_validation= y.iloc[-(i+1):-i]
      print(Y_validation.index) 
      probability4= model4.predict_proba(X_validation)
      print(probability4[0])
      tmp4.append(probability4[0])
    X_validation=X.tail(1) 
    # print(X_validation)
    Y_validation= y.tail(1)
    print(Y_validation.index) 
    probability4= model4.predict_proba(X_validation)
    print(probability4[0])
    tmp4.append(probability4[0])
    prob4[j]=tmp4

Streaming output truncated to the last 5000 lines.
[0.07811399 0.22281307 0.08652723 0.50426833 0.10827738]
DatetimeIndex(['2022-02-03'], dtype='datetime64[ns]', name='Date', freq=None)
[0.07679531 0.2108573  0.12367159 0.36857184 0.22010395]
DatetimeIndex(['2022-02-04'], dtype='datetime64[ns]', name='Date', freq=None)
[0.26077017 0.25094563 0.02873413 0.06236176 0.39718832]
DatetimeIndex(['2022-02-07'], dtype='datetime64[ns]', name='Date', freq=None)
[0.06688051 0.24127724 0.09237612 0.51628377 0.08318236]
DatetimeIndex(['2022-02-08'], dtype='datetime64[ns]', name='Date', freq=None)
[0.24689198 0.21370528 0.20466046 0.28803859 0.04670369]
DatetimeIndex(['2022-02-09'], dtype='datetime64[ns]', name='Date', freq=None)
[0.07167979 0.37075407 0.08466492 0.13758027 0.33532095]
DatetimeIndex(['2022-02-10'], dtype='datetime64[ns]', name='Date', freq=None)
[0.13221473 0.23522802 0.07085766 0.06718842 0.49451118]
DatetimeIndex(['2022-02-11'], dtype='datetime64[ns]', name='Date', freq=None)
[0.0

In [ ]:
prob4['date']=X.iloc[-60:].index
prob4_final=pd.DataFrame.from_dict(prob4)
prob4_final.set_index('date')

ABBV  \
date                                                            
2022-01-04  [0.07194361624252003, 0.3420255231001213, 0.13...   
2022-01-05  [0.0258344547034365, 0.3785456350280469, 0.109...   
2022-01-06  [0.026002130987119156, 0.14699878248207043, 0....   
2022-01-07  [0.03133528922998593, 0.4139334683181057, 0.24...   
2022-01-10  [0.03015433346108803, 0.4349309522943225, 0.28...   
2022-01-11  [0.036974975980272176, 0.39547509167808237, 0....   
2022-01-12  [0.0330151823205578, 0.3827003777470785, 0.186...   
2022-01-13  [0.030431916382102263, 0.23789505892127535, 0....   
2022-01-14  [0.3876408778447264, 0.03259103009322946, 0.48...   
2022-01-18  [0.042793496983056595, 0.3365484280513532, 0.2...   
2022-01-19  [0.01799457768462767, 0.09489827396447008, 0.5...   
2022-01-20  [0.0627503302341114, 0.14809792600574798, 0.52...   
2022-01-21  [0.21462446091022405, 0.1381511274764678, 0.34...   
2022-01-24  [0.2523581316972801, 0.07466665067628624, 0.37...   
2022-01-25  [0.017346088044883114, 0.025749791312522058, 0...   
2022-01-26  [0.03799938484995061, 0.08214936899404385, 0.2...   
2022-01-27  [0.07657379888956595, 0.17400629745361584, 0.3...   
2022-01-28  [0.11246794540021805, 0.12237795776195909, 0.4...   
2022-01-31  [0.031404506994533024, 0.7303518137287841, 0.0...   
2022-02-01  [0.038821989379415035, 0.36748413005994157, 0....   
2022-02-02  [0.8430948456396081, 0.021070240128511282, 0.0...   
2022-02-03  [0.8480232373301184, 0.03152379954842058, 0.02...   
2022-02-04  [0.22517093860766715, 0.13197941076686706, 0.0...   
2022-02-07  [0.026733759058972472, 0.1966087364607287, 0.3...   
2022-02-08  [0.5080431210097165, 0.2155431001112649, 0.012...   
2022-02-09  [0.10522986594056542, 0.2203009732686782, 0.06...   
2022-02-10  [0.18393500426391834, 0.5738568269950297, 0.01...   
2022-02-11  [0.2953502938915583, 0.4396888716858939, 0.022...   
2022-02-14  [0.014638523401988424, 0.9048659607416825, 0.0...   
2022-02-15  [0.29625747267068125, 0.6171735840575526, 0.03...   
2022-02-16  [0.06487731386329718, 0.8062796851286601, 0.01...   
2022-02-17  [0.562884684456545, 0.13383150877854147, 0.016...   
2022-02-18  [0.15902365232640767, 0.25246876703177806, 0.0...   
2022-02-22  [0.06312609036260303, 0.4566279823107698, 0.05...   
2022-02-23  [0.33837395815440674, 0.4664056935705644, 0.03...   
2022-02-24  [0.029982693313887532, 0.1719143157535835, 0.0...   
2022-02-25  [0.4163542888002099, 0.14136760335427734, 0.07...   
2022-02-28  [0.17376572973492568, 0.1722397707205896, 0.03...   
2022-03-01  [0.03579336023433795, 0.08797970970808797, 0.5...   
2022-03-02  [0.03941205727923366, 0.20404096795898066, 0.5...   
2022-03-03  [0.2391220184437426, 0.16354525839144432, 0.15...   
2022-03-04  [0.3890258342597934, 0.17596155841695113, 0.05...   
2022-03-07  [0.38780545026283775, 0.20370930087925748, 0.0...   
2022-03-08  [0.13215756890714908, 0.2988760015766448, 0.11...   
2022-03-09  [0.04344892796404842, 0.5862798571598603, 0.21...   
2022-03-10  [0.12646588981036752, 0.24067621674675344, 0.2...   
2022-03-11  [0.05003677410805966, 0.2848656560667947, 0.10...   
2022-03-14  [0.10087764938489432, 0.12377966108678307, 0.1...   
2022-03-15  [0.5445415516505226, 0.042734164845719236, 0.0...   
2022-03-16  [0.12124710150141606, 0.12161995073027089, 0.2...   
2022-03-17  [0.2936136449012585, 0.41825368154449993, 0.01...   
2022-03-18  [0.18294241543737327, 0.05467676075015676, 0.0...   
2022-03-21  [0.13647915931287868, 0.46802922381309187, 0.0...   
2022-03-22  [0.19764684354302173, 0.21101256527666398, 0.0...   
2022-03-23  [0.10325873417893831, 0.41212726427319096, 0.1...   
2022-03-24  [0.03529866848999185, 0.12737467153772913, 0.2...   
2022-03-25  [0.06434351738321169, 0.4540104195423405, 0.17...   
2022-03-28  [0.04580604283156149, 0.48304726108574636, 0.1...   
2022-03-29  [0.009811327494026807, 0.058455442358475926, 0...   
2022-03-30  [0.08173405644216415, 0.1231933361610854, 0.16...   

                          

In [ ]:
RPS4=pd.DataFrame()

for k in prob4_final.index: #for everyday of a stock->index
  prob=pd.DataFrame()
  prob1=pd.DataFrame()
  predic=pd.DataFrame()
  if(prob4_final['date'][k]!=prob4_final['date'].tail(1).values): #if it's not for the last day 
    #for historical data of two days 
    prob=rd.loc[(rd.index.date==prob1_final['date'][k])]
    prob1=rd.loc[ (rd.index.date==prob1_final['date'][k+1])]
    prob=create_historical(prob)
    prob1=create_historical(prob1)
    hist_data=prob.append(prob1)
    # print(hist_data)
    predic=prob4_final.loc[prob4_final['date']==prob4_final['date'][k]] #find predictions of this day
    predic=predic.drop('date',axis=1)
    # print(predic)
    data=pd.DataFrame(index=predic.columns)
    data=data.reset_index()
    # print(data)
    data[['Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']]=(0,0,0,0,0)
    for i in range(len(np.array_split(predic.values[0],46))-1):
      # print(i)
      # print(np.array_split(predic.values[0],46)[i][0])
      data.loc[i,['Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']]=np.array_split(predic.values[0],46)[i][0]
    data.columns = ['ID','Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']
    # print(data)
    #now we have data->predictions and hist_data->historical data so now we can call the RPS
    rps4=RPS_calculation(hist_data = hist_data , submission = data)['details']
    # print(rps) ->rps for every stock for one day 
    # print(rps['RPS'])
    tmp=pd.DataFrame(rps4['RPS'].values).T
    # print(tmp.T)
    RPS4=RPS4.append(tmp,ignore_index=True)
    # print(RPS[RPS.index==k])

    
  else:
    #for the last day
    prob=rd.loc[(rd.index.date==prob1_final['date'][k])]
    prob1=rd.loc[ (rd.index.date==rd.index.date[-1])]
    prob=create_historical(prob)
    prob1=create_historical(prob1)
    hist_data=prob.append(prob1)
    # print(hist_data)
    predic=prob4_final.loc[prob4_final['date']==prob4_final['date'][k]] #find predictions of this day
    predic=predic.drop('date',axis=1)
    # print(predic)
    data=pd.DataFrame(index=predic.columns)
    data=data.reset_index()
    # print(data)
    data[['Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']]=(0,0,0,0,0)
    for i in range(len(np.array_split(predic.values[0],46))-1):
      # print(i)
      # print(np.array_split(predic.values[0],46)[i][0])
      data.loc[i,['Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']]=np.array_split(predic.values[0],46)[i][0]
    data.columns = ['ID','Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']
    # print(data)
    #now we have data->predictions and hist_data->historical data so now we can call the RPS
    rps4=RPS_calculation(hist_data = hist_data , submission = data)['details']
    # print(rps) ->rps for every stock for one day 
    # print(rps['RPS'])
    tmp=pd.DataFrame(rps4['RPS'].values).T
    # print(tmp.T)
    RPS4=RPS4.append(tmp,ignore_index=True)              
print(RPS4)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior.  In a future version these will be considered non-comparable.Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior.  In a future version these will be considered non-comparable.Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:40: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior.  In a future version these will be considered non-comparable.Use 'ts == pd.Timestamp(date)' or 'ts.date() == dat

          0         1         2         3         4         5         6   \
0   0.224895  0.295247  0.055784  0.098178  0.388593  0.072539  0.118858   
1   0.132931  0.075694  0.271743  0.115276  0.100215  0.454259  0.125854   
2   0.049886  0.349478  0.135192  0.114299  0.130974  0.039641  0.010178   
3   0.285876  0.084549  0.387078  0.157240  0.289519  0.139158  0.184988   
4   0.071003  0.093759  0.144423  0.131219  0.103607  0.117737  0.377815   
5   0.056997  0.098518  0.075029  0.001768  0.052254  0.211038  0.115573   
6   0.290439  0.346540  0.136435  0.069586  0.111519  0.324322  0.249128   
7   0.247167  0.094970  0.128357  0.061859  0.039212  0.077839  0.140946   
8   0.408896  0.155932  0.166881  0.103763  0.283436  0.211611  0.208846   
9   0.108455  0.139144  0.199502  0.229567  0.192225  0.296091  0.193692   
10  0.187659  0.098846  0.094456  0.464741  0.407258  0.156239  0.302129   
11  0.119616  0.226443  0.269321  0.195459  0.300672  0.499119  0.273560   
12  0.117239

In [ ]:
d4=prob4_final['date']
name4=prob4_final.columns[:-1]
# print(np.split(name.values,len(name)))
# print(d.values)
RPS4['date']=d4.values
RPS4=RPS4.set_index('date')
RPS4.columns=assets
RPS4

ABBV       AEP       AIZ      ALLE      AMAT       AMP  \
date                                                                     
2022-01-04  0.224895  0.295247  0.055784  0.098178  0.388593  0.072539   
2022-01-05  0.132931  0.075694  0.271743  0.115276  0.100215  0.454259   
2022-01-06  0.049886  0.349478  0.135192  0.114299  0.130974  0.039641   
2022-01-07  0.285876  0.084549  0.387078  0.157240  0.289519  0.139158   
2022-01-10  0.071003  0.093759  0.144423  0.131219  0.103607  0.117737   
2022-01-11  0.056997  0.098518  0.075029  0.001768  0.052254  0.211038   
2022-01-12  0.290439  0.346540  0.136435  0.069586  0.111519  0.324322   
2022-01-13  0.247167  0.094970  0.128357  0.061859  0.039212  0.077839   
2022-01-14  0.408896  0.155932  0.166881  0.103763  0.283436  0.211611   
2022-01-18  0.108455  0.139144  0.199502  0.229567  0.192225  0.296091   
2022-01-19  0.187659  0.098846  0.094456  0.464741  0.407258  0.156239   
2022-01-20  0.119616  0.226443  0.269321  0.195459  0.300672  0.499119   
2022-01-21  0.117239  0.203995  0.127944  0.085042  0.071020  0.137045   
2022-01-24  0.289892  0.203476  0.105672  0.377740  0.044503  0.041837   
2022-01-25  0.352891  0.246856  0.331848  0.073992  0.034083  0.146701   
2022-01-26  0.193428  0.196445  0.298358  0.156681  0.007373  0.321091   
2022-01-27  0.048820  0.117317  0.069624  0.217113  0.241296  0.276818   
2022-01-28  0.297073  0.137995  0.169059  0.088546  0.069871  0.087084   
2022-01-31  0.019048  0.303413  0.118407  0.360842  0.258335  0.011805   
2022-02-01  0.047247  0.194834  0.085608  0.170679  0.114663  0.056021   
2022-02-02  0.630666  0.252861  0.144232  0.345103  0.306010  0.046780   
2022-02-03  0.462649  0.114086  0.027244  0.173213  0.057643  0.120909   
2022-02-04  0.136595  0.109084  0.103668  0.155940  0.143461  0.340384   
2022-02-07  0.150941  0.067343  0.003491  0.093143  0.124599  0.186862   
2022-02-08  0.078098  0.114969  0.177310  0.324889  0.231749  0.080961   
2022-02-09  0.217183  0.118102  0.059665  0.301747  0.118445  0.207359   
2022-02-10  0.243507  0.274068  0.222466  0.142509  0.471353  0.376709   
2022-02-11  0.400865  0.112552  0.077846  0.126359  0.142040  0.225173   
2022-02-14  0.170065  0.174151  0.467626  0.191748  0.173891  0.186951   
2022-02-15  0.554094  0.028556  0.284810  0.217118  0.238839  0.157446   
2022-02-16  0.309809  0.358626  0.053498  0.149719  0.294937  0.442943   
2022-02-17  0.100447  0.256861  0.090175  0.082661  0.367274  0.325884   
2022-02-18  0.254531  0.276059  0.028649  0.090725  0.252425  0.053431   
2022-02-22  0.267542  0.142560  0.126002  0.400782  0.184578  0.031317   
2022-02-23  0.101961  0.207281  0.057661  0.125675  0.271669  0.464815   
2022-02-24  0.169990  0.102301  0.048020  0.132682  0.108426  0.048997   
2022-02-25  0.101507  0.432870  0.270473  0.261126  0.172985  0.126643   
2022-02-28  0.106700  0.099549  0.185579  0.640336  0.181699  0.193847   
2022-03-01  0.172060  0.001378  0.117843  0.024110  0.169681  0.266009   
2022-03-02  0.142549  0.344667  0.292268  0.008499  0.530434  0.319839   
2022-03-03  0.086110  0.320148  0.088275  0.097640  0.198627  0.430556   
2022-03-04  0.173123  0.214182  0.212176  0.072278  0.166598  0.436377   
2022-03-07  0.092031  0.060402  0.104226  0.224016  0.028124  0.071617   
2022-03-08  0.111871  0.265519  0.078755  0.120412  0.465660  0.217220   
2022-03-09  0.222769  0.118372  0.168254  0.229125  0.010258  0.070989   
2022-03-10  0.260473  0.473845  0.255631  0.139190  0.140783  0.157004   
2022-03-11  0.141118  0.130610  0.012662  0.087242  0.477616  0.053014   
2022-03-14  0.064416  0.129562  0.113967  0.034918  0.018189  0.204555   
2022-03-15  0.126304  0.125701  0.080208  0.137351  0.430305  0.359161   
2022-03-16  0.084555  0.219006  0.157472  0.103264  0.181181  0.213824   
2022-03-17  0.136252  0.066257  0.147373  0.055254  0.010838  0.156983   
2022-03-18  0.037391  0.308738  0.295406  0.232961  0.040257  0.070770   
2022-03-21  0.067943

#####Final RPS calculation for GB

In [ ]:
print(RPS4.mean(axis=1).mean())

0.19257575108656763


#####Model XGB

In [ ]:
import xgboost as xgb
from xgboost.sklearn import XGBClassifier
model5=XGBClassifier()

In [ ]:
prob5=dict()

for j in assets:
    tmp5=[]
    df=stock[j]
    df1=df.dropna()
    X= df1.iloc[:,5:14]
    # print(X) #it has all the days
    y= df1['Rank']
    X_train= X.iloc[:-60] #only the days of one year until 3/01
    # print(X_train)
    Y_train= y.iloc[:-60]
    # print(Y_train)
    model5.fit(X_train,Y_train)
    #now each day we will use the models to predict 
    for i in range(59,0,-1): #from 4/01 and later -->predictions
      X_validation=X.iloc[-(i+1):-i] 
      # print(X_validation)
      Y_validation= y.iloc[-(i+1):-i]
      print(Y_validation.index) 
      probability5= model5.predict_proba(X_validation)
      print(probability5[0])
      tmp5.append(probability5[0])
    X_validation=X.tail(1) 
    # print(X_validation)
    Y_validation= y.tail(1)
    print(Y_validation.index) 
    probability5= model5.predict_proba(X_validation)
    print(probability5[0])
    tmp5.append(probability5[0])
    prob5[j]=tmp5

Streaming output truncated to the last 5000 lines.
DatetimeIndex(['2022-02-02'], dtype='datetime64[ns]', name='Date', freq=None)
[0.06239115 0.21725272 0.13844514 0.48062578 0.10128517]
DatetimeIndex(['2022-02-03'], dtype='datetime64[ns]', name='Date', freq=None)
[0.0697765  0.20830919 0.04626075 0.424339   0.25131458]
DatetimeIndex(['2022-02-04'], dtype='datetime64[ns]', name='Date', freq=None)
[0.09419537 0.4088754  0.0393592  0.05968793 0.3978821 ]
DatetimeIndex(['2022-02-07'], dtype='datetime64[ns]', name='Date', freq=None)
[0.0642195  0.3048434  0.07208689 0.42421314 0.13463709]
DatetimeIndex(['2022-02-08'], dtype='datetime64[ns]', name='Date', freq=None)
[0.27397645 0.30178553 0.09113355 0.2602247  0.07287979]
DatetimeIndex(['2022-02-09'], dtype='datetime64[ns]', name='Date', freq=None)
[0.18740503 0.37337255 0.10519844 0.13308768 0.20093627]
DatetimeIndex(['2022-02-10'], dtype='datetime64[ns]', name='Date', freq=None)
[0.18040225 0.2965329  0.0569291  0.303171   0.16296472]
Date

In [ ]:
prob5['date']=X.iloc[-60:].index
prob5_final=pd.DataFrame.from_dict(prob5)
prob5_final.set_index('date')

ABBV  \
date                                                            
2022-01-04  [0.060994297, 0.29048336, 0.27892724, 0.290525...   
2022-01-05  [0.049134996, 0.1291472, 0.18988, 0.3196562, 0...   
2022-01-06  [0.034661777, 0.08870259, 0.3550527, 0.2304065...   
2022-01-07  [0.04527307, 0.22241853, 0.45236418, 0.2217375...   
2022-01-10  [0.03861209, 0.24343182, 0.48524028, 0.1493781...   
2022-01-11  [0.04166027, 0.24961415, 0.23453924, 0.2201553...   
2022-01-12  [0.033646952, 0.22146691, 0.17182843, 0.280777...   
2022-01-13  [0.02888011, 0.22638464, 0.21517389, 0.2435000...   
2022-01-14  [0.42010218, 0.047636136, 0.42580032, 0.027324...   
2022-01-18  [0.086254455, 0.33060324, 0.36729357, 0.102251...   
2022-01-19  [0.021948332, 0.087794036, 0.2955591, 0.461114...   
2022-01-20  [0.032806188, 0.29247808, 0.35350198, 0.263417...   
2022-01-21  [0.34893942, 0.082573205, 0.37001315, 0.026330...   
2022-01-24  [0.26082, 0.10455318, 0.24562635, 0.18791917, ...   
2022-01-25  [0.07325419, 0.05980327, 0.694752, 0.035715394...   
2022-01-26  [0.019769851, 0.057153825, 0.3613643, 0.442361...   
2022-01-27  [0.026134929, 0.13081384, 0.41945344, 0.266938...   
2022-01-28  [0.036631867, 0.03620594, 0.6680372, 0.0868234...   
2022-01-31  [0.018743105, 0.57310593, 0.04935142, 0.202566...   
2022-02-01  [0.06833229, 0.31588122, 0.46425727, 0.1131813...   
2022-02-02  [0.68364024, 0.062689796, 0.037082784, 0.12420...   
2022-02-03  [0.59235793, 0.16226865, 0.07942656, 0.0916364...   
2022-02-04  [0.09652806, 0.10944803, 0.0157559, 0.47777405...   
2022-02-07  [0.06063416, 0.3919284, 0.17182013, 0.29056427...   
2022-02-08  [0.3339341, 0.27756724, 0.0077876966, 0.322249...   
2022-02-09  [0.09144314, 0.5147924, 0.04473577, 0.20382321...   
2022-02-10  [0.0694026, 0.7411675, 0.0109405285, 0.1004649...   
2022-02-11  [0.19254996, 0.53494364, 0.027850736, 0.116423...   
2022-02-14  [0.027427768, 0.83516335, 0.048217915, 0.06536...   
2022-02-15  [0.14360313, 0.74822074, 0.034577303, 0.048304...   
2022-02-16  [0.079094015, 0.33675748, 0.041820157, 0.12770...   
2022-02-17  [0.33258373, 0.14480218, 0.018887145, 0.276937...   
2022-02-18  [0.1491582, 0.27908933, 0.10653769, 0.39085555...   
2022-02-22  [0.029238012, 0.5477296, 0.04650139, 0.2640737...   
2022-02-23  [0.14351168, 0.63524866, 0.02619773, 0.0352439...   
2022-02-24  [0.036866356, 0.2459455, 0.09432385, 0.3570424...   
2022-02-25  [0.31585294, 0.18795615, 0.09720409, 0.3587078...   
2022-02-28  [0.06987819, 0.26773283, 0.14516124, 0.1559252...   
2022-03-01  [0.040505122, 0.11240587, 0.61372346, 0.202944...   
2022-03-02  [0.04866042, 0.1489381, 0.5998543, 0.15597723,...   
2022-03-03  [0.22461301, 0.09305819, 0.1523479, 0.35067186...   
2022-03-04  [0.4531995, 0.19542892, 0.038696464, 0.2688213...   
2022-03-07  [0.27317077, 0.3718079, 0.037544254, 0.2454324...   
2022-03-08  [0.23908624, 0.19613406, 0.09269869, 0.2850511...   
2022-03-09  [0.042565756, 0.4739401, 0.28653172, 0.1659257...   
2022-03-10  [0.16251338, 0.30818594, 0.27084196, 0.1686083...   
2022-03-11  [0.030268887, 0.49496165, 0.104273856, 0.25173...   
2022-03-14  [0.100329526, 0.099981956, 0.17486322, 0.31669...   
2022-03-15  [0.3183385, 0.054904517, 0.00951643, 0.5148846...   
2022-03-16  [0.06609367, 0.14149731, 0.079152696, 0.119481...   
2022-03-17  [0.3268035, 0.26612362, 0.0115989195, 0.232052...   
2022-03-18  [0.08072334, 0.06823182, 0.009281277, 0.362226...   
2022-03-21  [0.18033648, 0.52134675, 0.0062677786, 0.12544...   
2022-03-22  [0.044934325, 0.24702117, 0.06441602, 0.158814...   
2022-03-23  [0.08135979, 0.21067268, 0.34023726, 0.2458098...   
2022-03-24  [0.028090557, 0.12064049, 0.21136706, 0.167473...   
2022-03-25  [0.09959985, 0.18706079, 0.41889107, 0.1631352...   
2022-03-28  [0.03419667, 0.2998939, 0.25736973, 0.23990816...   
2022-03-29  [0.046821587, 0.24728923, 0.054971654, 0.52270...   
2022-03-30  [0.15486112, 0.07882241, 0.26262876, 0.3491181...   

                          

In [ ]:
RPS5=pd.DataFrame()

for k in prob5_final.index: #for everyday of a stock->index
  prob=pd.DataFrame()
  prob1=pd.DataFrame()
  predic=pd.DataFrame()
  if(prob5_final['date'][k]!=prob5_final['date'].tail(1).values): #if it's not for the last day 
    #for historical data of two days 
    prob=rd.loc[(rd.index.date==prob1_final['date'][k])]
    prob1=rd.loc[ (rd.index.date==prob1_final['date'][k+1])]
    prob=create_historical(prob)
    prob1=create_historical(prob1)
    hist_data=prob.append(prob1)
    # print(hist_data)
    predic=prob5_final.loc[prob5_final['date']==prob5_final['date'][k]] #find predictions of this day
    predic=predic.drop('date',axis=1)
    # print(predic)
    data=pd.DataFrame(index=predic.columns)
    data=data.reset_index()
    # print(data)
    data[['Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']]=(0,0,0,0,0)
    for i in range(len(np.array_split(predic.values[0],46))-1):
      # print(i)
      # print(np.array_split(predic.values[0],46)[i][0])
      data.loc[i,['Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']]=np.array_split(predic.values[0],46)[i][0]
    data.columns = ['ID','Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']
    # print(data)
    #now we have data->predictions and hist_data->historical data so now we can call the RPS
    rps5=RPS_calculation(hist_data = hist_data , submission = data)['details']
    # print(rps) ->rps for every stock for one day 
    # print(rps['RPS'])
    tmp=pd.DataFrame(rps5['RPS'].values).T
    # print(tmp.T)
    RPS5=RPS5.append(tmp,ignore_index=True)
    # print(RPS[RPS.index==k])

    
  else:
    #for the last day
    prob=rd.loc[(rd.index.date==prob1_final['date'][k])]
    prob1=rd.loc[ (rd.index.date==rd.index.date[-1])]
    prob=create_historical(prob)
    prob1=create_historical(prob1)
    hist_data=prob.append(prob1)
    # print(hist_data)
    predic=prob5_final.loc[prob5_final['date']==prob5_final['date'][k]] #find predictions of this day
    predic=predic.drop('date',axis=1)
    # print(predic)
    data=pd.DataFrame(index=predic.columns)
    data=data.reset_index()
    # print(data)
    data[['Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']]=(0,0,0,0,0)
    for i in range(len(np.array_split(predic.values[0],46))-1):
      # print(i)
      # print(np.array_split(predic.values[0],46)[i][0])
      data.loc[i,['Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']]=np.array_split(predic.values[0],46)[i][0]
    data.columns = ['ID','Rank 1', 'Rank 2', 'Rank 3', 'Rank 4','Rank 5']
    # print(data)
    #now we have data->predictions and hist_data->historical data so now we can call the RPS
    rps5=RPS_calculation(hist_data = hist_data , submission = data)['details']
    # print(rps) ->rps for every stock for one day 
    # print(rps['RPS'])
    tmp=pd.DataFrame(rps5['RPS'].values).T
    # print(tmp.T)
    RPS5=RPS5.append(tmp,ignore_index=True)              
print(RPS5)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior.  In a future version these will be considered non-comparable.Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior.  In a future version these will be considered non-comparable.Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.
  # Remove the CWD from sys.path while we load stuff.


AttributeError: ignored